// <auto-generated/> - Extracted from KnockOffGenerator.cs
#nullable enable
namespace KnockOff;

internal sealed record KnockOffTypeInfo(
	string Namespace,
	string ClassName,
	EquatableArray<ContainingTypeInfo> ContainingTypes,
	/// <summary>
	/// Type parameters for generic standalone stub classes (e.g., T in RepositoryStub&lt;T&gt;).
	/// Empty for non-generic classes.
	/// </summary>
	EquatableArray<TypeParameterInfo> TypeParameters,
	EquatableArray<InterfaceInfo> Interfaces,
	EquatableArray<UserMethodInfo> UserMethods,
	EquatableArray<DiagnosticInfo> Diagnostics,
	/// <summary>
	/// Flat collection of all members from all interfaces, deduplicated.
	/// Used for generating interceptors directly on stub class in v10.9+ flat API.
	/// </summary>
	EquatableArray<InterfaceMemberInfo> FlatMembers,
	/// <summary>
	/// Flat collection of all events from all interfaces, deduplicated.
	/// Used for generating event interceptors directly on stub class in v10.9+ flat API.
	/// </summary>
	EquatableArray<EventMemberInfo> FlatEvents,
	/// <summary>
	/// When true, the generated constructor defaults to strict mode (throws on unconfigured calls).
	/// From [KnockOff(Strict = true)].
	/// </summary>
	bool Strict = false) : IEquatable<KnockOffTypeInfo>;

/// <summary>
/// Represents a containing type (for nested class support).
/// </summary>
internal sealed record ContainingTypeInfo(
	string Name,
	string Keyword,
	string AccessibilityModifier) : IEquatable<ContainingTypeInfo>;

/// <summary>
/// Info for a diagnostic to report.
/// </summary>
internal sealed record DiagnosticInfo(
	string Id,
	string FilePath,
	int Line,
	int Column,
	string[] Args) : IEquatable<DiagnosticInfo>;

/// <summary>
/// Strategy for generating default return values when no callback/user method is provided.
/// </summary>
internal enum DefaultValueStrategy
{
	/// <summary>Use default/default! - for value types and nullable reference types.</summary>
	Default,
	/// <summary>Use new T() - for non-nullable reference types with parameterless constructor.</summary>
	NewInstance,
	/// <summary>Throw exception - no safe default available.</summary>
	ThrowException
}
