// <auto-generated/> - Extracted from KnockOffGenerator.cs
#nullable enable
using System.Linq;
using Microsoft.CodeAnalysis;

namespace KnockOff;

internal sealed record EventMemberInfo(
	string Name,
	string FullDelegateTypeName,
	EventDelegateKind DelegateKind,
	EquatableArray<ParameterInfo> DelegateParameters,
	string? ReturnTypeName,
	bool IsAsync,
	string DeclaringInterfaceFullName,
	string AccessModifier = "public",
	/// <summary>
	/// True if the event is abstract. False for events with default add/remove handlers (DIM events).
	/// </summary>
	bool IsAbstract = true) : IEquatable<EventMemberInfo>
{
	/// <summary>
	/// Creates an EventMemberInfo from an event symbol.
	/// </summary>
	public static EventMemberInfo FromEvent(IEventSymbol eventSymbol, string declaringInterfaceFullName)
	{
		var delegateType = (INamedTypeSymbol)eventSymbol.Type;
		var invokeMethod = delegateType.DelegateInvokeMethod;

		var accessModifier = eventSymbol.DeclaredAccessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.Internal => "internal",
			_ => "public"
		};

		if (invokeMethod is null)
		{
			// Fallback for malformed delegates
			return new EventMemberInfo(
				Name: eventSymbol.Name,
				FullDelegateTypeName: delegateType.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability),
				DelegateKind: EventDelegateKind.Custom,
				DelegateParameters: EquatableArray<ParameterInfo>.Empty,
				ReturnTypeName: null,
				IsAsync: false,
				DeclaringInterfaceFullName: declaringInterfaceFullName,
				AccessModifier: accessModifier,
				IsAbstract: eventSymbol.IsAbstract);
		}

		var delegateKind = SymbolHelpers.ClassifyDelegateKind(delegateType);
		var isAsync = SymbolHelpers.IsAsyncDelegate(invokeMethod);

		var parameters = invokeMethod.Parameters
			.Select(p => new ParameterInfo(p.Name, p.Type.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability), p.RefKind))
			.ToArray();

		var returnType = invokeMethod.ReturnsVoid ? null
			: invokeMethod.ReturnType.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability);

		return new EventMemberInfo(
			Name: eventSymbol.Name,
			FullDelegateTypeName: delegateType.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability),
			DelegateKind: delegateKind,
			DelegateParameters: new EquatableArray<ParameterInfo>(parameters),
			ReturnTypeName: returnType,
			IsAsync: isAsync,
			DeclaringInterfaceFullName: declaringInterfaceFullName,
			AccessModifier: accessModifier,
			IsAbstract: eventSymbol.IsAbstract);
	}
}

internal enum EventDelegateKind
{
	EventHandler,       // System.EventHandler
	EventHandlerOfT,    // System.EventHandler<TEventArgs>
	Action,             // System.Action or Action<T...>
	Func,               // System.Func<..., TResult>
	Custom              // Custom delegate type
}
