// <auto-generated/> - Extracted from KnockOffGenerator.cs
#nullable enable
using System.Linq;
using Microsoft.CodeAnalysis;

namespace KnockOff;

/// <summary>
/// Info for all [KnockOff&lt;T&gt;] attributes on a single class.
/// </summary>
internal sealed record InlineStubClassInfo(
	string Namespace,
	string ClassName,
	EquatableArray<ContainingTypeInfo> ContainingTypes,
	EquatableArray<InterfaceInfo> Interfaces,
	EquatableArray<DelegateInfo> Delegates,
	EquatableArray<ClassStubInfo> Classes,
	EquatableArray<PartialPropertyInfo> PartialProperties,
	EquatableArray<DiagnosticInfo> Diagnostics) : IEquatable<InlineStubClassInfo>;

/// <summary>
/// Info about a partial property that should be auto-implemented to return a stub instance.
/// </summary>
internal sealed record PartialPropertyInfo(
	string PropertyName,
	string StubTypeName,
	string AccessModifier,
	bool HasGetter,
	bool HasSetter) : IEquatable<PartialPropertyInfo>;

/// <summary>
/// Info about a delegate type for generating inline delegate stubs.
/// </summary>
internal sealed record DelegateInfo(
	string FullName,
	string Name,
	string ReturnType,
	bool IsVoid,
	EquatableArray<ParameterInfo> Parameters,
	/// <summary>
	/// True when this is an open generic delegate from [KnockOff(typeof(Factory&lt;&gt;))].
	/// When true, the generated stub class will have type parameters.
	/// </summary>
	bool IsOpenGeneric = false,
	/// <summary>
	/// Type parameters for open generic delegates (e.g., T, TKey, TValue).
	/// Empty for closed generic or non-generic delegates.
	/// </summary>
	EquatableArray<TypeParameterInfo> TypeParameters = default) : IEquatable<DelegateInfo>
{
	/// <summary>
	/// Extracts delegate info for inline delegate stubs.
	/// Returns null if the delegate cannot be processed.
	/// </summary>
	public static DelegateInfo? Extract(INamedTypeSymbol delegateType, bool isOpenGeneric = false, EquatableArray<TypeParameterInfo> typeParameters = default)
	{
		// Get the Invoke method - all delegates have one
		var invokeMethod = delegateType.DelegateInvokeMethod;
		if (invokeMethod is null)
			return null;

		// Extract return type
		var returnType = invokeMethod.ReturnType.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability);
		var isVoid = invokeMethod.ReturnsVoid;

		// Extract parameters
		var parameters = invokeMethod.Parameters
			.Select(p => new ParameterInfo(
				p.Name,
				p.Type.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability),
				p.RefKind))
			.ToArray();

		return new DelegateInfo(
			FullName: delegateType.ToDisplayString(SymbolHelpers.FullyQualifiedWithNullability),
			Name: delegateType.Name,
			ReturnType: returnType,
			IsVoid: isVoid,
			Parameters: new EquatableArray<ParameterInfo>(parameters),
			IsOpenGeneric: isOpenGeneric,
			TypeParameters: typeParameters);
	}
}
