// <auto-generated/> - Extracted from KnockOffGenerator.cs
#nullable enable
using Microsoft.CodeAnalysis;

namespace KnockOff;

internal sealed record UserMethodInfo(
	string Name,
	string ReturnType,
	EquatableArray<ParameterInfo> Parameters,
	bool IsGenericMethod,
	EquatableArray<TypeParameterInfo> TypeParameters) : IEquatable<UserMethodInfo>;

/// <summary>
/// Represents a group of method overloads with the same name
/// </summary>
internal sealed record MethodGroupInfo(
	string Name,
	string ReturnType,
	bool IsVoid,
	bool IsNullable,
	EquatableArray<MethodOverloadInfo> Overloads,
	EquatableArray<CombinedParameterInfo> CombinedParameters) : IEquatable<MethodGroupInfo>;

/// <summary>
/// Represents a single method overload's parameters
/// </summary>
internal sealed record MethodOverloadInfo(
	EquatableArray<ParameterInfo> Parameters,
	bool IsGenericMethod,
	EquatableArray<TypeParameterInfo> TypeParameters) : IEquatable<MethodOverloadInfo>;

/// <summary>
/// Represents a parameter in the combined tuple (nullable if not in all overloads)
/// </summary>
internal sealed record CombinedParameterInfo(
	string Name,
	string Type,
	string NullableType,
	bool IsNullable,
	RefKind RefKind) : IEquatable<CombinedParameterInfo>;
