<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<RootNamespace>Prototype.Stubs</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Prototype.Library\Prototype.Library.csproj" />
	</ItemGroup>

</Project>
