// src/Generator/Renderer/FlatRenderer.cs
#nullable enable
using System.Collections.Generic;
using System.Linq;
using KnockOff;
using KnockOff.Builder;
using KnockOff.Model.Flat;
using KnockOff.Model.Shared;
using KnockOff.Renderer.Shared;

namespace KnockOff.Renderer;

/// <summary>
/// Renders FlatGenerationUnit to source code string.
/// Pure emission - no decisions, just output what the model says.
/// </summary>
internal static class FlatRenderer
{
	public static string Render(FlatGenerationUnit unit)
	{
		var w = new CodeWriter();

		w.Line("// <auto-generated/>");
		w.Line("#nullable enable");
		w.Line();

		// Always include System.Linq - needed for .Sum() in overload TotalCallCount and generic methods
		w.Line("using System.Linq;");
		w.Line();

		// Namespace
		if (!string.IsNullOrEmpty(unit.Namespace))
		{
			w.Line($"namespace {unit.Namespace};");
			w.Line();
		}

		// Open containing type wrappers for nested classes
		foreach (var containingType in unit.ContainingTypes)
		{
			var accessMod = string.IsNullOrEmpty(containingType.AccessModifier)
				? ""
				: containingType.AccessModifier + " ";
			w.Line($"{accessMod}partial {containingType.Keyword} {containingType.Name}");
			w.Line("{");
		}

		// Class declaration with interfaces
		var interfaces = string.Join(", ", unit.InterfaceList);
		var typeParams = FormatTypeParameters(unit.TypeParameters);
		var constraints = FormatConstraints(unit.TypeParameters);

		// Calculate the class name with type parameters for delegate signatures
		var classNameWithTypeParams = $"{unit.ClassName}{typeParams}";

		// Base class for stub overrides
		var baseClass = $"{unit.ClassName}Base{typeParams}";

		using (w.Block($"partial class {unit.ClassName}{typeParams} : {baseClass}, {interfaces}, global::KnockOff.IKnockOffStub{constraints}"))
		{
			// Track rendered interceptors to avoid duplicates
			// (Multiple interface members may map to the same interceptor)
			var renderedInterceptorClasses = new HashSet<string>();

			// Generic method interfaces if needed
			if (unit.HasGenericMethods)
				RenderGenericMethodInterfaces(w);

			// Interceptor classes (deduplicated by interceptor name)
			var propertyOptions = new PropertyInterceptorRenderOptions(
				BaseIndent: 0,
				IncludeStrictParameter: true,
				StrictAccessExpression: "strict");
			foreach (var prop in unit.Properties)
			{
				if (renderedInterceptorClasses.Add(prop.InterceptorClassName))
				{
					var unifiedModel = ModelAdapters.ToUnifiedPropertyModel(prop);
					PropertyInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, propertyOptions);
				}
			}

			var indexerOptions = new IndexerInterceptorRenderOptions(
				BaseIndent: 0,
				IncludeStrictParameter: true,
				StrictAccessExpression: "strict");
			foreach (var indexer in unit.Indexers)
			{
				if (renderedInterceptorClasses.Add(indexer.InterceptorClassName))
				{
					var unifiedModel = ModelAdapters.ToUnifiedIndexerModel(indexer);
					IndexerInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, indexerOptions);
				}
			}

			// Render indexer container classes for groups with multiple indexers
			foreach (var group in unit.IndexerGroups)
			{
				if (group.Indexers.Count > 1 && renderedInterceptorClasses.Add(group.ContainerClassName))
					RenderIndexerContainerClass(w, group);
			}

			// Render method interceptor classes using groups (handles overloads)
			// Use shared renderer for unified API between inline and flat stubs
			foreach (var group in unit.MethodGroups)
			{
				if (renderedInterceptorClasses.Add(group.InterceptorClassName))
				{
					var unifiedModel = ModelAdapters.ToUnifiedModel(group, unit.ClassName, typeParams);
					var options = new InterceptorRenderOptions(
						BaseIndent: 0,
						IncludeStrictParameter: true,
						StrictAccessExpression: "strict");
					MethodInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, options);
				}
			}

			// Render user-defined method interceptor classes (full interceptor with When/Sequence support)
			foreach (var group in unit.StubOverrideGroups)
			{
				if (renderedInterceptorClasses.Add(group.InterceptorClassName))
				{
					var unifiedModel = ModelAdapters.ToUnifiedModel(group, unit.ClassName, typeParams);
					var options = new InterceptorRenderOptions(
						BaseIndent: 0,
						IncludeStrictParameter: true,
						StrictAccessExpression: "strict",
						StubOverrideFallback: true,
						StubTypeName: classNameWithTypeParams);
					MethodInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, options);
				}
			}

			foreach (var handler in unit.GenericMethodHandlers)
			{
				if (renderedInterceptorClasses.Add(handler.InterceptorClassName))
					RenderGenericMethodHandler(w, handler, classNameWithTypeParams);
			}

			// Render generic stub override handler groups (for overloaded generic stub overrides)
			foreach (var handlerGroup in unit.GenericStubOverrideHandlerGroups)
			{
				if (renderedInterceptorClasses.Add(handlerGroup.InterceptorClassName))
					RenderGenericStubOverrideHandlerGroup(w, handlerGroup, classNameWithTypeParams);
			}

			foreach (var evt in unit.Events)
			{
				if (renderedInterceptorClasses.Add(evt.InterceptorClassName))
					RenderEventInterceptorClass(w, evt);
			}

			// Interceptor properties (public access to interceptors)
			RenderInterceptorProperties(w, unit);

			// Standard members (Strict mode, Object accessor)
			RenderStandardMembers(w, unit);

			// Source(T) methods for each interface in the hierarchy
			RenderSourceMethods(w, unit);

			// Build set of interceptor names that have multiple UNIQUE overloads (need suffixed Invoke)
			var multiOverloadInterceptors = new HashSet<string>(
				unit.MethodGroups
					.Where(g => g.Methods.Select(GetSignatureSuffix).Distinct().Count() > 1)
					.Select(g => g.InterceptorName));

			// Build set of stub override interceptor names that have multiple UNIQUE overloads (need suffixed RecordCall)
			var multiOverloadStubOverrideInterceptors = new HashSet<string>(
				unit.StubOverrideGroups
					.Where(g => g.Methods.Select(GetSignatureSuffix).Distinct().Count() > 1)
					.Select(g => g.InterceptorName));

			// Build set of generic stub override interceptor names that have multiple overloads (need suffixed RecordCall/Callback)
			// A generic handler group needs suffixes if it has multiple type arities OR multiple signatures per arity
			var multiOverloadGenericStubOverrideInterceptors = new HashSet<string>(
				unit.GenericStubOverrideHandlerGroups
					.Where(g => g.TypeArityGroups.Count > 1 ||
					            g.TypeArityGroups.Any(a => a.SignatureGroups.Count > 1))
					.Select(g => g.InterceptorName));

			// Build indexer access map for multi-indexer groups
			var indexerAccessMap = BuildIndexerAccessMap(unit.IndexerGroups);

			// Explicit interface implementations (NOT deduplicated - one per interface member)
			foreach (var prop in unit.Properties)
				RenderPropertyImplementation(w, prop);

			foreach (var indexer in unit.Indexers)
				RenderIndexerImplementation(w, indexer, indexerAccessMap);

			foreach (var method in unit.Methods)
				RenderMethodImplementation(w, method, multiOverloadInterceptors, multiOverloadStubOverrideInterceptors, multiOverloadGenericStubOverrideInterceptors, unit.GenericStubOverrideHandlerGroups);

			foreach (var evt in unit.Events)
				RenderEventImplementation(w, evt);
		}

		// Close containing type wrappers for nested classes
		for (int i = 0; i < unit.ContainingTypes.Count; i++)
		{
			w.Line("}");
		}

		return w.ToString();
	}

	/// <summary>
	/// Renders the base class file for standalone stubs.
	/// Contains virtual protected methods for each interface method, suffixed with '_'.
	/// Users can override these methods to provide default implementations.
	/// </summary>
	public static string RenderBaseClass(FlatGenerationUnit unit)
	{
		var w = new CodeWriter();

		w.Line("// <auto-generated/>");
		w.Line("#nullable enable");
		w.Line();

		// Namespace
		if (!string.IsNullOrEmpty(unit.Namespace))
		{
			w.Line($"namespace {unit.Namespace};");
			w.Line();
		}

		// Open containing type wrappers for nested classes
		foreach (var containingType in unit.ContainingTypes)
		{
			var accessMod = string.IsNullOrEmpty(containingType.AccessModifier)
				? ""
				: containingType.AccessModifier + " ";
			w.Line($"{accessMod}partial {containingType.Keyword} {containingType.Name}");
			w.Line("{");
		}

		// Base class declaration with type parameters and constraints
		var typeParams = FormatTypeParameters(unit.TypeParameters);
		var constraints = FormatConstraints(unit.TypeParameters);

		using (w.Block($"public class {unit.ClassName}Base{typeParams}{constraints}"))
		{
			// Generate virtual protected methods for each non-generic interface method
			// Generic methods are excluded from the base class pattern per design decision
			//
			// When multiple interfaces have the same method signature but different return types
			// (e.g., ISet<T>.Add returns bool, ICollection<T>.Add returns void), we must pick one.
			// We prefer the non-void version as it provides more functionality.
			var methodsToRender = new Dictionary<string, FlatMethodModel>();

			foreach (var method in unit.Methods)
			{
				// Skip generic methods - they use .Of<T>() pattern only
				if (method.IsGenericMethod)
					continue;

				// Skip delegation targets (these are synthetic methods)
				if (method.DelegationTarget != null)
					continue;

				// Key by method name + parameter types ONLY (excluding return type)
				// C# does not allow overloading by return type, so we must pick one when
				// multiple interfaces have same method name/params but different returns
				var signatureKey = GetParameterOnlySignatureKey(method);

				if (methodsToRender.TryGetValue(signatureKey, out var existing))
				{
					// Conflict: same method signature from different interfaces
					// Prefer non-void return type (more informative for user)
					if (existing.IsVoid && !method.IsVoid)
					{
						methodsToRender[signatureKey] = method;
					}
					// Otherwise keep the first one (or the non-void one already stored)
				}
				else
				{
					methodsToRender[signatureKey] = method;
				}
			}

			// Render the selected methods
			foreach (var method in methodsToRender.Values)
			{
				RenderBaseClassMethod(w, method);
			}

			// Generate virtual protected properties for each interface property
			// When multiple interfaces have the same property name but different accessors
			// (e.g., IReadOnly.Name has getter only, IMutable.Name has get/set), we must pick one.
			// We prefer the version with MORE accessors (get/set > get-only or set-only).
			var propertiesToRender = new Dictionary<string, FlatPropertyModel>();

			foreach (var property in unit.Properties)
			{
				// Skip delegation targets (these are synthetic properties)
				if (property.DelegationTarget != null)
					continue;

				// Key by property name ONLY
				// C# does not allow overloading properties by return type or accessors
				var key = property.MemberName;

				if (propertiesToRender.TryGetValue(key, out var existing))
				{
					// Conflict: same property name from different interfaces
					// Prefer the version with MORE accessors
					var existingAccessorCount = (existing.HasGetter ? 1 : 0) + (existing.HasSetter ? 1 : 0);
					var newAccessorCount = (property.HasGetter ? 1 : 0) + (property.HasSetter ? 1 : 0);

					if (newAccessorCount > existingAccessorCount)
					{
						propertiesToRender[key] = property;
					}
					// If same accessor count, keep first (stable ordering)
				}
				else
				{
					propertiesToRender[key] = property;
				}
			}

			// Render the selected properties
			foreach (var property in propertiesToRender.Values)
			{
				RenderBaseClassProperty(w, property);
			}
		}

		// Close containing type wrappers for nested classes
		for (int i = 0; i < unit.ContainingTypes.Count; i++)
		{
			w.Line("}");
		}

		return w.ToString();
	}

	/// <summary>
	/// Gets a signature key for a method that only includes parameter types, not return type.
	/// Used for base class deduplication where C# doesn't allow overloading by return type.
	/// </summary>
	private static string GetParameterOnlySignatureKey(FlatMethodModel method)
	{
		if (method.Parameters.Count == 0)
			return $"{method.MethodName}_NoParams";

		var paramTypes = method.Parameters
			.Select(p => p.Type.Replace("global::", "").Replace(" ", ""))
			.ToArray();
		return $"{method.MethodName}_{string.Join("_", paramTypes)}";
	}

	/// <summary>
	/// Renders a single virtual protected method in the base class.
	/// Method name is suffixed with '_' to distinguish from interface method.
	/// Returns default! to allow compilation without override.
	/// </summary>
	private static void RenderBaseClassMethod(CodeWriter w, FlatMethodModel method)
	{
		var methodName = $"{method.MethodName}_";
		var returnType = method.IsVoid ? "void" : method.ReturnType;

		// Check if method has out parameters that need to be assigned
		var outParams = method.Parameters.Where(p => p.RefKind == Microsoft.CodeAnalysis.RefKind.Out).ToList();
		var hasOutParams = outParams.Count > 0;

		w.Line($"/// <summary>Override to provide default implementation for {method.DeclaringInterface}.{method.MethodName}.</summary>");

		if (hasOutParams)
		{
			// Methods with out parameters need a block body to assign all out params
			w.Line($"protected virtual {returnType} {methodName}({method.ParameterDeclarations})");
			using (w.Braces())
			{
				// Assign all out parameters to default
				foreach (var outParam in outParams)
				{
					w.Line($"{outParam.EscapedName} = default!;");
				}

				// Return default if non-void
				if (!method.IsVoid)
				{
					w.Line("return default!;");
				}
			}
		}
		else if (method.IsVoid)
		{
			w.Line($"protected virtual {returnType} {methodName}({method.ParameterDeclarations}) {{ }}");
		}
		else
		{
			w.Line($"protected virtual {returnType} {methodName}({method.ParameterDeclarations}) => default!;");
		}
		w.Line();
	}

	/// <summary>
	/// Renders a single virtual protected property in the base class.
	/// Property name is suffixed with '_' to distinguish from interface property.
	/// Returns default! to allow compilation without override.
	/// </summary>
	private static void RenderBaseClassProperty(CodeWriter w, FlatPropertyModel property)
	{
		var propertyName = $"{property.MemberName}_";
		var returnType = property.ReturnType;

		w.Line($"/// <summary>Override to provide default implementation for {property.DeclaringInterface}.{property.MemberName}.</summary>");

		if (property.HasGetter && property.HasSetter)
		{
			// Get/set property - full property syntax
			w.Line($"protected virtual {returnType} {propertyName} {{ get => default!; set {{ }} }}");
		}
		else if (property.HasGetter)
		{
			// Get-only property - expression-bodied
			w.Line($"protected virtual {returnType} {propertyName} => default!;");
		}
		else if (property.HasSetter)
		{
			// Set-only property - block syntax
			w.Line($"protected virtual {returnType} {propertyName} {{ set {{ }} }}");
		}
		w.Line();
	}

	#region Indexer Access Helpers

	/// <summary>
	/// Builds a map from indexer InterceptorName to the property access expression.
	/// For single-indexer groups: "Indexer"
	/// For multi-indexer groups: "Indexer.OfInt32", "Indexer.OfString", etc.
	/// </summary>
	private static Dictionary<string, string> BuildIndexerAccessMap(EquatableArray<FlatIndexerGroup> groups)
	{
		var map = new Dictionary<string, string>();

		foreach (var group in groups)
		{
			if (group.Indexers.Count == 1)
			{
				// Single indexer - direct access
				var indexer = group.Indexers.GetArray()![0];
				map[indexer.InterceptorName] = group.BaseName;
			}
			else
			{
				// Multiple indexers - container with OfXxx pattern
				foreach (var indexer in group.Indexers)
				{
					map[indexer.InterceptorName] = $"{group.BaseName}.Of{indexer.KeyTypeFriendlyName}";
				}
			}
		}

		return map;
	}

	#endregion

	#region Type Parameter Formatting

	private static string FormatTypeParameters(EquatableArray<TypeParameterModel> typeParameters)
	{
		if (typeParameters.Count == 0)
			return "";

		var names = string.Join(", ", typeParameters.Select(tp => tp.Name));
		return $"<{names}>";
	}

	private static string FormatConstraints(EquatableArray<TypeParameterModel> typeParameters)
	{
		if (typeParameters.Count == 0)
			return "";

		var clauses = typeParameters
			.Where(tp => !string.IsNullOrEmpty(tp.Constraints))
			.Select(tp => $" where {tp.Name} : {tp.Constraints}");

		return string.Join("", clauses);
	}

	#endregion

	#region Generic Method Interfaces

	private static void RenderGenericMethodInterfaces(CodeWriter w)
	{
		w.Line("/// <summary>Interface for tracking calls to generic methods.</summary>");
		using (w.Block("private interface IGenericMethodCallTracker"))
		{
			w.Line("int CallCount { get; }");
		}
		w.Line();

		w.Line("/// <summary>Interface for resetting state.</summary>");
		using (w.Block("private interface IResettable"))
		{
			w.Line("void Reset();");
		}
		w.Line();
	}

	#endregion

	#region Property Interceptor Class

	private static void RenderPropertyInterceptorClass(CodeWriter w, FlatPropertyModel prop, string className)
	{
		w.Line($"/// <summary>Tracks and configures behavior for {prop.MemberName}.</summary>");
		using (w.Block($"public sealed class {prop.InterceptorClassName}"))
		{
			if (prop.IsInitOnly)
			{
				RenderInitPropertyInterceptorContent(w, prop);
			}
			else
			{
				RenderRegularPropertyInterceptorContent(w, prop, className);
			}
		}
		w.Line();
	}

	private static void RenderInitPropertyInterceptorContent(CodeWriter w, FlatPropertyModel prop)
	{
		// Verifiable state
		w.Line("private bool _isVerifiable;");
		w.Line("private global::KnockOff.Called? _verifiableTimes;");
		w.Line("private bool _valueSet;");
		w.Line();

		w.Line("private " + prop.ReturnType + " _value = default!;");
		w.Line($"/// <summary>The configured value for {prop.MemberName}. Setting this marks the property as configured.</summary>");
		w.Line($"public {prop.ReturnType} Value");
		using (w.Braces())
		{
			w.Line("get => _value;");
			w.Line("set { _value = value; _valueSet = true; }");
		}
		w.Line();

		w.Line("private int _getCount;");
		w.Line("private int _setCount;");
		w.Line();

		w.Line("/// <summary>The value from the most recent setter call.</summary>");
		w.Line($"public {prop.NullableReturnType} LastSetValue {{ get; private set; }}");
		w.Line();

		w.Line("/// <summary>Records a getter access.</summary>");
		w.Line("public void RecordGet() => _getCount++;");
		w.Line();

		w.Line("/// <summary>Records a setter access.</summary>");
		w.Line($"public void RecordSet({prop.NullableReturnType} value) {{ _setCount++; LastSetValue = value; }}");
		w.Line();

		w.Line("/// <summary>Resets tracking state (counts, LastSetValue) but preserves configuration (Value) and verifiable marking.</summary>");
		w.Line("public void Reset() { _getCount = 0; _setCount = 0; LastSetValue = default; }");
		w.Line();

		// Verifiable methods (fluent)
		w.Line($"/// <summary>Marks this property for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
		w.Line($"public {prop.InterceptorClassName} Verifiable() {{ _isVerifiable = true; _verifiableTimes = null; return this; }}");
		w.Line();
		w.Line($"/// <summary>Marks this property for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
		w.Line($"public {prop.InterceptorClassName} Verifiable(global::KnockOff.Called times) {{ _isVerifiable = true; _verifiableTimes = times; return this; }}");
		w.Line();

		// Verify methods - throw on failure
		w.Line("/// <summary>Verifies the property was accessed at least once. Throws VerificationException if not.</summary>");
		w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
		w.Line();

		w.Line("/// <summary>Verifies total access count satisfies the Called constraint. Throws VerificationException if not.</summary>");
		w.Line("public void Verify(global::KnockOff.Called times)");
		using (w.Braces())
		{
			w.Line("var totalCount = _getCount + _setCount;");
			w.Line("if (!times.Validate(totalCount))");
			w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.MemberName}\", times, totalCount));");
		}
		w.Line();

		// VerifyGet methods
		w.Line("/// <summary>Verifies the getter was accessed at least once. Throws VerificationException if not.</summary>");
		w.Line("public void VerifyGet() => VerifyGet(global::KnockOff.Called.AtLeastOnce);");
		w.Line();

		w.Line("/// <summary>Verifies getter access count satisfies the Called constraint. Throws VerificationException if not.</summary>");
		w.Line("public void VerifyGet(global::KnockOff.Called times)");
		using (w.Braces())
		{
			w.Line("if (!times.Validate(_getCount))");
			w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.MemberName} (get)\", times, _getCount));");
		}
		w.Line();

		// VerifySet methods
		w.Line("/// <summary>Verifies the setter was accessed at least once. Throws VerificationException if not.</summary>");
		w.Line("public void VerifySet() => VerifySet(global::KnockOff.Called.AtLeastOnce);");
		w.Line();

		w.Line("/// <summary>Verifies setter access count satisfies the Called constraint. Throws VerificationException if not.</summary>");
		w.Line("public void VerifySet(global::KnockOff.Called times)");
		using (w.Braces())
		{
			w.Line("if (!times.Validate(_setCount))");
			w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.MemberName} (set)\", times, _setCount));");
		}
		w.Line();

		// Internal verification support for stub-level Verify/VerifyAll
		w.Line("/// <summary>Whether this property was marked with Verifiable().</summary>");
		w.Line("internal bool IsVerifiable => _isVerifiable;");
		w.Line();

		w.Line("/// <summary>Whether this property has been configured (Value set).</summary>");
		w.Line("internal bool IsConfigured => _valueSet;");
		w.Line();

		w.Line("/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
		w.Line($"internal global::KnockOff.VerificationFailure? CheckVerification()");
		using (w.Braces())
		{
			w.Line("if (!_isVerifiable) return null;");
			w.Line("var times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
			w.Line("var totalCount = _getCount + _setCount;");
			w.Line($"return times.Validate(totalCount) ? null : new global::KnockOff.VerificationFailure(\"{prop.MemberName}\", times, totalCount);");
		}
		w.Line();

		w.Line("/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
		w.Line($"internal global::KnockOff.VerificationFailure? CheckVerificationAll()");
		using (w.Braces())
		{
			w.Line("if (!IsConfigured) return null;");
			w.Line("var totalCount = _getCount + _setCount;");
			w.Line($"return totalCount >= 1 ? null : new global::KnockOff.VerificationFailure(\"{prop.MemberName}\", global::KnockOff.Called.AtLeastOnce, totalCount);");
		}
	}

	private static void RenderRegularPropertyInterceptorContent(CodeWriter w, FlatPropertyModel prop, string className)
	{
		// Source field for Source(T) feature - uses declaring interface type
		w.Line($"/// <summary>Source object to delegate to when no Get/Set is configured.</summary>");
		w.Line($"internal {prop.DeclaringInterface}? _source;");
		w.Line();

		// Verifiable state
		w.Line("private bool _isVerifiable;");
		w.Line("private global::KnockOff.Called? _verifiableTimes;");
		w.Line("private bool _valueSet;");
		w.Line();

		if (prop.HasGetter)
		{
			w.Line("private int _getCount;");
			w.Line();

			w.Line("/// <summary>Callback invoked when the getter is accessed. If set, its return value is used.</summary>");
			w.Line($"public global::System.Func<{prop.ReturnType}>? Get {{ get; set; }}");
			w.Line();
		}

		if (prop.HasSetter)
		{
			w.Line("private int _setCount;");
			w.Line();

			w.Line("/// <summary>The value from the most recent setter call.</summary>");
			w.Line($"public {prop.NullableReturnType} LastSetValue {{ get; private set; }}");
			w.Line();

			w.Line("/// <summary>Callback invoked when the setter is accessed.</summary>");
			w.Line($"public global::System.Action<{prop.ReturnType}>? Set {{ get; set; }}");
			w.Line();
		}

		// Value property for backing storage - setting Value marks the property as configured
		w.Line("private " + prop.ReturnType + " _value" + GetDefaultValueSuffix(prop.DefaultExpression));
		w.Line("/// <summary>Value returned by getter when Get is not set. Setting this marks the property as configured.</summary>");
		w.Line($"public {prop.ReturnType} Value");
		using (w.Braces())
		{
			w.Line("get => _value;");
			w.Line("set { _value = value; _valueSet = true; }");
		}
		w.Line();

		if (prop.HasGetter)
		{
			w.Line("/// <summary>Records a getter access.</summary>");
			w.Line("public void RecordGet() => _getCount++;");
			w.Line();
		}

		if (prop.HasSetter)
		{
			w.Line("/// <summary>Records a setter access.</summary>");
			w.Line($"public void RecordSet({prop.NullableReturnType} value) {{ _setCount++; LastSetValue = value; }}");
			w.Line();
		}

		// Reset method - clears tracking state but preserves configuration (Get/Set/Value) and verifiable marking
		w.Line("/// <summary>Resets tracking state (counts, LastSetValue) but preserves configuration (Get, Set, Value) and verifiable marking.</summary>");
		var resetParts = new System.Collections.Generic.List<string>();
		if (prop.HasGetter) resetParts.Add("_getCount = 0;");
		if (prop.HasSetter) resetParts.Add("_setCount = 0; LastSetValue = default;");
		resetParts.Add("_source = null;");
		w.Line($"public void Reset() {{ {string.Join(" ", resetParts)} }}");
		w.Line();

		// Verifiable methods (fluent)
		w.Line($"/// <summary>Marks this property for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
		w.Line($"public {prop.InterceptorClassName} Verifiable() {{ _isVerifiable = true; _verifiableTimes = null; return this; }}");
		w.Line();
		w.Line($"/// <summary>Marks this property for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
		w.Line($"public {prop.InterceptorClassName} Verifiable(global::KnockOff.Called times) {{ _isVerifiable = true; _verifiableTimes = times; return this; }}");
		w.Line();

		// Build total count expression based on available accessors
		var totalCountExpr = prop.HasGetter && prop.HasSetter
			? "_getCount + _setCount"
			: (prop.HasGetter ? "_getCount" : "_setCount");

		// Verify methods - throw on failure
		w.Line("/// <summary>Verifies the property was accessed at least once. Throws VerificationException if not.</summary>");
		w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
		w.Line();

		w.Line("/// <summary>Verifies total access count satisfies the Called constraint. Throws VerificationException if not.</summary>");
		w.Line("public void Verify(global::KnockOff.Called times)");
		using (w.Braces())
		{
			w.Line($"var totalCount = {totalCountExpr};");
			w.Line("if (!times.Validate(totalCount))");
			w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.MemberName}\", times, totalCount));");
		}
		w.Line();

		// VerifyGet methods
		if (prop.HasGetter)
		{
			w.Line("/// <summary>Verifies the getter was accessed at least once. Throws VerificationException if not.</summary>");
			w.Line("public void VerifyGet() => VerifyGet(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies getter access count satisfies the Called constraint. Throws VerificationException if not.</summary>");
			w.Line("public void VerifyGet(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(_getCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.MemberName} (get)\", times, _getCount));");
			}
			w.Line();
		}

		// VerifySet methods
		if (prop.HasSetter)
		{
			w.Line("/// <summary>Verifies the setter was accessed at least once. Throws VerificationException if not.</summary>");
			w.Line("public void VerifySet() => VerifySet(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies setter access count satisfies the Called constraint. Throws VerificationException if not.</summary>");
			w.Line("public void VerifySet(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(_setCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.MemberName} (set)\", times, _setCount));");
			}
			w.Line();
		}

		// Internal verification support for stub-level Verify/VerifyAll
		w.Line("/// <summary>Whether this property was marked with Verifiable().</summary>");
		w.Line("internal bool IsVerifiable => _isVerifiable;");
		w.Line();

		// IsConfigured - Value set OR Get/Set callback registered
		var isConfiguredParts = new System.Collections.Generic.List<string> { "_valueSet" };
		if (prop.HasGetter) isConfiguredParts.Add("Get != null");
		if (prop.HasSetter) isConfiguredParts.Add("Set != null");
		w.Line("/// <summary>Whether this property has been configured (Value set or callbacks registered).</summary>");
		w.Line($"internal bool IsConfigured => {string.Join(" || ", isConfiguredParts)};");
		w.Line();

		w.Line("/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
		w.Line($"internal global::KnockOff.VerificationFailure? CheckVerification()");
		using (w.Braces())
		{
			w.Line("if (!_isVerifiable) return null;");
			w.Line("var times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
			w.Line($"var totalCount = {totalCountExpr};");
			w.Line($"return times.Validate(totalCount) ? null : new global::KnockOff.VerificationFailure(\"{prop.MemberName}\", times, totalCount);");
		}
		w.Line();

		w.Line("/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
		w.Line($"internal global::KnockOff.VerificationFailure? CheckVerificationAll()");
		using (w.Braces())
		{
			w.Line("if (!IsConfigured) return null;");
			w.Line($"var totalCount = {totalCountExpr};");
			w.Line($"return totalCount >= 1 ? null : new global::KnockOff.VerificationFailure(\"{prop.MemberName}\", global::KnockOff.Called.AtLeastOnce, totalCount);");
		}
	}

	private static string GetDefaultValueSuffix(string defaultExpression)
	{
		// The DefaultExpression from the model contains the complete expression (e.g., "default!", "new List<int>()")
		// We need to convert it to an initializer format with " = " prefix and ";" suffix
		if (string.IsNullOrEmpty(defaultExpression) || defaultExpression == "default!")
			return " = default!;";

		// For NewInstance strategy, the expression will be like "new SomeType()"
		return $" = {defaultExpression};";
	}

	#endregion

	#region Indexer Container Class (for OfXxx pattern)

	private static void RenderIndexerContainerClass(CodeWriter w, FlatIndexerGroup group)
	{
		// Deduplicate by KeyTypeFriendlyName - same key type shares the same interceptor in container
		var uniqueByKeyType = group.Indexers
			.GroupBy(i => i.KeyTypeFriendlyName)
			.Select(g => g.First())
			.ToList();

		w.Line($"/// <summary>Container for indexer interceptors with OfXxx access pattern.</summary>");
		using (w.Block($"public sealed class {group.ContainerClassName}"))
		{
			// Of{KeyType} properties (container owns its interceptors)
			foreach (var indexer in uniqueByKeyType)
			{
				w.Line($"/// <summary>Gets the interceptor for indexer with {indexer.KeyTypeFriendlyName} key type.</summary>");
				w.Line($"public {indexer.InterceptorClassName} Of{indexer.KeyTypeFriendlyName} {{ get; }} = new();");
				w.Line();
			}

			// Reset method (resets all)
			w.Line("/// <summary>Resets all indexer interceptors.</summary>");
			using (w.Block("public void Reset()"))
			{
				foreach (var indexer in uniqueByKeyType)
				{
					w.Line($"Of{indexer.KeyTypeFriendlyName}.Reset();");
				}
			}
			w.Line();

			// Internal verification support for stub-level Verify/VerifyAll
			// Container aggregates verification from all indexer interceptors
			w.Line("internal bool IsVerifiable => false; // Container is not individually verifiable");

			// Check if any contained interceptor is configured
			var isConfiguredParts = uniqueByKeyType.Select(i => $"Of{i.KeyTypeFriendlyName}.IsConfigured").ToList();
			w.Line($"internal bool IsConfigured => {string.Join(" || ", isConfiguredParts)};");
			w.Line();

			w.Line("/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
			w.Line("internal global::KnockOff.VerificationFailure? CheckVerification()");
			using (w.Braces())
			{
				// Container returns first failure from any contained interceptor
				foreach (var indexer in uniqueByKeyType)
				{
					w.Line($"if (Of{indexer.KeyTypeFriendlyName}.CheckVerification() is {{ }} failure{indexer.KeyTypeFriendlyName}) return failure{indexer.KeyTypeFriendlyName};");
				}
				w.Line("return null;");
			}
			w.Line();

			w.Line("/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
			w.Line("internal global::KnockOff.VerificationFailure? CheckVerificationAll()");
			using (w.Braces())
			{
				// Container returns first failure from any contained interceptor
				foreach (var indexer in uniqueByKeyType)
				{
					w.Line($"if (Of{indexer.KeyTypeFriendlyName}.CheckVerificationAll() is {{ }} failure{indexer.KeyTypeFriendlyName}) return failure{indexer.KeyTypeFriendlyName};");
				}
				w.Line("return null;");
			}
		}
		w.Line();
	}

	#endregion

	#region Indexer Interceptor Class

	private static void RenderIndexerInterceptorClass(CodeWriter w, FlatIndexerModel indexer, string className)
	{
		w.Line($"/// <summary>Tracks and configures behavior for indexer.</summary>");
		using (w.Block($"public sealed class {indexer.InterceptorClassName}"))
		{
			// Source field for Source(T) feature - uses declaring interface type
			w.Line($"/// <summary>Source object to delegate to when no Get/Set is configured.</summary>");
			w.Line($"internal {indexer.DeclaringInterface}? _source;");
			w.Line();

			if (indexer.HasGetter)
			{
				w.Line("private int _getCount;");
				w.Line();

				w.Line("/// <summary>The key from the most recent getter access.</summary>");
				w.Line($"public {indexer.NullableKeyType} LastGetKey {{ get; private set; }}");
				w.Line();

				w.Line("/// <summary>Callback invoked when the getter is accessed.</summary>");
				w.Line($"public global::System.Func<{indexer.KeyType}, {indexer.ReturnType}>? Get {{ get; set; }}");
				w.Line();
			}

			if (indexer.HasSetter)
			{
				w.Line("private int _setCount;");
				w.Line();

				w.Line("/// <summary>The key and value from the most recent setter call.</summary>");
				w.Line($"public ({indexer.NullableKeyType} Key, {indexer.NullableReturnType} Value)? LastSetEntry {{ get; private set; }}");
				w.Line();

				w.Line("/// <summary>Callback invoked when the setter is accessed.</summary>");
				w.Line($"public global::System.Action<{indexer.KeyType}, {indexer.ReturnType}>? Set {{ get; set; }}");
				w.Line();
			}

			if (indexer.HasGetter)
			{
				w.Line("/// <summary>Records a getter access.</summary>");
				w.Line($"public void RecordGet({indexer.NullableKeyType} {indexer.KeyParamName}) {{ _getCount++; LastGetKey = {indexer.KeyParamName}; }}");
				w.Line();
			}

			if (indexer.HasSetter)
			{
				w.Line("/// <summary>Records a setter access.</summary>");
				w.Line($"public void RecordSet({indexer.NullableKeyType} {indexer.KeyParamName}, {indexer.NullableReturnType} value) {{ _setCount++; LastSetEntry = ({indexer.KeyParamName}, value); }}");
				w.Line();
			}

			// Backing dictionary
			w.Line($"/// <summary>Backing storage for this indexer.</summary>");
			w.Line($"public global::System.Collections.Generic.Dictionary<{indexer.KeyType}, {indexer.ReturnType}> Backing {{ get; }} = new();");
			w.Line();

			// Reset method - clears tracking state but preserves configuration (Get/Set/Backing) and verifiable marking
			w.Line("/// <summary>Resets tracking state (counts, LastGetKey, LastSetEntry) but preserves configuration (Get, Set, Backing) and verifiable marking.</summary>");
			var resetParts = new System.Collections.Generic.List<string>();
			if (indexer.HasGetter) resetParts.Add("_getCount = 0; LastGetKey = default;");
			if (indexer.HasSetter) resetParts.Add("_setCount = 0; LastSetEntry = null;");
			resetParts.Add("_source = null;");
			// Note: Backing dictionary is intentionally NOT cleared - pre-populated data is preserved
			w.Line($"public void Reset() {{ {string.Join(" ", resetParts)} }}");
			w.Line();

			// Verification API for indexers
			w.Line("private bool _isVerifiable;");
			w.Line("private global::KnockOff.Called? _verifiableTimes;");
			w.Line();

			if (indexer.HasGetter)
			{
				w.Line("/// <summary>Verifies the indexer getter was accessed at least once.</summary>");
				w.Line("public void VerifyGet() => VerifyGet(global::KnockOff.Called.AtLeastOnce);");
				w.Line();

				w.Line("/// <summary>Verifies the indexer getter access count matches the Called constraint.</summary>");
				w.Line("public void VerifyGet(global::KnockOff.Called times)");
				using (w.Braces())
				{
					w.Line("if (!times.Validate(_getCount))");
					w.Line("\tthrow new global::KnockOff.VerificationException($\"Indexer getter verification failed: expected {times}, but was called {_getCount} time(s).\");");
				}
				w.Line();
			}

			if (indexer.HasSetter)
			{
				w.Line("/// <summary>Verifies the indexer setter was accessed at least once.</summary>");
				w.Line("public void VerifySet() => VerifySet(global::KnockOff.Called.AtLeastOnce);");
				w.Line();

				w.Line("/// <summary>Verifies the indexer setter access count matches the Called constraint.</summary>");
				w.Line("public void VerifySet(global::KnockOff.Called times)");
				using (w.Braces())
				{
					w.Line("if (!times.Validate(_setCount))");
					w.Line("\tthrow new global::KnockOff.VerificationException($\"Indexer setter verification failed: expected {times}, but was called {_setCount} time(s).\");");
				}
				w.Line();
			}

			w.Line("/// <summary>Verifies the indexer was accessed at least once.</summary>");
			w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			// Build total count expression based on what accessors exist
			var indexerTotalCountExpr = indexer.HasGetter && indexer.HasSetter
				? "_getCount + _setCount"
				: (indexer.HasGetter ? "_getCount" : "_setCount");

			w.Line("/// <summary>Verifies the total indexer access count matches the Called constraint.</summary>");
			w.Line("public void Verify(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line($"var totalCount = {indexerTotalCountExpr};");
				w.Line("if (!times.Validate(totalCount))");
				w.Line("\tthrow new global::KnockOff.VerificationException($\"Indexer verification failed: expected {times}, but was called {totalCount} time(s).\");");
			}
			w.Line();

			w.Line("/// <summary>Marks this indexer for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
			w.Line($"public {indexer.InterceptorClassName} Verifiable()");
			using (w.Braces())
			{
				w.Line("_isVerifiable = true;");
				w.Line("_verifiableTimes = global::KnockOff.Called.AtLeastOnce;");
				w.Line("return this;");
			}
			w.Line();

			w.Line("/// <summary>Marks this indexer for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
			w.Line($"public {indexer.InterceptorClassName} Verifiable(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("_isVerifiable = true;");
				w.Line("_verifiableTimes = times;");
				w.Line("return this;");
			}
			w.Line();

			// Internal verification methods for stub-level Verify()/VerifyAll()
			// Determine if configured based on available callbacks
			var isConfiguredExpr = indexer.HasGetter && indexer.HasSetter
				? "Get != null || Set != null || Backing.Count > 0"
				: (indexer.HasGetter ? "Get != null || Backing.Count > 0" : "Set != null || Backing.Count > 0");

			w.Line($"internal bool IsVerifiable => _isVerifiable;");
			w.Line($"internal bool IsConfigured => {isConfiguredExpr};");
			w.Line();

			w.Line("/// <summary>Checks verification for Stub.Verify() - only verifiable items.</summary>");
			w.Line("internal global::KnockOff.VerificationFailure? CheckVerification()");
			using (w.Braces())
			{
				w.Line("if (!_isVerifiable) return null;");
				w.Line("var times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
				w.Line($"var totalCount = {indexerTotalCountExpr};");
				w.Line("if (!times.Validate(totalCount))");
				w.Line("\treturn new global::KnockOff.VerificationFailure(\"Indexer\", times, totalCount);");
				w.Line("return null;");
			}
			w.Line();

			w.Line("/// <summary>Checks verification for Stub.VerifyAll() - all configured items.</summary>");
			w.Line("internal global::KnockOff.VerificationFailure? CheckVerificationAll()");
			using (w.Braces())
			{
				w.Line("if (!IsConfigured && !_isVerifiable) return null;");
				w.Line("var times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
				w.Line($"var totalCount = {indexerTotalCountExpr};");
				w.Line("if (!times.Validate(totalCount))");
				w.Line("\treturn new global::KnockOff.VerificationFailure(\"Indexer\", times, totalCount);");
				w.Line("return null;");
			}
		}
		w.Line();
	}

	#endregion

	#region Signature Suffix Helpers

	private static string GetSignatureSuffix(FlatMethodModel method)
	{
		var returnSuffix = UnifiedInterceptorBuilder.GetTypeSuffix(method.ReturnType);
		if (method.Parameters.Count == 0)
			return $"NoParams_{returnSuffix}";
		return string.Join("_", method.Parameters.Select(p => UnifiedInterceptorBuilder.GetTypeSuffix(p.Type))) + $"_{returnSuffix}";
	}

	#endregion

	#region Generic Method Handler

	private static void RenderGenericMethodHandler(CodeWriter w, FlatGenericMethodHandlerModel handler, string className)
	{
		w.Line($"/// <summary>Interceptor for {handler.MethodName} (generic method with Of&lt;T&gt;() access).</summary>");
		using (w.Block($"public sealed class {handler.InterceptorClassName}"))
		{
			// Dictionary for typed handlers
			w.Line($"private readonly global::System.Collections.Generic.Dictionary<{handler.KeyType}, object> _typedHandlers = new();");
			w.Line();

			// Of<T>() method
			w.Line($"/// <summary>Gets the typed handler for the specified type argument(s).</summary>");
			w.Line($"public {handler.TypedHandlerClassName}<{handler.TypeParameterNames}> Of<{handler.TypeParameterNames}>(){handler.ConstraintClauses}");
			using (w.Braces())
			{
				w.Line($"var key = {handler.KeyConstruction};");
				w.Line($"if (!_typedHandlers.TryGetValue(key, out var handler))");
				using (w.Braces())
				{
					w.Line($"handler = new {handler.TypedHandlerClassName}<{handler.TypeParameterNames}>();");
					w.Line("_typedHandlers[key] = handler;");
				}
				w.Line($"return ({handler.TypedHandlerClassName}<{handler.TypeParameterNames}>)handler;");
			}
			w.Line();

			// Aggregate tracking (private - use Verify for public API)
			w.Line("private int TotalCallCount => _typedHandlers.Values.Sum(h => ((IGenericMethodCallTracker)h).CallCount);");
			w.Line();
			w.Line($"/// <summary>All type argument(s) that were used in calls.</summary>");
			w.Line($"public global::System.Collections.Generic.IReadOnlyList<{handler.KeyType}> CalledTypeArguments => _typedHandlers.Where(kvp => ((IGenericMethodCallTracker)kvp.Value).CallCount > 0).Select(kvp => kvp.Key).ToList();");
			w.Line();

			// Reset method
			w.Line("/// <summary>Resets all typed handlers.</summary>");
			using (w.Block("public void Reset()"))
			{
				w.Line("foreach (var handler in _typedHandlers.Values)");
				w.Line("\t((IResettable)handler).Reset();");
				w.Line("_typedHandlers.Clear();");
			}
			w.Line();

			// Verify methods
			w.Line("/// <summary>Verifies method was called at least once with any type argument. Throws VerificationException if not.</summary>");
			w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies total call count satisfies the Called constraint. Throws VerificationException if not.</summary>");
			w.Line("public void Verify(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(TotalCallCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{handler.MethodName}\", times, TotalCallCount));");
			}
			w.Line();

			// Nested Typed Handler Class
			RenderTypedHandlerClass(w, handler, className);
		}
		w.Line();
	}

	private static void RenderTypedHandlerClass(CodeWriter w, FlatGenericMethodHandlerModel handler, string className)
	{
		w.Line($"/// <summary>Typed handler for {handler.MethodName} with specific type arguments.</summary>");
		w.Line($"public sealed class {handler.TypedHandlerClassName}<{handler.TypeParameterNames}> : IGenericMethodCallTracker, IResettable, global::KnockOff.IMethodTracking{handler.ConstraintClauses}");
		using (w.Braces())
		{
			// Delegate
			w.Line($"/// <summary>Delegate for {handler.MethodName}.</summary>");
			w.Line(handler.DelegateSignature);
			w.Line();

			// Private callback field
			w.Line($"private {handler.MethodName}Delegate? _call;");
			w.Line();

			// CallCount - private field with explicit interface implementation for aggregation
			w.Line("internal int _callCount;");
			w.Line("int IGenericMethodCallTracker.CallCount => _callCount;");
			w.Line();

			// LastArg/LastArgs
			if (handler.NonGenericParams.Count == 1)
			{
				var param = handler.NonGenericParams.GetArray()![0];
				w.Line($"/// <summary>The '{param.Name}' argument from the most recent call.</summary>");
				w.Line($"public {param.NullableType} LastArg {{ get; private set; }}");
				w.Line();
			}
			else if (handler.NonGenericParams.Count > 1)
			{
				w.Line("/// <summary>The arguments from the most recent call.</summary>");
				w.Line($"public {handler.LastCallType}? LastArgs {{ get; private set; }}");
				w.Line();
			}

			// Return/Call method (returns IMethodTracking for consistency with regular method interceptors)
			var typedHandlerEntryPoint = handler.IsVoid ? "Call" : "Return";
			w.Line("/// <summary>Sets the callback invoked when this method is called. Returns this handler for tracking.</summary>");
			w.Line($"public global::KnockOff.IMethodTracking {typedHandlerEntryPoint}({handler.MethodName}Delegate callback) {{ _call = callback; return this; }}");
			w.Line();

			// Callback property for internal use by invocation logic
			w.Line("/// <summary>Gets the configured callback (internal use).</summary>");
			w.Line($"internal {handler.MethodName}Delegate? Callback => _call;");
			w.Line();

			// RecordCall
			w.Line("/// <summary>Records a method call.</summary>");
			if (handler.NonGenericParams.Count == 0)
			{
				w.Line("public void RecordCall() => _callCount++;");
			}
			else if (handler.NonGenericParams.Count == 1)
			{
				var param = handler.NonGenericParams.GetArray()![0];
				w.Line($"public void RecordCall({param.NullableType} {param.EscapedName}) {{ _callCount++; LastArg = {param.EscapedName}; }}");
			}
			else
			{
				var paramList = string.Join(", ", handler.NonGenericParams.Select(p => $"{p.NullableType} {p.EscapedName}"));
				var tupleConstruction = string.Join(", ", handler.NonGenericParams.Select(p => p.EscapedName));
				w.Line($"public void RecordCall({paramList}) {{ _callCount++; LastArgs = ({tupleConstruction}); }}");
			}
			w.Line();

			// Reset
			w.Line("/// <summary>Resets all tracking state.</summary>");
			if (handler.NonGenericParams.Count == 0)
			{
				w.Line("public void Reset() { _callCount = 0; _call = null; }");
			}
			else if (handler.NonGenericParams.Count == 1)
			{
				w.Line("public void Reset() { _callCount = 0; LastArg = default; _call = null; }");
			}
			else
			{
				w.Line("public void Reset() { _callCount = 0; LastArgs = default; _call = null; }");
			}
			w.Line();

			// Verify methods - new API throws VerificationException
			w.Line("/// <summary>Verifies call count is at least once. Throws VerificationException if not.</summary>");
			w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies call count satisfies the Called constraint. Throws VerificationException if not.</summary>");
			w.Line("public void Verify(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(_callCount))");
				w.Line("\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"method\", times, _callCount));");
			}
			w.Line();

			// Verifiable methods
			w.Line("/// <summary>Marks for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
			w.Line("public global::KnockOff.IMethodTracking Verifiable() => this;");
			w.Line();

			w.Line("/// <summary>Marks for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
			w.Line("public global::KnockOff.IMethodTracking Verifiable(global::KnockOff.Called times) => this;");
		}
	}

	#endregion

	#region Generic Stub Override Handler Group

	private static void RenderGenericStubOverrideHandlerGroup(CodeWriter w, FlatGenericMethodHandlerGroup group, string className)
	{
		w.Line($"/// <summary>Interceptor for {group.MethodName} (generic stub override with Of&lt;T&gt;() access).</summary>");
		using (w.Block($"public sealed class {group.InterceptorClassName}"))
		{
			// Each type arity gets its own dictionary
			foreach (var arity in group.TypeArityGroups)
			{
				var dictSuffix = arity.TypeParameterCount > 1 ? $"_{arity.TypeParameterCount}" : "";
				w.Line($"private readonly global::System.Collections.Generic.Dictionary<{arity.KeyType}, object> _typedHandlers{dictSuffix} = new();");
			}
			w.Line();

			// Of<T>() method for each type arity
			foreach (var arity in group.TypeArityGroups)
			{
				var dictSuffix = arity.TypeParameterCount > 1 ? $"_{arity.TypeParameterCount}" : "";
				w.Line($"/// <summary>Gets the typed handler for the specified type argument(s).</summary>");
				w.Line($"public {arity.TypedHandlerClassName}<{arity.TypeParameterNames}> Of<{arity.TypeParameterNames}>(){arity.ConstraintClauses}");
				using (w.Braces())
				{
					w.Line($"var key = {arity.KeyConstruction};");
					w.Line($"if (!_typedHandlers{dictSuffix}.TryGetValue(key, out var handler))");
					using (w.Braces())
					{
						w.Line($"handler = new {arity.TypedHandlerClassName}<{arity.TypeParameterNames}>();");
						w.Line($"_typedHandlers{dictSuffix}[key] = handler;");
					}
					w.Line($"return ({arity.TypedHandlerClassName}<{arity.TypeParameterNames}>)handler;");
				}
				w.Line();
			}

			// Aggregate tracking
			if (group.TypeArityGroups.Count == 1)
			{
				w.Line("private int TotalCallCount => _typedHandlers.Values.Sum(h => ((IGenericMethodCallTracker)h).CallCount);");
			}
			else
			{
				var dictNames = string.Join(".Concat(", group.TypeArityGroups.Select((a, i) =>
					$"_typedHandlers{(a.TypeParameterCount > 1 ? $"_{a.TypeParameterCount}" : "")}.Values"));
				dictNames += string.Join("", Enumerable.Range(0, group.TypeArityGroups.Count - 1).Select(_ => ")"));
				w.Line($"private int TotalCallCount => {dictNames}.Sum(h => ((IGenericMethodCallTracker)h).CallCount);");
			}
			w.Line();

			// CalledTypeArguments - only for single-arity, too complex for mixed
			if (group.TypeArityGroups.Count == 1)
			{
				var arity = group.TypeArityGroups.First();
				w.Line($"/// <summary>All type argument(s) that were used in calls.</summary>");
				w.Line($"public global::System.Collections.Generic.IReadOnlyList<{arity.KeyType}> CalledTypeArguments => _typedHandlers.Where(kvp => ((IGenericMethodCallTracker)kvp.Value).CallCount > 0).Select(kvp => kvp.Key).ToList();");
				w.Line();
			}

			// Reset method
			w.Line("/// <summary>Resets all typed handlers.</summary>");
			using (w.Block("public void Reset()"))
			{
				foreach (var arity in group.TypeArityGroups)
				{
					var dictSuffix = arity.TypeParameterCount > 1 ? $"_{arity.TypeParameterCount}" : "";
					w.Line($"foreach (var handler in _typedHandlers{dictSuffix}.Values)");
					w.Line($"\t((IResettable)handler).Reset();");
					w.Line($"_typedHandlers{dictSuffix}.Clear();");
				}
			}
			w.Line();

			// Verify methods
			w.Line("/// <summary>Verifies method was called at least once with any type argument. Throws VerificationException if not.</summary>");
			w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies total call count satisfies the Called constraint. Throws VerificationException if not.</summary>");
			w.Line("public void Verify(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(TotalCallCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{group.MethodName}\", times, TotalCallCount));");
			}
			w.Line();

			// Nested Typed Handler Classes (one per type arity)
			foreach (var arity in group.TypeArityGroups)
			{
				RenderGenericStubOverrideTypedHandlerClass(w, group.MethodName, arity);
			}
		}
		w.Line();
	}

	private static void RenderGenericStubOverrideTypedHandlerClass(CodeWriter w, string methodName, FlatGenericTypeArityGroup arity)
	{
		w.Line($"/// <summary>Typed handler for {methodName} with specific type arguments.</summary>");
		w.Line($"public sealed class {arity.TypedHandlerClassName}<{arity.TypeParameterNames}> : IGenericMethodCallTracker, IResettable, global::KnockOff.IMethodTracking{arity.ConstraintClauses}");
		using (w.Braces())
		{
			// Delegates (one per signature)
			foreach (var sig in arity.SignatureGroups)
			{
				w.Line($"/// <summary>Delegate for {methodName}{sig.SignatureSuffix}.</summary>");
				w.Line(sig.DelegateSignature);
			}
			w.Line();

			// Private callback fields (one per signature)
			foreach (var sig in arity.SignatureGroups)
			{
				w.Line($"private {sig.DelegateName}? _call{sig.SignatureSuffix};");
			}
			w.Line();

			// CallCount
			w.Line("internal int _callCount;");
			w.Line("int IGenericMethodCallTracker.CallCount => _callCount;");
			w.Line();

			// Per-signature LastArg/LastArgs storage
			foreach (var sig in arity.SignatureGroups)
			{
				var paramArray = sig.AllParameters.GetArray() ?? Array.Empty<ParameterModel>();
				if (paramArray.Length == 1)
				{
					w.Line($"/// <summary>The argument from the most recent call to {methodName}{sig.SignatureSuffix}.</summary>");
					w.Line($"public {sig.LastCallType} LastArg{sig.SignatureSuffix} {{ get; private set; }}");
				}
				else if (paramArray.Length > 1)
				{
					w.Line($"/// <summary>The arguments from the most recent call to {methodName}{sig.SignatureSuffix}.</summary>");
					w.Line($"public {sig.LastCallType}? LastArgs{sig.SignatureSuffix} {{ get; private set; }}");
				}
			}
			if (arity.SignatureGroups.Count > 0)
				w.Line();

			// Return/Call methods (one per signature)
			foreach (var sig in arity.SignatureGroups)
			{
				var sigEntryPoint = sig.IsVoid ? "Call" : "Return";
				w.Line($"/// <summary>Sets the callback invoked when this signature is called. Returns this handler for tracking.</summary>");
				w.Line($"public global::KnockOff.IMethodTracking {sigEntryPoint}{sig.SignatureSuffix}({sig.DelegateName} callback) {{ _call{sig.SignatureSuffix} = callback; return this; }}");
			}
			w.Line();

			// Callback properties (one per signature)
			foreach (var sig in arity.SignatureGroups)
			{
				w.Line($"/// <summary>Gets the configured callback for {methodName}{sig.SignatureSuffix} (internal use).</summary>");
				w.Line($"internal {sig.DelegateName}? Callback{sig.SignatureSuffix} => _call{sig.SignatureSuffix};");
			}
			w.Line();

			// RecordCall methods (one per signature)
			foreach (var sig in arity.SignatureGroups)
			{
				var paramArray = sig.AllParameters.GetArray() ?? Array.Empty<ParameterModel>();
				w.Line($"/// <summary>Records a method call for {methodName}{sig.SignatureSuffix}.</summary>");
				if (paramArray.Length == 0)
				{
					w.Line($"internal void RecordCall{sig.SignatureSuffix}() => _callCount++;");
				}
				else if (paramArray.Length == 1)
				{
					var param = paramArray[0];
					w.Line($"internal void RecordCall{sig.SignatureSuffix}({param.NullableType} {param.EscapedName}) {{ _callCount++; LastArg{sig.SignatureSuffix} = {param.EscapedName}; }}");
				}
				else
				{
					var paramList = string.Join(", ", paramArray.Select(p => $"{p.NullableType} {p.EscapedName}"));
					var tupleConstruction = string.Join(", ", paramArray.Select(p => p.EscapedName));
					w.Line($"internal void RecordCall{sig.SignatureSuffix}({paramList}) {{ _callCount++; LastArgs{sig.SignatureSuffix} = ({tupleConstruction}); }}");
				}
			}
			w.Line();

			// Reset
			w.Line("/// <summary>Resets all tracking state.</summary>");
			var resetParts = new List<string> { "_callCount = 0" };
			foreach (var sig in arity.SignatureGroups)
			{
				resetParts.Add($"_call{sig.SignatureSuffix} = null");
				var paramArray = sig.AllParameters.GetArray() ?? Array.Empty<ParameterModel>();
				if (paramArray.Length == 1)
					resetParts.Add($"LastArg{sig.SignatureSuffix} = default");
				else if (paramArray.Length > 1)
					resetParts.Add($"LastArgs{sig.SignatureSuffix} = default");
			}
			w.Line($"public void Reset() {{ {string.Join("; ", resetParts)}; }}");
			w.Line();

			// Verify methods
			w.Line("/// <summary>Verifies call count is at least once. Throws VerificationException if not.</summary>");
			w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies call count satisfies the Called constraint. Throws VerificationException if not.</summary>");
			w.Line("public void Verify(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(_callCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{methodName}\", times, _callCount));");
			}
			w.Line();

			// Verifiable methods
			w.Line("/// <summary>Marks for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
			w.Line("public global::KnockOff.IMethodTracking Verifiable() => this;");
			w.Line();

			w.Line("/// <summary>Marks for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
			w.Line("public global::KnockOff.IMethodTracking Verifiable(global::KnockOff.Called times) => this;");
		}
	}

	#endregion

	#region Event Interceptor Class

	private static void RenderEventInterceptorClass(CodeWriter w, FlatEventModel evt)
	{
		w.Line($"/// <summary>Interceptor for {evt.EventName} event.</summary>");
		using (w.Block($"public sealed class {evt.InterceptorClassName}"))
		{
			// Backing field
			w.Line($"private {evt.DelegateType}? _handler;");
			w.Line();

			// Add/Remove tracking
			w.Line("private int _addCount;");
			w.Line("private int _removeCount;");
			w.Line();

			w.Line("/// <summary>Whether any handlers are subscribed.</summary>");
			w.Line("public bool HasSubscribers => _handler != null;");
			w.Line();

			// RecordAdd/RecordRemove
			w.Line($"/// <summary>Records an event subscription.</summary>");
			w.Line($"public void RecordAdd({evt.DelegateType}? value) {{ _addCount++; _handler = ({evt.DelegateType}?)global::System.Delegate.Combine(_handler, value); }}");
			w.Line();

			w.Line($"/// <summary>Records an event unsubscription.</summary>");
			w.Line($"public void RecordRemove({evt.DelegateType}? value) {{ _removeCount++; _handler = ({evt.DelegateType}?)global::System.Delegate.Remove(_handler, value); }}");
			w.Line();

			// Raise method
			RenderEventRaiseMethod(w, evt);

			// Reset - clears tracking state but preserves verifiable marking
			w.Line("/// <summary>Resets tracking state (counts, handler) but preserves verifiable marking.</summary>");
			w.Line("public void Reset() { _addCount = 0; _removeCount = 0; _handler = null; }");
			w.Line();

			// Verification API for events
			w.Line("private bool _isVerifiable;");
			w.Line("private global::KnockOff.Called? _verifiableTimes;");
			w.Line();

			w.Line("/// <summary>Verifies the event was subscribed to at least once.</summary>");
			w.Line("public void VerifyAdd() => VerifyAdd(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies the event subscription count matches the Called constraint.</summary>");
			w.Line("public void VerifyAdd(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(_addCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' add verification failed: expected {{times}}, but was called {{_addCount}} time(s).\");");
			}
			w.Line();

			w.Line("/// <summary>Verifies the event was unsubscribed at least once.</summary>");
			w.Line("public void VerifyRemove() => VerifyRemove(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies the event unsubscription count matches the Called constraint.</summary>");
			w.Line("public void VerifyRemove(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("if (!times.Validate(_removeCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' remove verification failed: expected {{times}}, but was called {{_removeCount}} time(s).\");");
			}
			w.Line();

			w.Line("/// <summary>Verifies the event was accessed (add or remove) at least once.</summary>");
			w.Line("public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
			w.Line();

			w.Line("/// <summary>Verifies the total event access count matches the Called constraint.</summary>");
			w.Line("public void Verify(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("var totalCount = _addCount + _removeCount;");
				w.Line("if (!times.Validate(totalCount))");
				w.Line($"\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' verification failed: expected {{times}}, but was called {{totalCount}} time(s).\");");
			}
			w.Line();

			w.Line("/// <summary>Marks this event for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
			w.Line($"public {evt.InterceptorClassName} Verifiable()");
			using (w.Braces())
			{
				w.Line("_isVerifiable = true;");
				w.Line("_verifiableTimes = global::KnockOff.Called.AtLeastOnce;");
				w.Line("return this;");
			}
			w.Line();

			w.Line("/// <summary>Marks this event for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
			w.Line($"public {evt.InterceptorClassName} Verifiable(global::KnockOff.Called times)");
			using (w.Braces())
			{
				w.Line("_isVerifiable = true;");
				w.Line("_verifiableTimes = times;");
				w.Line("return this;");
			}
			w.Line();

			// Internal verification methods for stub-level Verify()/VerifyAll()
			w.Line("internal bool IsVerifiable => _isVerifiable;");
			w.Line("internal bool IsConfigured => _handler != null;");
			w.Line();

			w.Line("/// <summary>Checks verification for Stub.Verify() - only verifiable items.</summary>");
			w.Line("internal global::KnockOff.VerificationFailure? CheckVerification()");
			using (w.Braces())
			{
				w.Line("if (!_isVerifiable) return null;");
				w.Line("var times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
				w.Line("var totalCount = _addCount + _removeCount;");
				w.Line("if (!times.Validate(totalCount))");
				w.Line($"\treturn new global::KnockOff.VerificationFailure(\"{evt.EventName}\", times, totalCount);");
				w.Line("return null;");
			}
			w.Line();

			w.Line("/// <summary>Checks verification for Stub.VerifyAll() - all configured items.</summary>");
			w.Line("internal global::KnockOff.VerificationFailure? CheckVerificationAll()");
			using (w.Braces())
			{
				w.Line("if (!IsConfigured && !_isVerifiable) return null;");
				w.Line("var times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
				w.Line("var totalCount = _addCount + _removeCount;");
				w.Line("if (!times.Validate(totalCount))");
				w.Line($"\treturn new global::KnockOff.VerificationFailure(\"{evt.EventName}\", times, totalCount);");
				w.Line("return null;");
			}
		}
		w.Line();
	}

	private static void RenderEventRaiseMethod(CodeWriter w, FlatEventModel evt)
	{
		if (evt.RaiseReturnsValue)
		{
			// Func-style delegate
			w.Line("/// <summary>Raises the event with the specified arguments and returns the result.</summary>");
			if (string.IsNullOrEmpty(evt.RaiseParameters))
			{
				w.Line($"public {evt.RaiseReturnType} Raise() => _handler != null ? _handler.Invoke() : default!;");
			}
			else
			{
				w.Line($"public {evt.RaiseReturnType} Raise({evt.RaiseParameters}) => _handler != null ? _handler.Invoke({evt.RaiseArguments}) : default!;");
			}
		}
		else if (evt.UsesDynamicInvoke)
		{
			// Custom delegate - use DynamicInvoke
			if (string.IsNullOrEmpty(evt.RaiseParameters))
			{
				w.Line("/// <summary>Raises the event.</summary>");
				w.Line("public void Raise() => (_handler as global::System.Action)?.Invoke();");
			}
			else
			{
				w.Line("/// <summary>Invokes the handler if subscribed.</summary>");
				w.Line($"public void Raise({evt.RaiseParameters}) => _handler?.DynamicInvoke({evt.RaiseArguments});");
			}
		}
		else
		{
			// Standard Action/EventHandler
			if (string.IsNullOrEmpty(evt.RaiseParameters))
			{
				w.Line("/// <summary>Raises the event.</summary>");
				w.Line("public void Raise() => _handler?.Invoke();");
			}
			else
			{
				w.Line("/// <summary>Raises the event with the specified arguments.</summary>");
				w.Line($"public void Raise({evt.RaiseParameters}) => _handler?.Invoke({evt.RaiseArguments});");
			}
		}
		w.Line();
	}

	#endregion

	#region Interceptor Properties

	private static void RenderInterceptorProperties(CodeWriter w, FlatGenerationUnit unit)
	{
		// Track rendered interceptor properties to avoid duplicates
		var renderedProperties = new HashSet<string>();

		// Properties
		foreach (var prop in unit.Properties)
		{
			if (!renderedProperties.Add(prop.InterceptorName))
				continue;
			var newKeyword = prop.NeedsNewKeyword ? "new " : "";
			w.Line($"/// <summary>Interceptor for {prop.MemberName}. Configure via .Value, track via .GetCount.</summary>");
			w.Line($"public {newKeyword}{prop.InterceptorClassName} {prop.InterceptorName} {{ get; }} = new();");
			w.Line();
		}

		// Indexers - use container pattern for groups with multiple indexers
		foreach (var group in unit.IndexerGroups)
		{
			if (!renderedProperties.Add(group.BaseName))
				continue;
			var newKeyword = group.NeedsNewKeyword ? "new " : "";

			if (group.Indexers.Count == 1)
			{
				// Single indexer - direct access pattern
				var indexer = group.Indexers.GetArray()![0];
				w.Line($"/// <summary>Interceptor for indexer. Configure callbacks and track access.</summary>");
				w.Line($"public {newKeyword}{indexer.InterceptorClassName} {group.BaseName} {{ get; }} = new();");
				w.Line();
			}
			else
			{
				// Multiple indexers - container pattern with OfXxx access
				w.Line($"/// <summary>Interceptor for indexer. Access via .Of{{KeyType}} (e.g., .OfInt32, .OfString).</summary>");
				w.Line($"public {newKeyword}{group.ContainerClassName} {group.BaseName} {{ get; }} = new();");
				w.Line();
			}
		}

		// Methods (only non-generic - generic methods use handler properties)
		foreach (var method in unit.Methods.Where(m => !m.IsGenericMethod))
		{
			if (!renderedProperties.Add(method.InterceptorName))
				continue;
			var newKeyword = method.NeedsNewKeyword ? "new " : "";
			w.Line($"/// <summary>Interceptor for {method.MethodName}.</summary>");
			w.Line($"public {newKeyword}{method.InterceptorClassName} {method.InterceptorName} {{ get; }} = new();");
			w.Line();
		}

		// Generic method handlers
		foreach (var handler in unit.GenericMethodHandlers)
		{
			if (!renderedProperties.Add(handler.InterceptorName))
				continue;
			var newKeyword = handler.NeedsNewKeyword ? "new " : "";
			w.Line($"/// <summary>Interceptor for {handler.MethodName} (generic method).</summary>");
			w.Line($"public {newKeyword}{handler.InterceptorClassName} {handler.InterceptorName} {{ get; }} = new();");
			w.Line();
		}

		// Generic stub override handler groups (for overloaded generic stub overrides)
		foreach (var handlerGroup in unit.GenericStubOverrideHandlerGroups)
		{
			if (!renderedProperties.Add(handlerGroup.InterceptorName))
				continue;
			var newKeyword = handlerGroup.NeedsNewKeyword ? "new " : "";
			w.Line($"/// <summary>Interceptor for {handlerGroup.MethodName} (generic stub override with overloads).</summary>");
			w.Line($"public {newKeyword}{handlerGroup.InterceptorClassName} {handlerGroup.InterceptorName} {{ get; }} = new();");
			w.Line();
		}

		// Events
		foreach (var evt in unit.Events)
		{
			if (!renderedProperties.Add(evt.InterceptorName))
				continue;
			var newKeyword = evt.NeedsNewKeyword ? "new " : "";
			w.Line($"/// <summary>Interceptor for {evt.EventName} event.</summary>");
			w.Line($"public {newKeyword}{evt.InterceptorClassName} {evt.InterceptorName} {{ get; }} = new();");
			w.Line();
		}
	}

	#endregion

	#region Standard Members

	private static void RenderStandardMembers(CodeWriter w, FlatGenerationUnit unit)
	{
		// Strict mode property with configurable default
		var strictDefault = unit.Strict ? "true" : "false";
		w.Line("/// <summary>When true, throws StubException for unconfigured member access.</summary>");
		w.Line($"public bool Strict {{ get; set; }} = {strictDefault};");
		w.Line();

		// Object accessor - returns the first interface type
		var typeParams = FormatTypeParameters(unit.TypeParameters);
		var primaryInterface = unit.InterfaceList.Count > 0 ? unit.InterfaceList.GetArray()![0] : $"{unit.ClassName}{typeParams}";
		w.Line($"/// <summary>The {primaryInterface} instance. Use for passing to code expecting the interface.</summary>");
		w.Line($"public {primaryInterface} Object => this;");
		w.Line();

		// Verify and VerifyAll methods (if there are any verifiable members)
		// Must check all member types: methods, stub overrides, properties, events
		// NOTE: Indexers excluded - there's a separate bug where indexer container accessor paths are wrong
		// TODO: Fix indexer verification accessor paths (see IndexerGroups vs individual Indexers)
		if (unit.MethodGroups.Count > 0
			|| unit.StubOverrideGroups.Count > 0
			|| unit.Properties.Count > 0
			|| unit.Events.Count > 0)
		{
			RenderVerifyMethods(w, unit);
		}

		// SmartDefault helper (only if there are generic methods)
		if (unit.HasGenericMethods)
		{
			RenderSmartDefaultMethod(w);
		}
	}

	private static void RenderVerifyMethods(CodeWriter w, FlatGenerationUnit unit)
	{
		// Get unique interceptor names for methods (method groups define the interceptor names)
		var methodInterceptorNames = unit.MethodGroups
			.Select(g => g.InterceptorName)
			.Distinct()
			.ToList();

		// Get unique user-defined method interceptor names (tracking-only, always configured)
		var stubOverrideInterceptorNames = unit.StubOverrideGroups
			.Select(g => g.InterceptorName)
			.Distinct()
			.ToList();

		// Get unique property interceptor names
		var propertyInterceptorNames = unit.Properties
			.Select(p => p.InterceptorName)
			.Distinct()
			.ToList();

		// Get unique indexer interceptor names
		var indexerInterceptorNames = unit.Indexers
			.Select(i => i.InterceptorName)
			.Distinct()
			.ToList();

		// Get unique event interceptor names
		var eventInterceptorNames = unit.Events
			.Select(e => e.InterceptorName)
			.Distinct()
			.ToList();

		// Verify method - checks only .Verifiable() items, throws if any fail
		w.Line("/// <summary>Verifies all members marked with .Verifiable() were invoked as expected. Throws VerificationException with all failures if any fail.</summary>");
		using (w.Block("public void Verify()"))
		{
			w.Line("var failures = new global::System.Collections.Generic.List<global::KnockOff.VerificationFailure>();");
			w.Line();

			// Check verifiable method interceptors
			foreach (var name in methodInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check verifiable property interceptors
			foreach (var name in propertyInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check verifiable indexer interceptors
			foreach (var name in indexerInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check verifiable event interceptors
			foreach (var name in eventInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check verifiable user-defined method interceptors
			foreach (var name in stubOverrideInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			w.Line();
			w.Line("if (failures.Count > 0)");
			w.Line("\tthrow new global::KnockOff.VerificationException(failures);");
		}
		w.Line();

		// VerifyAll method - checks ALL configured members, throws if any fail
		// NOTE: User-defined methods are NOT included in VerifyAll because they are always "configured"
		w.Line("/// <summary>Verifies ALL configured members were invoked at least once. Throws VerificationException with all failures if any fail.</summary>");
		using (w.Block("public void VerifyAll()"))
		{
			w.Line("var failures = new global::System.Collections.Generic.List<global::KnockOff.VerificationFailure>();");
			w.Line();

			// Check all configured method interceptors
			foreach (var name in methodInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerificationAll() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check all configured property interceptors
			foreach (var name in propertyInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerificationAll() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check all configured indexer interceptors
			foreach (var name in indexerInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerificationAll() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			// Check all configured event interceptors
			foreach (var name in eventInterceptorNames)
			{
				w.Line($"if ({name}.CheckVerificationAll() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
			}

			w.Line();
			w.Line("if (failures.Count > 0)");
			w.Line("\tthrow new global::KnockOff.VerificationException(failures);");
		}
		w.Line();
	}

	private static void RenderSmartDefaultMethod(CodeWriter w)
	{
		w.Line("/// <summary>Gets a smart default value for a generic type at runtime.</summary>");
		using (w.Block("private static T SmartDefault<T>(string methodName)"))
		{
			w.Line("var type = typeof(T);");
			w.Line();
			w.Line("// Value types -> default(T)");
			w.Line("if (type.IsValueType)");
			w.Line("\treturn default!;");
			w.Line();
			w.Line("// Check for parameterless constructor");
			w.Line("var ctor = type.GetConstructor(");
			w.Line("\tSystem.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance,");
			w.Line("\tnull, System.Type.EmptyTypes, null);");
			w.Line();
			w.Line("if (ctor != null)");
			w.Line("\treturn (T)ctor.Invoke(null);");
			w.Line();
			w.Line("throw new global::System.InvalidOperationException(");
			w.Line("\t$\"No implementation provided for {methodName}<{type.Name}>. \" +");
			w.Line("\t$\"Set the handler's Return or Call.\");");
		}
		w.Line();
	}

	#endregion

	#region Source Methods

	/// <summary>
	/// Renders Source(T) methods for each interface in the inheritance hierarchy.
	/// Each Source(T) overload sets _source for members declared on T or its bases,
	/// and clears _source for members declared on more derived interfaces.
	/// </summary>
	private static void RenderSourceMethods(CodeWriter w, FlatGenerationUnit unit)
	{
		if (unit.SourceProviders.Count == 0)
			return;

		w.Line("// Source(T) methods for interface delegation");
		w.Line();

		foreach (var provider in unit.SourceProviders)
		{
			w.Line($"/// <summary>Delegates unconfigured member access to the provided source object ({provider.InterfaceType}).</summary>");
			w.Line($"/// <param name=\"source\">The source to delegate to, or null to clear.</param>");
			using (w.Block($"public void {provider.MethodName}({provider.InterfaceType}? source)"))
			{
				foreach (var mapping in provider.MemberMappings)
				{
					if (mapping.SetSource)
					{
						w.Line($"{mapping.InterceptorName}._source = source;");
					}
					else
					{
						w.Line($"{mapping.InterceptorName}._source = null;");
					}
				}
			}
			w.Line();
		}
	}

	#endregion

	#region Property Implementation

	private static void RenderPropertyImplementation(CodeWriter w, FlatPropertyModel prop)
	{
		// Handle property delegation (e.g., IProperty.Value (object) delegates to IProperty<T>.Value (T))
		if (prop.DelegationTarget != null && prop.DelegationTargetInterface != null)
		{
			RenderPropertyDelegation(w, prop);
			return;
		}

		// User-defined properties with base class pattern: record access, check Get/Set, then delegate to virtual property
		if (prop.HasStubOverride)
		{
			RenderPropertyStubOverrideImplementation(w, prop);
			return;
		}

		w.Line($"{prop.RefReturnPrefix}{prop.ReturnType} {prop.DeclaringInterface}.{prop.MemberName}");
		using (w.Braces())
		{
			if (prop.IsRefReturn)
			{
				// Ref return properties are always get-only (C# constraint)
				w.Line("get");
				using (w.Braces())
				{
					w.Line($"{prop.InterceptorName}.InvokeRefGet(Strict);");
					w.Line($"return ref {prop.InterceptorName}._refReturnBacking;");
				}
			}
			else if (prop.IsInitOnly)
			{
				// Init-only: use InvokeGet for getter, but init setter records and sets value via SetValue
				w.Line($"get => {prop.InterceptorName}.InvokeGet(Strict);");
				w.Line($"init {{ {prop.InterceptorName}.RecordSet(value); {prop.InterceptorName}.SetValue(value); }}");
			}
			else
			{
				// Regular properties: use InvokeGet/InvokeSet which handle the priority chain
				if (prop.HasGetter)
				{
					w.Line($"get => {prop.InterceptorName}.InvokeGet(Strict);");
				}

				if (prop.HasSetter)
				{
					if (prop.SetterPragmaDisable != null)
						w.Append(prop.SetterPragmaDisable);
					w.Line($"set => {prop.InterceptorName}.InvokeSet(Strict, value);");
					if (prop.SetterPragmaRestore != null)
						w.Line(prop.SetterPragmaRestore);
				}
			}
		}
		w.Line();
	}

	/// <summary>
	/// Renders the explicit interface implementation for a property with stub override (base class pattern).
	/// Priority chain: Get/Set > Stub override (virtual property with _ suffix).
	/// Unlike properties without stub override, this does NOT fall through to Strict/Default.
	/// </summary>
	private static void RenderPropertyStubOverrideImplementation(CodeWriter w, FlatPropertyModel prop)
	{
		w.Line($"{prop.ReturnType} {prop.DeclaringInterface}.{prop.MemberName}");
		using (w.Braces())
		{
			if (prop.HasGetter)
			{
				w.Line("get");
				using (w.Braces())
				{
					// Get supersedes stub override (InvokeGetCallback tracks internally)
					w.Line($"if ({prop.InterceptorName}.HasGet) return {prop.InterceptorName}.InvokeGetCallback();");
					// Record access only for stub override path (to avoid double counting)
					w.Line($"{prop.InterceptorName}.RecordGet();");
					// Stub override (virtual property with _ suffix)
					w.Line($"return {prop.MemberName}_;");
				}
			}

			if (prop.HasSetter)
			{
				if (prop.SetterPragmaDisable != null)
					w.Append(prop.SetterPragmaDisable);
				w.Line("set");
				using (w.Braces())
				{
					// Set supersedes stub override (InvokeSetCallback tracks internally)
					w.Line($"if ({prop.InterceptorName}.HasSet) {{ {prop.InterceptorName}.InvokeSetCallback(value); return; }}");
					// Record access only for stub override path (to avoid double counting)
					w.Line($"{prop.InterceptorName}.RecordSet(value);");
					// Stub override (virtual property with _ suffix)
					w.Line($"{prop.MemberName}_ = value;");
				}
				if (prop.SetterPragmaRestore != null)
					w.Line(prop.SetterPragmaRestore);
			}
		}
		w.Line();
	}

	private static void RenderPropertyDelegation(CodeWriter w, FlatPropertyModel prop)
	{
		var target = prop.DelegationTarget!;
		var targetInterface = prop.DelegationTargetInterface!;

		w.Line($"{prop.ReturnType} {prop.DeclaringInterface}.{prop.MemberName}");
		using (w.Braces())
		{
			if (prop.HasGetter)
			{
				// Cast the typed value to object (or the base return type)
				w.Line($"get => (({targetInterface})this).{target.Name}!;");
			}

			if (prop.HasSetter)
			{
				// Cast the object value to the typed type
				w.Line($"set => (({targetInterface})this).{target.Name} = ({target.ReturnType.TrimEnd('?')})value!;");
			}
		}
		w.Line();
	}

	#endregion

	#region Indexer Implementation

	private static void RenderIndexerImplementation(CodeWriter w, FlatIndexerModel indexer, Dictionary<string, string> indexerAccessMap)
	{
		// Get the correct access expression (e.g., "Indexer" or "Indexer.OfInt32")
		var accessExpr = indexerAccessMap.TryGetValue(indexer.InterceptorName, out var mapped)
			? mapped
			: indexer.InterceptorName;

		w.Line($"{indexer.RefReturnPrefix}{indexer.ReturnType} {indexer.DeclaringInterface}.this[{indexer.KeyType} {indexer.KeyParamName}]");
		using (w.Braces())
		{
			if (indexer.IsRefReturn)
			{
				// Ref return indexers are always get-only (C# constraint)
				w.Line("get");
				using (w.Braces())
				{
					w.Line($"{accessExpr}.InvokeRefGet(Strict, {indexer.KeyParamName});");
					w.Line($"return ref {accessExpr}._refReturnBacking;");
				}
			}
			else
			{
				// Use InvokeGet/InvokeSet which handle the priority chain
				if (indexer.HasGetter)
				{
					w.Line($"get => {accessExpr}.InvokeGet(Strict, {indexer.KeyParamName});");
				}

				if (indexer.HasSetter)
				{
					w.Line($"set => {accessExpr}.InvokeSet(Strict, {indexer.KeyParamName}, value);");
				}
			}
		}
		w.Line();
	}

	#endregion

	#region Method Implementation

	private static void RenderMethodImplementation(
		CodeWriter w,
		FlatMethodModel method,
		HashSet<string> multiOverloadInterceptors,
		HashSet<string> multiOverloadStubOverrideInterceptors,
		HashSet<string> multiOverloadGenericStubOverrideInterceptors,
		EquatableArray<FlatGenericMethodHandlerGroup> genericStubOverrideHandlerGroups)
	{
		// Handle method delegation (e.g., IRule.RunRule(IValidateBase) delegates to IRule<T>.RunRule(T))
		if (method.DelegationTarget != null && method.DelegationTargetInterface != null)
		{
			RenderMethodDelegation(w, method);
			return;
		}

		// Generic methods use method-based Return/Call API via typed handlers
		if (method.IsGenericMethod)
		{
			RenderGenericMethodImplementation(w, method, multiOverloadGenericStubOverrideInterceptors, genericStubOverrideHandlerGroups);
			return;
		}

		// User-defined methods with base class pattern: record call, check Return/Call, then delegate to virtual method
		if (method.HasStubOverride)
		{
			RenderStubOverrideImplementation(w, method, multiOverloadStubOverrideInterceptors);
			return;
		}

		// Determine if this method is part of an overload group (needs suffixed Invoke)
		var isMultiOverload = multiOverloadInterceptors.Contains(method.InterceptorName);
		var invokeSuffix = isMultiOverload ? $"_{GetSignatureSuffix(method)}" : "";

		// Non-generic methods use the new Invoke pattern
		w.Line($"{method.RefReturnPrefix}{method.ReturnType} {method.DeclaringInterface}.{method.MethodName}({method.ParameterDeclarations})");
		using (w.Braces())
		{
			// Build invoke args (includes Strict, no stub parameter)
			var invokeArgs = method.Parameters.Count > 0
				? "Strict, " + string.Join(", ", method.Parameters.Select(p => $"{p.RefPrefix}{p.EscapedName}"))
				: "Strict";

			if (method.IsRefReturn)
			{
				var invokeRefSuffix = isMultiOverload ? $"_{GetSignatureSuffix(method)}" : "";
				var backingField = isMultiOverload ? $"_refReturnBacking_{GetSignatureSuffix(method)}" : "_refReturnBacking";
				w.Line($"{method.InterceptorName}.InvokeRef{invokeRefSuffix}({invokeArgs});");
				w.Line($"return ref {method.InterceptorName}.{backingField};");
			}
			else if (method.IsVoid)
				w.Line($"{method.InterceptorName}.Invoke{invokeSuffix}({invokeArgs});");
			else
				w.Line($"return {method.InterceptorName}.Invoke{invokeSuffix}({invokeArgs});");
		}
		w.Line();
	}

	/// <summary>
	/// Renders the explicit interface implementation for a method with stub override (base class pattern).
	/// Priority chain: When chains > Sequences > Return/Call > Stub override (virtual method with _ suffix).
	/// The unified interceptor handles all logic including stub override fallback.
	/// </summary>
	private static void RenderStubOverrideImplementation(CodeWriter w, FlatMethodModel method, HashSet<string> multiOverloadStubOverrideInterceptors)
	{
		// Determine if this stub override is part of an overload group (needs suffixed Invoke)
		var isMultiOverload = multiOverloadStubOverrideInterceptors.Contains(method.InterceptorName);
		var invokeSuffix = isMultiOverload ? $"_{GetSignatureSuffix(method)}" : "";

		w.Line($"{method.ReturnType} {method.DeclaringInterface}.{method.MethodName}({method.ParameterDeclarations})");
		using (w.Braces())
		{
			// Build invoke args (includes Strict, stub reference, and method parameters)
			var invokeArgs = method.Parameters.Count > 0
				? "Strict, this, " + string.Join(", ", method.Parameters.Select(p => $"{p.RefPrefix}{p.EscapedName}"))
				: "Strict, this";

			if (method.IsVoid)
				w.Line($"{method.InterceptorName}.Invoke{invokeSuffix}({invokeArgs});");
			else
				w.Line($"return {method.InterceptorName}.Invoke{invokeSuffix}({invokeArgs});");
		}
		w.Line();
	}

	private static void RenderGenericMethodImplementation(
		CodeWriter w,
		FlatMethodModel method,
		HashSet<string> multiOverloadGenericStubOverrideInterceptors,
		EquatableArray<FlatGenericMethodHandlerGroup> genericStubOverrideHandlerGroups)
	{
		// For methods with unconstrained nullable type parameters (T? without where T : class),
		// we must disable nullable context. Without this, the compiler interprets T? as Nullable<T>
		// (CS0453) or reports nullability mismatch (CS8769). The type strings are already stripped
		// of ? for these type parameters by the builder.
		if (method.NeedsNullableDisable)
			w.Line("#nullable disable");

		// Generic methods use the method-based Return/Call API via typed handlers
		w.Line($"{method.ReturnType} {method.DeclaringInterface}.{method.MethodName}{method.TypeParameterDecl}({method.ParameterDeclarations}){method.ConstraintClauses}");
		using (w.Braces())
		{
			// Initialize out parameters
			foreach (var p in method.Parameters.Where(p => p.RefKind == Microsoft.CodeAnalysis.RefKind.Out))
			{
				w.Line($"{p.EscapedName} = default!;");
			}

			var interceptorAccess = $"{method.InterceptorName}{method.OfTypeAccess}";

			// Generic methods use RecordCallArgs (excludes generic-typed params)
			var recordCallArgs = method.RecordCallArgs;

			// Record the call
			w.Line($"{interceptorAccess}.RecordCall({recordCallArgs});");

			// Build onCall args (no stub parameter)
			var callArgs = method.Parameters.Count > 0
				? string.Join(", ", method.Parameters.Select(p => $"{p.RefPrefix}{p.EscapedName}"))
				: "";

			if (method.IsVoid)
			{
				w.Line($"if ({interceptorAccess}.Callback is {{ }} callCallback)");
				w.Line($"{{ callCallback({callArgs}); return; }}");
				w.Line($"if (Strict) throw global::KnockOff.StubException.NotConfigured(\"{method.SimpleInterfaceName}\", \"{method.MethodName}\");");
				// Generic methods don't support stub overrides - just return for void
			}
			else if (method.ThrowsOnDefault)
			{
				w.Line($"if ({interceptorAccess}.Callback is {{ }} callback)");
				w.Line($"\treturn callback({callArgs});");
				w.Line($"if (Strict) throw global::KnockOff.StubException.NotConfigured(\"{method.SimpleInterfaceName}\", \"{method.MethodName}\");");
				w.Line($"throw new global::System.InvalidOperationException(\"No implementation provided for {method.MethodName}. Use {interceptorAccess}.{(method.IsVoid ? "Call" : "Return")}(callback).\");");
			}
			else
			{
				w.Line($"if ({interceptorAccess}.Callback is {{ }} callback)");
				w.Line($"\treturn callback({callArgs});");
				w.Line($"if (Strict) throw global::KnockOff.StubException.NotConfigured(\"{method.SimpleInterfaceName}\", \"{method.MethodName}\");");
				w.Line($"return {method.DefaultExpression};");
			}
		}

		if (method.NeedsNullableDisable)
			w.Line("#nullable restore");
		w.Line();
	}

	/// <summary>
	/// Gets the signature suffix for a generic stub override from the handler groups.
	/// </summary>
	private static string GetGenericStubOverrideSignatureSuffix(
		FlatMethodModel method,
		EquatableArray<FlatGenericMethodHandlerGroup> handlerGroups)
	{
		var group = handlerGroups.FirstOrDefault(g => g.InterceptorName == method.InterceptorName);
		if (group == null)
			return "";

		// Strip angle brackets from method's type parameter list for comparison
		// TypeParameterList has angle brackets (e.g., "<T>"), TypeParameterNames does not (e.g., "T")
		var methodTypeParams = method.TypeParameterList.TrimStart('<').TrimEnd('>');

		// Find the type arity group matching this method's type parameters
		var arityGroup = group.TypeArityGroups.FirstOrDefault(a => a.TypeParameterNames == methodTypeParams);
		if (arityGroup == null)
			return "";

		// Find the signature group matching this method
		// We need to match by parameter types
		var paramArray = method.Parameters.GetArray() ?? Array.Empty<ParameterModel>();
		foreach (var sig in arityGroup.SignatureGroups)
		{
			var sigParams = sig.AllParameters.GetArray() ?? Array.Empty<ParameterModel>();
			if (paramArray.Length == sigParams.Length)
			{
				var match = true;
				for (int i = 0; i < paramArray.Length; i++)
				{
					if (paramArray[i].Type != sigParams[i].Type)
					{
						match = false;
						break;
					}
				}
				if (match)
					return sig.SignatureSuffix;
			}
		}

		return "";
	}

	private static void RenderMethodDelegation(CodeWriter w, FlatMethodModel method)
	{
		var target = method.DelegationTarget!;
		var targetInterface = method.DelegationTargetInterface!;

		// Build parameter cast expressions for delegation
		var memberParams = method.Parameters.GetArray() ?? System.Array.Empty<KnockOff.Model.Shared.ParameterModel>();
		var targetParams = target.Parameters.GetArray() ?? System.Array.Empty<ParameterInfo>();

		var castArgs = new List<string>();
		for (int i = 0; i < memberParams.Length; i++)
		{
			var memberType = memberParams[i].Type;
			var targetType = targetParams[i].Type;
			var paramName = memberParams[i].EscapedName;

			if (memberType != targetType)
			{
				// Cast to the target type
				castArgs.Add($"({targetType}){paramName}");
			}
			else
			{
				castArgs.Add(paramName);
			}
		}

		var argList = string.Join(", ", castArgs);

		// Expression-bodied members don't use 'return' keyword
		if (method.NeedsNullableDisable)
			w.Line("#nullable disable");
		w.Line($"{method.ReturnType} {method.DeclaringInterface}.{method.MethodName}{method.TypeParameterDecl}({method.ParameterDeclarations}){method.ConstraintClauses}");
		w.Line($"\t=> (({targetInterface})this).{target.Name}({argList});");
		if (method.NeedsNullableDisable)
			w.Line("#nullable restore");
		w.Line();
	}

	#endregion

	#region Event Implementation

	private static void RenderEventImplementation(CodeWriter w, FlatEventModel evt)
	{
		w.Line($"event {evt.DelegateType}? {evt.DeclaringInterface}.{evt.EventName}");
		using (w.Braces())
		{
			w.Line($"add => {evt.InterceptorName}.RecordAdd(value);");
			w.Line($"remove => {evt.InterceptorName}.RecordRemove(value);");
		}
		w.Line();
	}

	#endregion

	#region Async Type Helpers

	/// <summary>
	/// Analyzes a return type for async patterns and extracts the inner type.
	/// Used for Returns() auto-wrapping in stub override interceptors.
	/// </summary>
	private static (string InnerType, bool IsTaskT, bool IsValueTaskT) GetAsyncTypeInfo(string returnType)
	{
		const string TaskPrefix = "global::System.Threading.Tasks.Task<";
		const string ValueTaskPrefix = "global::System.Threading.Tasks.ValueTask<";

		if (returnType.StartsWith(TaskPrefix) && returnType.EndsWith(">"))
		{
			var innerType = returnType.Substring(TaskPrefix.Length, returnType.Length - TaskPrefix.Length - 1);
			return (innerType, true, false);
		}

		if (returnType.StartsWith(ValueTaskPrefix) && returnType.EndsWith(">"))
		{
			var innerType = returnType.Substring(ValueTaskPrefix.Length, returnType.Length - ValueTaskPrefix.Length - 1);
			return (innerType, false, true);
		}

		return (returnType, false, false);
	}

	#endregion
}
