// src/Generator/Renderer/InlineRenderer.cs
#nullable enable
using System.Collections.Generic;
using System.Linq;
using KnockOff.Model.Inline;
using KnockOff.Model.Shared;
using KnockOff.Renderer.Shared;

namespace KnockOff.Renderer;

/// <summary>
/// Renders InlineGenerationUnit to source code string.
/// Pure emission - no decisions, just output what the model says.
/// </summary>
internal static class InlineRenderer
{
    public static string Render(InlineGenerationUnit unit)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();

        // Add using System.Linq if there are generic methods (needed for aggregate LINQ)
        if (unit.HasGenericMethods)
        {
            w.Line("using System.Linq;");
            w.Line();
        }

        // Namespace
        if (!string.IsNullOrEmpty(unit.Namespace))
        {
            w.Line($"namespace {unit.Namespace};");
            w.Line();
        }

        // Open containing type wrappers for nested classes
        foreach (var containingType in unit.ContainingTypes)
        {
            var accessMod = string.IsNullOrEmpty(containingType.AccessModifier)
                ? ""
                : containingType.AccessModifier + " ";
            w.Line($"{accessMod}partial {containingType.Keyword} {containingType.Name}");
            w.Line("{");
        }

        // Partial class
        w.Line($"partial class {unit.ClassName}");
        w.Line("{");

        // Nested Stubs class
        w.Line("\t/// <summary>Contains stub implementations for inline stub pattern.</summary>");
        w.Line("\tpublic static class Stubs");
        w.Line("\t{");

        // Check if any interface has generic methods - if so, generate helper interfaces
        if (unit.HasGenericMethods)
        {
            w.Line("\t\tprivate interface IGenericMethodCallTracker { int CallCount { get; } }");
            w.Line("\t\tprivate interface IResettable { void Reset(); }");
            w.Line();
        }

        // Render interface stubs
        foreach (var ifaceStub in unit.InterfaceStubs)
        {
            RenderInterfaceStub(w, ifaceStub);
        }

        // Render delegate stubs
        foreach (var delStub in unit.DelegateStubs)
        {
            RenderDelegateStub(w, delStub);
        }

        // Render class stubs
        foreach (var classStub in unit.ClassStubs)
        {
            RenderClassStub(w, classStub);
        }

        w.Line("\t}"); // Close Stubs class

        // Render partial property implementations
        foreach (var prop in unit.PartialProperties)
        {
            RenderPartialProperty(w, prop);
        }

        w.Line("}"); // Close partial class

        // Close containing type wrappers
        for (int i = 0; i < unit.ContainingTypes.Count; i++)
        {
            w.Line("}");
        }

        return w.ToString();
    }

    #region Interface Stub Rendering

    private static void RenderInterfaceStub(CodeWriter w, InlineInterfaceStubModel iface)
    {
        // Use shared renderers for property and indexer interceptors
        var typeParams = FormatTypeParameterList(iface.TypeParameters);
        var constraints = FormatConstraints(iface.TypeParameters);
        var previousIndent = w.Indent;
        w.SetIndent(2);  // Inline stubs are nested 2 levels deep

        // Render property interceptor classes using shared renderer
        foreach (var prop in iface.Properties)
        {
            var unifiedModel = ModelAdapters.ToUnifiedPropertyModel(prop);
            // Use property-specific type parameters (may differ from interface-level for open generics)
            var options = new PropertyInterceptorRenderOptions(
                BaseIndent: 2,
                IncludeStrictParameter: true,
                StrictAccessExpression: "strict",
                InterceptorTypeParameters: prop.TypeParameterList,
                InterceptorConstraints: prop.ConstraintClauses);
            PropertyInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, options);
        }

        // Render indexer interceptor classes using shared renderer
        foreach (var indexer in iface.Indexers)
        {
            var unifiedModel = ModelAdapters.ToUnifiedIndexerModel(indexer);
            // Use indexer-specific type parameters (may differ from interface-level for open generics)
            var options = new IndexerInterceptorRenderOptions(
                BaseIndent: 2,
                IncludeStrictParameter: true,
                StrictAccessExpression: "strict",
                InterceptorTypeParameters: indexer.TypeParameterList,
                InterceptorConstraints: indexer.ConstraintClauses);
            IndexerInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, options);
        }

        w.SetIndent(previousIndent);

        // Render container classes for multi-indexer groups
        foreach (var group in iface.IndexerGroups)
        {
            if (group.Indexers.Count > 1)
            {
                RenderIndexerContainerClass(w, group);
            }
        }

        // Use shared renderer for method interceptors
        // Set indent level for nested class context (inside partial class and Stubs class)
        var methodTypeParams = FormatTypeParameterList(iface.TypeParameters);
        var methodConstraints = FormatConstraints(iface.TypeParameters);
        previousIndent = w.Indent;
        w.SetIndent(2);  // Inline stubs are nested 2 levels deep
        foreach (var method in iface.Methods)
        {
            var options = new InterceptorRenderOptions(
                BaseIndent: 2,
                IncludeStrictParameter: true,
                StrictAccessExpression: "strict",
                InterceptorTypeParameters: methodTypeParams,
                InterceptorConstraints: methodConstraints);
            MethodInterceptorRenderer.RenderInterceptorClass(w, method, options);
        }
        w.SetIndent(previousIndent);

        foreach (var handler in iface.GenericMethodHandlers)
        {
            RenderGenericMethodHandler(w, handler);
        }

        foreach (var evt in iface.Events)
        {
            RenderEventInterceptorClass(w, evt, iface.StubClassName);
        }

        // Render the stub class
        var stubTypeParamList = FormatTypeParameterList(iface.TypeParameters);
        var stubConstraints = FormatConstraints(iface.TypeParameters);

        w.Line($"\t\t/// <summary>Stub implementation of {iface.BaseType}.</summary>");
        w.Line($"\t\tpublic class {iface.StubClassName}{stubTypeParamList} : {iface.BaseType}, global::KnockOff.IKnockOffStub{stubConstraints}");
        w.Line("\t\t{");

        // Interceptor properties
        foreach (var interceptorProp in iface.InterceptorProperties)
        {
            var newKeyword = interceptorProp.NeedsNewKeyword ? "new " : "";
            w.Line($"\t\t\t/// <summary>{interceptorProp.Description}</summary>");
            w.Line($"\t\t\tpublic {newKeyword}{interceptorProp.InterceptorTypeName} {interceptorProp.PropertyName} {{ get; }} = new();");
            w.Line();
        }

        // Explicit interface implementations
        foreach (var impl in iface.Implementations)
        {
            RenderImplementation(w, impl);
        }

        // Object property
        w.Line($"\t\t\t/// <summary>The {iface.BaseType} instance. Use for passing to code expecting the interface.</summary>");
        w.Line($"\t\t\tpublic {iface.BaseType} Object => this;");
        w.Line();

        // Strict property and constructor
        var strictDefault = iface.Strict ? "true" : "false";
        w.Line("\t\t\t/// <summary>When true, unconfigured method calls throw StubException instead of returning default.</summary>");
        w.Line($"\t\t\tpublic bool Strict {{ get; set; }} = {strictDefault};");
        w.Line();
        w.Line($"\t\t\t/// <summary>Creates a new instance of the stub.</summary>");
        w.Line($"\t\t\t/// <param name=\"strict\">When true, unconfigured method calls throw StubException.</param>");
        w.Line($"\t\t\tpublic {iface.StubClassName}(bool strict = {strictDefault})");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tStrict = strict;");
        w.Line("\t\t\t}");
        w.Line();

        // Source(T) methods for Source feature
        RenderSourceMethods(w, iface);

        // SmartDefault helper if interface has generic methods
        if (iface.HasGenericMethods)
        {
            RenderSmartDefaultMethod(w);
        }

        // Verify and VerifyAll methods
        RenderInlineVerifyMethods(w, iface);

        w.Line("\t\t}");
        w.Line();
    }

    private static void RenderInlineVerifyMethods(CodeWriter w, InlineInterfaceStubModel iface)
    {
        // Get unique interceptor property names (the actual property names on the stub class)
        var interceptorPropertyNames = iface.InterceptorProperties
            .Select(p => p.PropertyName)
            .Distinct()
            .ToList();

        // Verify method - checks only .Verifiable() items, throws if any fail
        w.Line("\t\t\t/// <summary>Verifies all members marked with .Verifiable() were invoked as expected. Throws VerificationException with all failures if any fail.</summary>");
        w.Line("\t\t\tpublic void Verify()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tvar failures = new global::System.Collections.Generic.List<global::KnockOff.VerificationFailure>();");
        w.Line();

        // Check all interceptors (methods and properties share the same pattern)
        foreach (var name in interceptorPropertyNames)
        {
            w.Line($"\t\t\t\tif ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
        }

        w.Line();
        w.Line("\t\t\t\tif (failures.Count > 0)");
        w.Line("\t\t\t\t\tthrow new global::KnockOff.VerificationException(failures);");
        w.Line("\t\t\t}");
        w.Line();

        // VerifyAll method - checks ALL configured members, throws if any fail
        w.Line("\t\t\t/// <summary>Verifies ALL configured members were invoked at least once. Throws VerificationException with all failures if any fail.</summary>");
        w.Line("\t\t\tpublic void VerifyAll()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tvar failures = new global::System.Collections.Generic.List<global::KnockOff.VerificationFailure>();");
        w.Line();

        // Check all configured interceptors
        foreach (var name in interceptorPropertyNames)
        {
            w.Line($"\t\t\t\tif ({name}.CheckVerificationAll() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
        }

        w.Line();
        w.Line("\t\t\t\tif (failures.Count > 0)");
        w.Line("\t\t\t\t\tthrow new global::KnockOff.VerificationException(failures);");
        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderPropertyInterceptorClass(CodeWriter w, InlinePropertyModel prop, string stubClassName)
    {
        var typeParamList = prop.TypeParameterList;
        var constraintClause = prop.ConstraintClauses;

        w.Line($"\t\t/// <summary>Interceptor for {stubClassName}.{prop.PropertyName}.</summary>");
        w.Line($"\t\tpublic sealed class {prop.InterceptorClassName}{typeParamList}{constraintClause}");
        w.Line("\t\t{");

        // Verifiable state
        w.Line("\t\t\tprivate bool _isVerifiable;");
        w.Line("\t\t\tprivate global::KnockOff.Times? _verifiableTimes;");
        w.Line("\t\t\tprivate bool _valueSet;");
        w.Line();

        if (prop.HasGetter)
        {
            w.Line("\t\t\tprivate int _getCount;");
            w.Line();
            w.Line($"\t\t\t/// <summary>Callback for getter. If set, returns its value.</summary>");
            w.Line($"\t\t\tpublic global::System.Func<{prop.ReturnType}>? OnGet {{ get; set; }}");
            w.Line();
        }

        if (prop.HasSetter)
        {
            w.Line("\t\t\tprivate int _setCount;");
            w.Line();
            w.Line($"\t\t\t/// <summary>The last value passed to the setter.</summary>");
            w.Line($"\t\t\tpublic {prop.NullableReturnType} LastSetValue {{ get; private set; }}");
            w.Line();
            w.Line($"\t\t\t/// <summary>Callback for setter.</summary>");
            w.Line($"\t\t\tpublic global::System.Action<{prop.ReturnType}>? OnSet {{ get; set; }}");
            w.Line();
        }

        // Value property with backing field - setting Value marks the property as configured
        w.Line($"\t\t\tprivate {prop.ReturnType} _value = default!;");
        w.Line($"\t\t\t/// <summary>Value returned by getter when OnGet is not set. Setting this marks the property as configured.</summary>");
        w.Line($"\t\t\tpublic {prop.ReturnType} Value");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tget => _value;");
        w.Line("\t\t\t\tset { _value = value; _valueSet = true; }");
        w.Line("\t\t\t}");
        w.Line();

        // Source field for Source(T) feature - skip for init-only properties
        if (!string.IsNullOrEmpty(prop.DeclaringInterface) && !prop.IsInitOnly)
        {
            w.Line($"\t\t\t/// <summary>Source object for delegation when OnGet is not set.</summary>");
            w.Line($"\t\t\tinternal {prop.DeclaringInterface}? _source;");
            w.Line();
        }

        // RecordGet/RecordSet
        if (prop.HasGetter)
        {
            w.Line("\t\t\t/// <summary>Records a getter access.</summary>");
            w.Line("\t\t\tpublic void RecordGet() => _getCount++;");
            w.Line();
        }
        if (prop.HasSetter)
        {
            w.Line("\t\t\t/// <summary>Records a setter access.</summary>");
            w.Line($"\t\t\tpublic void RecordSet({prop.NullableReturnType} value) {{ _setCount++; LastSetValue = value; }}");
            w.Line();
        }

        // Reset method - clears tracking state but preserves configuration (OnGet/OnSet/Value) and verifiable marking
        w.Line("\t\t\t/// <summary>Resets tracking state (counts, LastSetValue) but preserves configuration (OnGet, OnSet, Value) and verifiable marking.</summary>");
        var resetParts = new List<string>();
        if (prop.HasGetter) resetParts.Add("_getCount = 0;");
        if (prop.HasSetter) resetParts.Add("_setCount = 0; LastSetValue = default;");
        if (!string.IsNullOrEmpty(prop.DeclaringInterface) && !prop.IsInitOnly) resetParts.Add("_source = null;");
        w.Line($"\t\t\tpublic void Reset() {{ {string.Join(" ", resetParts)} }}");
        w.Line();

        // Verifiable methods (fluent)
        w.Line($"\t\t\t/// <summary>Marks this property for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
        w.Line($"\t\t\tpublic {prop.InterceptorClassName}{typeParamList} Verifiable() {{ _isVerifiable = true; _verifiableTimes = null; return this; }}");
        w.Line();
        w.Line($"\t\t\t/// <summary>Marks this property for verification by Stub.Verify() with Times constraint. Returns this for fluent chaining.</summary>");
        w.Line($"\t\t\tpublic {prop.InterceptorClassName}{typeParamList} Verifiable(global::KnockOff.Times times) {{ _isVerifiable = true; _verifiableTimes = times; return this; }}");
        w.Line();

        // Verify methods - throw on failure
        // Build total count expression based on available accessors
        var totalCountExpr = prop.HasGetter && prop.HasSetter
            ? "_getCount + _setCount"
            : (prop.HasGetter ? "_getCount" : "_setCount");

        w.Line("\t\t\t/// <summary>Verifies the property was accessed at least once. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify() => Verify(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies total access count satisfies the Times constraint. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tvar totalCount = {totalCountExpr};");
        w.Line("\t\t\t\tif (!times.Validate(totalCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.PropertyName}\", times, totalCount));");
        w.Line("\t\t\t}");
        w.Line();

        // VerifyGet methods
        if (prop.HasGetter)
        {
            w.Line("\t\t\t/// <summary>Verifies the getter was accessed at least once. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifyGet() => VerifyGet(global::KnockOff.Times.AtLeastOnce);");
            w.Line();

            w.Line("\t\t\t/// <summary>Verifies getter access count satisfies the Times constraint. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifyGet(global::KnockOff.Times times)");
            w.Line("\t\t\t{");
            w.Line("\t\t\t\tif (!times.Validate(_getCount))");
            w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.PropertyName} (get)\", times, _getCount));");
            w.Line("\t\t\t}");
            w.Line();
        }

        // VerifySet methods
        if (prop.HasSetter)
        {
            w.Line("\t\t\t/// <summary>Verifies the setter was accessed at least once. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifySet() => VerifySet(global::KnockOff.Times.AtLeastOnce);");
            w.Line();

            w.Line("\t\t\t/// <summary>Verifies setter access count satisfies the Times constraint. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifySet(global::KnockOff.Times times)");
            w.Line("\t\t\t{");
            w.Line("\t\t\t\tif (!times.Validate(_setCount))");
            w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{prop.PropertyName} (set)\", times, _setCount));");
            w.Line("\t\t\t}");
            w.Line();
        }

        // Internal verification support for stub-level Verify/VerifyAll
        w.Line("\t\t\t/// <summary>Whether this property was marked with Verifiable().</summary>");
        w.Line("\t\t\tinternal bool IsVerifiable => _isVerifiable;");
        w.Line();

        // IsConfigured - Value set OR OnGet/OnSet callback registered
        var isConfiguredParts = new List<string> { "_valueSet" };
        if (prop.HasGetter) isConfiguredParts.Add("OnGet != null");
        if (prop.HasSetter) isConfiguredParts.Add("OnSet != null");
        w.Line("\t\t\t/// <summary>Whether this property has been configured (Value set or callbacks registered).</summary>");
        w.Line($"\t\t\tinternal bool IsConfigured => {string.Join(" || ", isConfiguredParts)};");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerification()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!_isVerifiable) return null;");
        w.Line("\t\t\t\tvar times = _verifiableTimes ?? global::KnockOff.Times.AtLeastOnce;");
        w.Line($"\t\t\t\tvar totalCount = {totalCountExpr};");
        w.Line($"\t\t\t\treturn times.Validate(totalCount) ? null : new global::KnockOff.VerificationFailure(\"{prop.PropertyName}\", times, totalCount);");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerificationAll()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!IsConfigured) return null;");
        w.Line($"\t\t\t\tvar totalCount = {totalCountExpr};");
        w.Line($"\t\t\t\treturn totalCount >= 1 ? null : new global::KnockOff.VerificationFailure(\"{prop.PropertyName}\", global::KnockOff.Times.AtLeastOnce, totalCount);");
        w.Line("\t\t\t}");

        w.Line("\t\t}");
        w.Line();
    }

    private static void RenderIndexerInterceptorClass(CodeWriter w, InlineIndexerModel indexer, string stubClassName)
    {
        var typeParamList = indexer.TypeParameterList;
        var constraintClause = indexer.ConstraintClauses;

        w.Line($"\t\t/// <summary>Interceptor for {stubClassName}.{indexer.IndexerName}.</summary>");
        w.Line($"\t\tpublic sealed class {indexer.InterceptorClassName}{typeParamList}{constraintClause}");
        w.Line("\t\t{");

        // Verifiable state
        w.Line("\t\t\tprivate bool _isVerifiable;");
        w.Line("\t\t\tprivate global::KnockOff.Times? _verifiableTimes;");
        w.Line("\t\t\tprivate bool _configured;");
        w.Line();

        if (indexer.HasGetter)
        {
            w.Line("\t\t\tprivate int _getCount;");
            w.Line();
            w.Line($"\t\t\t/// <summary>The last key used to access the getter.</summary>");
            w.Line($"\t\t\tpublic {indexer.NullableKeyType} LastGetKey {{ get; private set; }}");
            w.Line();
            w.Line($"\t\t\tprivate global::System.Func<{indexer.ParameterTypes}, {indexer.ReturnType}>? _onGet;");
            w.Line($"\t\t\t/// <summary>Callback for getter. Setting this marks the indexer as configured.</summary>");
            w.Line($"\t\t\tpublic global::System.Func<{indexer.ParameterTypes}, {indexer.ReturnType}>? OnGet");
            w.Line("\t\t\t{");
            w.Line("\t\t\t\tget => _onGet;");
            w.Line("\t\t\t\tset { _onGet = value; if (value != null) _configured = true; }");
            w.Line("\t\t\t}");
            w.Line();
        }

        if (indexer.HasSetter)
        {
            w.Line("\t\t\tprivate int _setCount;");
            w.Line();
            w.Line($"\t\t\t/// <summary>The last key-value pair passed to the setter.</summary>");
            w.Line($"\t\t\tpublic ({indexer.KeyType} Key, {indexer.ReturnType} Value)? LastSetEntry {{ get; private set; }}");
            w.Line();
            w.Line($"\t\t\tprivate global::System.Action<{indexer.ParameterTypes}, {indexer.ReturnType}>? _onSet;");
            w.Line($"\t\t\t/// <summary>Callback for setter. Setting this marks the indexer as configured.</summary>");
            w.Line($"\t\t\tpublic global::System.Action<{indexer.ParameterTypes}, {indexer.ReturnType}>? OnSet");
            w.Line("\t\t\t{");
            w.Line("\t\t\t\tget => _onSet;");
            w.Line("\t\t\t\tset { _onSet = value; if (value != null) _configured = true; }");
            w.Line("\t\t\t}");
            w.Line();
        }

        // RecordGet/RecordSet
        if (indexer.HasGetter)
        {
            w.Line($"\t\t\t/// <summary>Records a getter access.</summary>");
            w.Line($"\t\t\tpublic void RecordGet({indexer.ParameterSignature}) {{ _getCount++; LastGetKey = {indexer.KeyExpression}; }}");
            w.Line();
        }
        if (indexer.HasSetter)
        {
            w.Line($"\t\t\t/// <summary>Records a setter access.</summary>");
            w.Line($"\t\t\tpublic void RecordSet({indexer.ParameterSignature}, {indexer.ReturnType} value) {{ _setCount++; LastSetEntry = ({indexer.KeyExpression}, value); }}");
            w.Line();
        }

        // Backing dictionary
        w.Line($"\t\t\t/// <summary>Backing storage for this indexer.</summary>");
        w.Line($"\t\t\tpublic global::System.Collections.Generic.Dictionary<{indexer.SingleKeyType}, {indexer.ReturnType}> Backing {{ get; }} = new();");
        w.Line();

        // Source field for Source(T) feature
        if (!string.IsNullOrEmpty(indexer.DeclaringInterface))
        {
            w.Line($"\t\t\t/// <summary>Source object for delegation when OnGet/OnSet is not set.</summary>");
            w.Line($"\t\t\tinternal {indexer.DeclaringInterface}? _source;");
            w.Line();
        }

        // Reset method - clears tracking state but preserves configuration (OnGet/OnSet/Backing) and verifiable marking
        w.Line("\t\t\t/// <summary>Resets tracking state (counts, LastGetKey, LastSetEntry) but preserves configuration (OnGet, OnSet, Backing) and verifiable marking.</summary>");
        var resetParts = new List<string>();
        if (indexer.HasGetter) resetParts.Add("_getCount = 0; LastGetKey = default;");
        if (indexer.HasSetter) resetParts.Add("_setCount = 0; LastSetEntry = default;");
        if (!string.IsNullOrEmpty(indexer.DeclaringInterface)) resetParts.Add("_source = null;");
        w.Line($"\t\t\tpublic void Reset() {{ {string.Join(" ", resetParts)} }}");
        w.Line();

        // Build total count expression based on available accessors
        var totalCountExpr = indexer.HasGetter && indexer.HasSetter
            ? "_getCount + _setCount"
            : (indexer.HasGetter ? "_getCount" : "_setCount");

        // Verifiable methods (fluent)
        w.Line($"\t\t\t/// <summary>Marks this indexer for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
        w.Line($"\t\t\tpublic {indexer.InterceptorClassName}{typeParamList} Verifiable() {{ _isVerifiable = true; _verifiableTimes = null; return this; }}");
        w.Line();
        w.Line($"\t\t\t/// <summary>Marks this indexer for verification by Stub.Verify() with Times constraint. Returns this for fluent chaining.</summary>");
        w.Line($"\t\t\tpublic {indexer.InterceptorClassName}{typeParamList} Verifiable(global::KnockOff.Times times) {{ _isVerifiable = true; _verifiableTimes = times; return this; }}");
        w.Line();

        // Verify methods - throw on failure
        w.Line("\t\t\t/// <summary>Verifies the indexer was accessed at least once. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify() => Verify(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies total access count satisfies the Times constraint. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tvar totalCount = {totalCountExpr};");
        w.Line("\t\t\t\tif (!times.Validate(totalCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{indexer.IndexerName}\", times, totalCount));");
        w.Line("\t\t\t}");
        w.Line();

        // VerifyGet methods
        if (indexer.HasGetter)
        {
            w.Line("\t\t\t/// <summary>Verifies the getter was accessed at least once. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifyGet() => VerifyGet(global::KnockOff.Times.AtLeastOnce);");
            w.Line();

            w.Line("\t\t\t/// <summary>Verifies getter access count satisfies the Times constraint. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifyGet(global::KnockOff.Times times)");
            w.Line("\t\t\t{");
            w.Line("\t\t\t\tif (!times.Validate(_getCount))");
            w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{indexer.IndexerName} (get)\", times, _getCount));");
            w.Line("\t\t\t}");
            w.Line();
        }

        // VerifySet methods
        if (indexer.HasSetter)
        {
            w.Line("\t\t\t/// <summary>Verifies the setter was accessed at least once. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifySet() => VerifySet(global::KnockOff.Times.AtLeastOnce);");
            w.Line();

            w.Line("\t\t\t/// <summary>Verifies setter access count satisfies the Times constraint. Throws VerificationException if not.</summary>");
            w.Line("\t\t\tpublic void VerifySet(global::KnockOff.Times times)");
            w.Line("\t\t\t{");
            w.Line("\t\t\t\tif (!times.Validate(_setCount))");
            w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{indexer.IndexerName} (set)\", times, _setCount));");
            w.Line("\t\t\t}");
            w.Line();
        }

        // Internal verification support for stub-level Verify/VerifyAll
        w.Line("\t\t\t/// <summary>Whether this indexer was marked with Verifiable().</summary>");
        w.Line("\t\t\tinternal bool IsVerifiable => _isVerifiable;");
        w.Line();

        w.Line("\t\t\t/// <summary>Whether this indexer has been configured (callbacks registered).</summary>");
        w.Line("\t\t\tinternal bool IsConfigured => _configured;");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerification()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!_isVerifiable) return null;");
        w.Line("\t\t\t\tvar times = _verifiableTimes ?? global::KnockOff.Times.AtLeastOnce;");
        w.Line($"\t\t\t\tvar totalCount = {totalCountExpr};");
        w.Line($"\t\t\t\treturn times.Validate(totalCount) ? null : new global::KnockOff.VerificationFailure(\"{indexer.IndexerName}\", times, totalCount);");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerificationAll()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!IsConfigured) return null;");
        w.Line($"\t\t\t\tvar totalCount = {totalCountExpr};");
        w.Line($"\t\t\t\treturn totalCount >= 1 ? null : new global::KnockOff.VerificationFailure(\"{indexer.IndexerName}\", global::KnockOff.Times.AtLeastOnce, totalCount);");
        w.Line("\t\t\t}");

        w.Line("\t\t}");
        w.Line();
    }

    private static void RenderIndexerContainerClass(CodeWriter w, InlineIndexerGroup group)
    {
        // Deduplicate by KeyTypeFriendlyName - same key type shares the same interceptor in container
        var uniqueByKeyType = group.Indexers
            .GroupBy(i => i.KeyTypeFriendlyName)
            .Select(g => g.First())
            .ToList();

        w.Line($"\t\t/// <summary>Container for indexer interceptors with OfXxx access pattern.</summary>");
        w.Line($"\t\tpublic sealed class {group.ContainerClassName}");
        w.Line("\t\t{");

        // Of{KeyType} properties (container owns its interceptors)
        foreach (var indexer in uniqueByKeyType)
        {
            w.Line($"\t\t\t/// <summary>Gets the interceptor for indexer with {indexer.KeyTypeFriendlyName} key type.</summary>");
            w.Line($"\t\t\tpublic {indexer.InterceptorClassName}{indexer.TypeParameterList} Of{indexer.KeyTypeFriendlyName} {{ get; }} = new();");
            w.Line();
        }

        // Reset method (resets all)
        w.Line("\t\t\t/// <summary>Resets all indexer interceptors.</summary>");
        w.Line("\t\t\tpublic void Reset()");
        w.Line("\t\t\t{");
        foreach (var indexer in uniqueByKeyType)
        {
            w.Line($"\t\t\t\tOf{indexer.KeyTypeFriendlyName}.Reset();");
        }
        w.Line("\t\t\t}");
        w.Line();

        // Internal verification support for stub-level Verify/VerifyAll
        // Container aggregates verification from all indexer interceptors
        w.Line("\t\t\tinternal bool IsVerifiable => false; // Container is not individually verifiable");

        // Check if any contained interceptor is configured
        var isConfiguredParts = uniqueByKeyType.Select(i => $"Of{i.KeyTypeFriendlyName}.IsConfigured").ToList();
        w.Line($"\t\t\tinternal bool IsConfigured => {string.Join(" || ", isConfiguredParts)};");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerification()");
        w.Line("\t\t\t{");
        // Container returns first failure from any contained interceptor
        foreach (var indexer in uniqueByKeyType)
        {
            w.Line($"\t\t\t\tif (Of{indexer.KeyTypeFriendlyName}.CheckVerification() is {{ }} failure{indexer.KeyTypeFriendlyName}) return failure{indexer.KeyTypeFriendlyName};");
        }
        w.Line("\t\t\t\treturn null;");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerificationAll()");
        w.Line("\t\t\t{");
        // Container returns first failure from any contained interceptor
        foreach (var indexer in uniqueByKeyType)
        {
            w.Line($"\t\t\t\tif (Of{indexer.KeyTypeFriendlyName}.CheckVerificationAll() is {{ }} failure{indexer.KeyTypeFriendlyName}) return failure{indexer.KeyTypeFriendlyName};");
        }
        w.Line("\t\t\t\treturn null;");
        w.Line("\t\t\t}");

        w.Line("\t\t}");
        w.Line();
    }

    // NOTE: RenderMethodInterceptorClass has been removed.
    // Method interceptors now use the shared MethodInterceptorRenderer.RenderInterceptorClass.

    private static void RenderGenericMethodHandler(CodeWriter w, InlineGenericMethodHandlerModel handler)
    {
        var ifaceTypeParamList = handler.InterfaceTypeParameterList;
        var ifaceConstraintClause = handler.InterfaceConstraintClauses;

        w.Line($"\t\t/// <summary>Interceptor for {handler.MethodName}.</summary>");
        w.Line($"\t\tpublic sealed class {handler.InterceptorClassName}{ifaceTypeParamList}{ifaceConstraintClause}");
        w.Line("\t\t{");

        // Dictionary for typed handlers
        w.Line($"\t\t\tprivate readonly global::System.Collections.Generic.Dictionary<{handler.KeyType}, object> _typedHandlers = new();");
        w.Line();

        // Of<T>() method
        w.Line($"\t\t\t/// <summary>Gets the typed handler for the specified type argument(s).</summary>");
        w.Line($"\t\t\tpublic {handler.TypedHandlerClassName}<{handler.TypeParameterNames}> Of<{handler.TypeParameterNames}>(){handler.MethodConstraintClauses}");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tvar key = {handler.KeyConstruction};");
        w.Line($"\t\t\t\tif (!_typedHandlers.TryGetValue(key, out var handler))");
        w.Line("\t\t\t\t{");
        w.Line($"\t\t\t\t\thandler = new {handler.TypedHandlerClassName}<{handler.TypeParameterNames}>();");
        w.Line("\t\t\t\t\t_typedHandlers[key] = handler;");
        w.Line("\t\t\t\t}");
        w.Line($"\t\t\t\treturn ({handler.TypedHandlerClassName}<{handler.TypeParameterNames}>)handler;");
        w.Line("\t\t\t}");
        w.Line();

        // Aggregate tracking (private - use Verify for public API)
        w.Line("\t\t\tprivate int TotalCallCount => _typedHandlers.Values.Cast<IGenericMethodCallTracker>().Sum(h => h.CallCount);");
        w.Line();
        w.Line($"\t\t\t/// <summary>All type argument(s) that were used in calls.</summary>");
        w.Line($"\t\t\tpublic global::System.Collections.Generic.IReadOnlyList<{handler.KeyType}> CalledTypeArguments => _typedHandlers.Where(kvp => ((IGenericMethodCallTracker)kvp.Value).CallCount > 0).Select(kvp => kvp.Key).ToList();");
        w.Line();

        // Reset method - clears tracking state but preserves configuration (typed handlers with OnCall)
        w.Line("\t\t\t/// <summary>Resets tracking state (call counts) but preserves configuration (OnCall callbacks).</summary>");
        w.Line("\t\t\tpublic void Reset()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tforeach (var handler in _typedHandlers.Values.Cast<IResettable>())");
        w.Line("\t\t\t\t\thandler.Reset();");
        w.Line("\t\t\t}");
        w.Line();

        // Verify methods
        w.Line("\t\t\t/// <summary>Verifies method was called at least once with any type argument. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify() => Verify(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies total call count satisfies the Times constraint. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!times.Validate(TotalCallCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"{handler.MethodName}\", times, TotalCallCount));");
        w.Line("\t\t\t}");
        w.Line();

        // Internal verification support for stub-level Verify/VerifyAll
        // Generic method handlers aggregate verification from all typed handlers
        w.Line("\t\t\tinternal bool IsVerifiable => false; // Generic handlers are not individually verifiable");
        w.Line("\t\t\tinternal bool IsConfigured => _typedHandlers.Count > 0;");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.Verify() - only checks if marked verifiable.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerification() => null; // Generic methods not individually verifiable");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.VerifyAll() - checks if configured.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerificationAll()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!IsConfigured) return null;");
        w.Line($"\t\t\t\treturn TotalCallCount >= 1 ? null : new global::KnockOff.VerificationFailure(\"{handler.MethodName}\", global::KnockOff.Times.AtLeastOnce, TotalCallCount);");
        w.Line("\t\t\t}");
        w.Line();

        // Nested Typed Handler Class
        RenderTypedHandlerClass(w, handler);

        w.Line("\t\t}");
        w.Line();
    }

    private static void RenderTypedHandlerClass(CodeWriter w, InlineGenericMethodHandlerModel handler)
    {
        w.Line($"\t\t\t/// <summary>Typed handler for {handler.MethodName} with specific type arguments.</summary>");
        w.Line($"\t\t\tpublic sealed class {handler.TypedHandlerClassName}<{handler.TypeParameterNames}> : IGenericMethodCallTracker, IResettable, global::KnockOff.IMethodTracking{handler.MethodConstraintClauses}");
        w.Line("\t\t\t{");

        // Delegate
        w.Line($"\t\t\t\t/// <summary>Delegate for {handler.MethodName}.</summary>");
        w.Line($"\t\t\t\t{handler.DelegateSignature}");
        w.Line();

        // Private callback field
        w.Line($"\t\t\t\tprivate {handler.MethodName}Delegate? _onCall;");
        w.Line();

        // CallCount - private field with explicit interface implementation for aggregation
        w.Line("\t\t\t\tprivate int _callCount;");
        w.Line("\t\t\t\tint IGenericMethodCallTracker.CallCount => _callCount;");
        w.Line();

        // LastArg/LastArgs
        if (handler.LastCallArgType != null)
        {
            var param = handler.NonGenericParameters.GetArray()![0];
            w.Line($"\t\t\t\t/// <summary>The '{param.Name}' argument from the most recent call.</summary>");
            w.Line($"\t\t\t\tpublic {handler.LastCallArgType} LastArg {{ get; private set; }}");
            w.Line();
        }
        else if (handler.LastCallArgsType != null)
        {
            w.Line("\t\t\t\t/// <summary>The arguments from the most recent call.</summary>");
            w.Line($"\t\t\t\tpublic {handler.LastCallArgsType} LastArgs {{ get; private set; }}");
            w.Line();
        }

        // OnCall method (returns IMethodTracking for consistency with regular method interceptors)
        w.Line("\t\t\t\t/// <summary>Sets the callback invoked when this method is called. Returns this handler for tracking.</summary>");
        w.Line($"\t\t\t\tpublic global::KnockOff.IMethodTracking OnCall({handler.MethodName}Delegate callback) {{ _onCall = callback; return this; }}");
        w.Line();

        // Callback property for internal use by invocation logic
        w.Line("\t\t\t\t/// <summary>Gets the configured callback (internal use).</summary>");
        w.Line($"\t\t\t\tinternal {handler.MethodName}Delegate? Callback => _onCall;");
        w.Line();

        // RecordCall
        w.Line("\t\t\t\t/// <summary>Records a method call.</summary>");
        if (handler.NonGenericParameters.Count == 0)
        {
            w.Line("\t\t\t\tpublic void RecordCall() => _callCount++;");
        }
        else if (handler.NonGenericParameters.Count == 1)
        {
            var param = handler.NonGenericParameters.GetArray()![0];
            w.Line($"\t\t\t\tpublic void RecordCall({param.Type} {param.Name}) {{ _callCount++; LastArg = {param.Name}; }}");
        }
        else
        {
            var paramList = string.Join(", ", handler.NonGenericParameters.Select(p => $"{p.Type} {p.Name}"));
            var tupleConstruction = string.Join(", ", handler.NonGenericParameters.Select(p => p.Name));
            w.Line($"\t\t\t\tpublic void RecordCall({paramList}) {{ _callCount++; LastArgs = ({tupleConstruction}); }}");
        }
        w.Line();

        // Reset - clears tracking state but preserves configuration (OnCall callback)
        w.Line("\t\t\t\t/// <summary>Resets tracking state (_callCount, LastArg/LastArgs) but preserves configuration (OnCall).</summary>");
        if (handler.NonGenericParameters.Count == 0)
        {
            w.Line("\t\t\t\tpublic void Reset() { _callCount = 0; }");
        }
        else if (handler.NonGenericParameters.Count == 1)
        {
            w.Line("\t\t\t\tpublic void Reset() { _callCount = 0; LastArg = default; }");
        }
        else
        {
            w.Line("\t\t\t\tpublic void Reset() { _callCount = 0; LastArgs = default; }");
        }
        w.Line();

        // Verify methods - new API throws VerificationException
        w.Line("\t\t\t\t/// <summary>Verifies call count is at least once. Throws VerificationException if not.</summary>");
        w.Line("\t\t\t\tpublic void Verify() => Verify(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t\t/// <summary>Verifies call count satisfies the Times constraint. Throws VerificationException if not.</summary>");
        w.Line("\t\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\tif (!times.Validate(_callCount))");
        w.Line("\t\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"method\", times, _callCount));");
        w.Line("\t\t\t\t}");
        w.Line();

        // Verifiable methods
        w.Line("\t\t\t\t/// <summary>Marks for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
        w.Line("\t\t\t\tpublic global::KnockOff.IMethodTracking Verifiable() => this;");
        w.Line();

        w.Line("\t\t\t\t/// <summary>Marks for verification by Stub.Verify() with Times constraint. Returns this for fluent chaining.</summary>");
        w.Line("\t\t\t\tpublic global::KnockOff.IMethodTracking Verifiable(global::KnockOff.Times times) => this;");

        w.Line("\t\t\t}");
    }

    private static void RenderEventInterceptorClass(CodeWriter w, InlineEventModel evt, string stubClassName)
    {
        var typeParamList = evt.TypeParameterList;
        var constraintClause = evt.ConstraintClauses;

        w.Line($"\t\t/// <summary>Interceptor for {stubClassName}.{evt.EventName} event.</summary>");
        w.Line($"\t\tpublic sealed class {evt.InterceptorClassName}{typeParamList}{constraintClause}");
        w.Line("\t\t{");

        w.Line("\t\t\tprivate int _addCount;");
        w.Line("\t\t\tprivate int _removeCount;");
        w.Line();
        w.Line($"\t\t\t/// <summary>The backing delegate for raising the event.</summary>");
        w.Line($"\t\t\tpublic {evt.DelegateType}? Handler {{ get; private set; }}");
        w.Line();
        w.Line("\t\t\t/// <summary>Records an event subscription.</summary>");
        w.Line($"\t\t\tpublic void RecordAdd({evt.DelegateType}? handler) {{ _addCount++; Handler = ({evt.DelegateType}?)global::System.Delegate.Combine(Handler, handler); }}");
        w.Line();
        w.Line("\t\t\t/// <summary>Records an event unsubscription.</summary>");
        w.Line($"\t\t\tpublic void RecordRemove({evt.DelegateType}? handler) {{ _removeCount++; Handler = ({evt.DelegateType}?)global::System.Delegate.Remove(Handler, handler); }}");
        w.Line();
        w.Line("\t\t\t/// <summary>Resets tracking state (counts, Handler) but preserves verifiable marking.</summary>");
        w.Line("\t\t\tpublic void Reset() { _addCount = 0; _removeCount = 0; Handler = null; }");
        w.Line();

        // Verification API for events
        w.Line("\t\t\tprivate bool _isVerifiable;");
        w.Line("\t\t\tprivate global::KnockOff.Times? _verifiableTimes;");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies the event was subscribed to at least once.</summary>");
        w.Line("\t\t\tpublic void VerifyAdd() => VerifyAdd(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies the event subscription count matches the Times constraint.</summary>");
        w.Line("\t\t\tpublic void VerifyAdd(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!times.Validate(_addCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' add verification failed: expected {{times}}, but was called {{_addCount}} time(s).\");");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies the event was unsubscribed at least once.</summary>");
        w.Line("\t\t\tpublic void VerifyRemove() => VerifyRemove(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies the event unsubscription count matches the Times constraint.</summary>");
        w.Line("\t\t\tpublic void VerifyRemove(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!times.Validate(_removeCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' remove verification failed: expected {{times}}, but was called {{_removeCount}} time(s).\");");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies the event was accessed (add or remove) at least once.</summary>");
        w.Line("\t\t\tpublic void Verify() => Verify(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies the total event access count matches the Times constraint.</summary>");
        w.Line("\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tvar totalCount = _addCount + _removeCount;");
        w.Line("\t\t\t\tif (!times.Validate(totalCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' verification failed: expected {{times}}, but was called {{totalCount}} time(s).\");");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Marks this event for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
        w.Line($"\t\t\tpublic {evt.InterceptorClassName}{typeParamList} Verifiable()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\t_isVerifiable = true;");
        w.Line("\t\t\t\t_verifiableTimes = global::KnockOff.Times.AtLeastOnce;");
        w.Line("\t\t\t\treturn this;");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Marks this event for verification by Stub.Verify() with Times constraint. Returns this for fluent chaining.</summary>");
        w.Line($"\t\t\tpublic {evt.InterceptorClassName}{typeParamList} Verifiable(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\t_isVerifiable = true;");
        w.Line("\t\t\t\t_verifiableTimes = times;");
        w.Line("\t\t\t\treturn this;");
        w.Line("\t\t\t}");
        w.Line();

        // Internal verification methods for stub-level Verify()/VerifyAll()
        w.Line("\t\t\tinternal bool IsVerifiable => _isVerifiable;");
        w.Line("\t\t\tinternal bool IsConfigured => Handler != null;");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.Verify() - only verifiable items.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerification()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!_isVerifiable) return null;");
        w.Line("\t\t\t\tvar times = _verifiableTimes ?? global::KnockOff.Times.AtLeastOnce;");
        w.Line("\t\t\t\tvar totalCount = _addCount + _removeCount;");
        w.Line("\t\t\t\tif (!times.Validate(totalCount))");
        w.Line($"\t\t\t\t\treturn new global::KnockOff.VerificationFailure(\"{evt.EventName}\", times, totalCount);");
        w.Line("\t\t\t\treturn null;");
        w.Line("\t\t\t}");
        w.Line();

        w.Line("\t\t\t/// <summary>Checks verification for Stub.VerifyAll() - all configured items.</summary>");
        w.Line("\t\t\tinternal global::KnockOff.VerificationFailure? CheckVerificationAll()");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!IsConfigured && !_isVerifiable) return null;");
        w.Line("\t\t\t\tvar times = _verifiableTimes ?? global::KnockOff.Times.AtLeastOnce;");
        w.Line("\t\t\t\tvar totalCount = _addCount + _removeCount;");
        w.Line("\t\t\t\tif (!times.Validate(totalCount))");
        w.Line($"\t\t\t\t\treturn new global::KnockOff.VerificationFailure(\"{evt.EventName}\", times, totalCount);");
        w.Line("\t\t\t\treturn null;");
        w.Line("\t\t\t}");

        w.Line("\t\t}");
        w.Line();
    }

    private static void RenderSmartDefaultMethod(CodeWriter w)
    {
        w.Line("\t\t\t/// <summary>Gets a smart default value for a generic type at runtime.</summary>");
        w.Line("\t\t\tprivate static T SmartDefault<T>(string methodName)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tvar type = typeof(T);");
        w.Line();
        w.Line("\t\t\t\t// Value types -> default(T)");
        w.Line("\t\t\t\tif (type.IsValueType)");
        w.Line("\t\t\t\t\treturn default!;");
        w.Line();
        w.Line("\t\t\t\t// Check for parameterless constructor");
        w.Line("\t\t\t\tvar ctor = type.GetConstructor(");
        w.Line("\t\t\t\t\tSystem.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance,");
        w.Line("\t\t\t\t\tnull, System.Type.EmptyTypes, null);");
        w.Line();
        w.Line("\t\t\t\tif (ctor != null)");
        w.Line("\t\t\t\t\treturn (T)ctor.Invoke(null);");
        w.Line();
        w.Line("\t\t\t\tthrow new global::System.InvalidOperationException(");
        w.Line("\t\t\t\t\t$\"No implementation provided for {methodName}<{type.Name}>. \" +");
        w.Line("\t\t\t\t\t$\"Set the handler's OnCall.\");");
        w.Line("\t\t\t}");
        w.Line();
    }

    #endregion

    #region Implementation Rendering

    private static void RenderImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        switch (impl.Kind)
        {
            case InlineMemberKind.Property:
                RenderPropertyImplementation(w, impl);
                break;
            case InlineMemberKind.Indexer:
                RenderIndexerImplementation(w, impl);
                break;
            case InlineMemberKind.Method:
                RenderMethodImplementation(w, impl);
                break;
            case InlineMemberKind.Event:
                RenderEventImplementation(w, impl);
                break;
        }
    }

    private static void RenderPropertyImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        if (impl.DelegationTarget != null)
        {
            // Delegation implementation
            w.Line($"\t\t\t{impl.ReturnType} {impl.InterfaceFullName}.{impl.MemberName}");
            w.Line("\t\t\t{");
            if (impl.HasGetter)
            {
                w.Line($"\t\t\t\tget => (({impl.DelegationTarget.TargetInterfaceFullName})this).{impl.DelegationTarget.TargetMemberName};");
            }
            if (impl.HasSetter)
            {
                w.Line($"\t\t\t\tset => (({impl.DelegationTarget.TargetInterfaceFullName})this).{impl.DelegationTarget.TargetMemberName} = ({impl.DelegationTarget.TargetReturnType})value;");
            }
            w.Line("\t\t\t}");
            w.Line();
            return;
        }

        w.Line($"\t\t\t{impl.ReturnType} {impl.InterfaceFullName}.{impl.MemberName}");
        w.Line("\t\t\t{");

        if (impl.HasGetter)
        {
            if (impl.IsInitOnly)
            {
                // Init-only: use InvokeGet which handles the priority chain
                w.Line($"\t\t\t\tget => {impl.InterceptorName}.InvokeGet(Strict);");
            }
            else
            {
                // Regular: use InvokeGet which handles the priority chain
                w.Line($"\t\t\t\tget => {impl.InterceptorName}.InvokeGet(Strict);");
            }
        }

        if (impl.HasSetter)
        {
            var setterKeyword = impl.IsInitOnly ? "init" : "set";
            if (impl.SetterPragmaDisable != null)
                w.Append(impl.SetterPragmaDisable);
            if (impl.IsInitOnly)
            {
                // Init-only: record and set value via SetValue (no InvokeSet for init accessor)
                w.Line($"\t\t\t\t{setterKeyword} {{ {impl.InterceptorName}.RecordSet(value); {impl.InterceptorName}.SetValue(value); }}");
            }
            else
            {
                // Regular: use InvokeSet which handles the priority chain
                w.Line($"\t\t\t\t{setterKeyword} => {impl.InterceptorName}.InvokeSet(Strict, value);");
            }
            if (impl.SetterPragmaRestore != null)
                w.Line(impl.SetterPragmaRestore);
        }

        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderIndexerImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        w.Line($"\t\t\t{impl.ReturnType} {impl.InterfaceFullName}.this[{impl.ParameterDeclarations}]");
        w.Line("\t\t\t{");

        if (impl.HasGetter)
        {
            // Use InvokeGet which handles the priority chain
            w.Line($"\t\t\t\tget => {impl.InterceptorName}.InvokeGet(Strict, {impl.ArgumentList});");
        }

        if (impl.HasSetter)
        {
            // Use InvokeSet which handles the priority chain
            w.Line($"\t\t\t\tset => {impl.InterceptorName}.InvokeSet(Strict, {impl.ArgumentList}, value);");
        }

        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderMethodImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        if (impl.DelegationTarget != null)
        {
            // Delegation implementation
            var returnKeyword = impl.IsVoid ? "" : "return ";
            w.Line($"\t\t\t{impl.ReturnType} {impl.InterfaceFullName}.{impl.MemberName}({impl.ParameterDeclarations})");
            w.Line("\t\t\t{");
            w.Line($"\t\t\t\t{returnKeyword}(({impl.DelegationTarget.TargetInterfaceFullName})this).{impl.DelegationTarget.TargetMemberName}({impl.DelegationTarget.CastArguments});");
            w.Line("\t\t\t}");
            w.Line();
            return;
        }

        if (impl.IsGenericMethod)
        {
            RenderGenericMethodImplementation(w, impl);
        }
        else
        {
            RenderNonGenericMethodImplementation(w, impl);
        }
    }

    private static void RenderNonGenericMethodImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        w.Line($"\t\t\t{impl.ReturnType} {impl.InterfaceFullName}.{impl.MemberName}({impl.ParameterDeclarations})");
        w.Line("\t\t\t{");

        // Build invoke args (includes Strict, no stub parameter)
        var invokeArgs = string.IsNullOrEmpty(impl.ArgumentList)
            ? "Strict"
            : $"Strict, {impl.ArgumentList}";

        // Call the interceptor's Invoke method (handles out params, tracking, callbacks, strict, defaults)
        if (impl.IsVoid)
            w.Line($"\t\t\t\t{impl.InterceptorName}.Invoke{impl.InvokeSuffix}({invokeArgs});");
        else
            w.Line($"\t\t\t\treturn {impl.InterceptorName}.Invoke{impl.InvokeSuffix}({invokeArgs});");

        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderGenericMethodImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        w.Line($"\t\t\t{impl.ReturnType} {impl.InterfaceFullName}.{impl.MemberName}{impl.TypeParameterDecl}({impl.ParameterDeclarations}){impl.ConstraintClauses}");
        w.Line("\t\t\t{");

        // Initialize out parameters first
        foreach (var outParamInit in impl.OutParameterInitializations)
        {
            w.Line($"\t\t\t\t{outParamInit}");
        }

        // Get the typed handler via Of<T>()
        w.Line($"\t\t\t\tvar typedHandler = {impl.InterceptorName}{impl.OfTypeAccess};");

        // Record the call
        if (string.IsNullOrEmpty(impl.NonGenericArgList))
        {
            w.Line("\t\t\t\ttypedHandler.RecordCall();");
        }
        else
        {
            w.Line($"\t\t\t\ttypedHandler.RecordCall({impl.NonGenericArgList});");
        }

        // Check for Callback
        w.Line($"\t\t\t\tif (typedHandler.Callback is {{ }} onCallCallback)");
        if (impl.IsVoid)
        {
            w.Line($"\t\t\t\t{{ onCallCallback({impl.OnCallArgs}); return; }}");
        }
        else
        {
            w.Line($"\t\t\t\t\treturn onCallCallback({impl.OnCallArgs});");
        }

        // Strict mode check
        w.Line($"\t\t\t\tif (Strict) throw global::KnockOff.StubException.NotConfigured(\"{impl.SimpleInterfaceName}\", \"{impl.MemberName}\");");

        // Default behavior
        if (!impl.IsVoid)
        {
            // Check for Task/ValueTask types
            if (impl.ReturnType == "global::System.Threading.Tasks.Task")
            {
                w.Line("\t\t\t\treturn global::System.Threading.Tasks.Task.CompletedTask;");
            }
            else if (impl.ReturnType == "global::System.Threading.Tasks.ValueTask")
            {
                w.Line("\t\t\t\treturn default;");
            }
            else if (impl.IsNullable)
            {
                w.Line("\t\t\t\treturn default!;");
            }
            else
            {
                w.Line($"\t\t\t\treturn {impl.DefaultExpression};");
            }
        }

        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderEventImplementation(CodeWriter w, InlineInterfaceImplementation impl)
    {
        w.Line($"\t\t\tevent {impl.ReturnType}? {impl.InterfaceFullName}.{impl.MemberName}");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tadd => {impl.InterceptorName}.RecordAdd(value);");
        w.Line($"\t\t\t\tremove => {impl.InterceptorName}.RecordRemove(value);");
        w.Line("\t\t\t}");
        w.Line();
    }

    #endregion

    #region Delegate Stub Rendering

    private static void RenderDelegateStub(CodeWriter w, InlineDelegateStubModel del)
    {
        // Determine if When chain is supported for this delegate
        // Non-void: requires parameters (uses IWhenBuilder + IWhenChain)
        // Void: requires parameters (uses IVoidWhenChain directly)
        var canHaveWhenChain = !del.IsVoid && del.Parameters.Count > 0;
        var canHaveVoidWhenChain = del.IsVoid && del.Parameters.Count > 0;
        var interceptorClassName = del.InterceptorClassName + del.TypeParameterList;

        // Generate handler class first (generic if delegate is open generic)
        w.Line($"\t\t/// <summary>Interceptor for {del.StubClassName} delegate.</summary>");
        w.Line($"\t\tpublic sealed class {del.InterceptorClassName}{del.TypeParameterList}{del.ConstraintClauses}");
        w.Line("\t\t{");

        // CallCount (private - use Verify() API to check call counts)
        w.Line("\t\t\tprivate int _callCount;");
        w.Line();

        // LastArg/LastArgs
        if (del.LastCallArgType != null)
        {
            w.Line($"\t\t\t/// <summary>The argument from the last invocation.</summary>");
            w.Line($"\t\t\tpublic {del.LastCallArgType} LastArg {{ get; private set; }}");
            w.Line();
        }
        else if (del.LastCallArgsType != null)
        {
            w.Line($"\t\t\t/// <summary>The arguments from the last invocation.</summary>");
            w.Line($"\t\t\tpublic {del.LastCallArgsType} LastArgs {{ get; private set; }}");
            w.Line();
        }

        // OnCall callback - internal field and public method (method syntax for API consistency)
        w.Line($"\t\t\tinternal {del.OnCallType}? _onCall;");
        w.Line();
        w.Line($"\t\t\t/// <summary>Configures callback invoked when delegate is called.</summary>");
        w.Line($"\t\t\tpublic void OnCall({del.OnCallType} callback) {{ _onCall = callback; }}");
        w.Line();

        // Returns value overload - wraps value in lambda (non-void delegates only)
        if (!del.IsVoid)
        {
            // Generate underscore parameters to ignore arguments: () => value, (_) => value, (_, _) => value, etc.
            var ignoredParams = del.Parameters.Count == 0
                ? ""
                : string.Join(", ", Enumerable.Range(0, del.Parameters.Count).Select(_ => "_"));
            w.Line($"\t\t\t/// <summary>Configures return value for delegate. Always returns the specified value.</summary>");
            w.Line($"\t\t\tpublic void Returns({del.ReturnType} value) {{ _onCall = ({ignoredParams}) => value; }}");
            w.Line();
        }

        // When chain storage fields (for delegates with parameters)
        // Fields are internal so the stub's Invoke method can access them
        if (canHaveWhenChain)
        {
            w.Line("\t\t\t// When chain storage");
            w.Line("\t\t\tinternal global::System.Collections.Generic.List<WhenMatcher>? _whenChain;");
            w.Line("\t\t\tinternal int _whenChainHead;");
            w.Line("\t\t\tinternal bool _whenVerifiable;");
            w.Line();
        }
        if (canHaveVoidWhenChain)
        {
            w.Line("\t\t\t// When chain storage for void delegate");
            w.Line("\t\t\tinternal global::System.Collections.Generic.List<VoidWhenMatcher>? _whenChain;");
            w.Line("\t\t\tinternal int _whenChainHead;");
            w.Line("\t\t\tinternal bool _whenVerifiable;");
            w.Line();
        }

        // RecordCall method
        if (del.Parameters.Count == 0)
        {
            w.Line("\t\t\tpublic void RecordCall() { _callCount++; }");
        }
        else if (del.Parameters.Count == 1)
        {
            var param = del.Parameters.GetArray()![0];
            w.Line($"\t\t\tpublic void RecordCall({param.Type} {param.Name}) {{ _callCount++; LastArg = {param.Name}; }}");
        }
        else
        {
            var paramList = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var argList = string.Join(", ", del.Parameters.Select(p => p.Name));
            w.Line($"\t\t\tpublic void RecordCall({paramList}) {{ _callCount++; LastArgs = ({argList}); }}");
        }
        w.Line();

        // Reset method - clears tracking state but preserves configuration (OnCall)
        w.Line("\t\t\t/// <summary>Resets tracking state (call count, LastArg/LastArgs) but preserves configuration (OnCall).</summary>");
        w.Append("\t\t\tpublic void Reset() { _callCount = 0; ");
        if (del.LastCallArgType != null)
            w.Append("LastArg = default; ");
        else if (del.LastCallArgsType != null)
            w.Append("LastArgs = default; ");
        if (canHaveWhenChain || canHaveVoidWhenChain)
        {
            w.Append("_whenChainHead = 0; ");
            w.Append("if (_whenChain != null) foreach (var m in _whenChain) m.CallCount = 0; ");
        }
        w.Line("}");
        w.Line();

        // Verify methods
        w.Line("\t\t\t/// <summary>Verifies delegate was invoked at least once. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify() => Verify(global::KnockOff.Times.AtLeastOnce);");
        w.Line();

        w.Line("\t\t\t/// <summary>Verifies call count satisfies the Times constraint. Throws VerificationException if not.</summary>");
        w.Line("\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\tif (!times.Validate(_callCount))");
        w.Line($"\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"delegate\", times, _callCount));");
        w.Line("\t\t\t}");
        w.Line();

        // When() entry points (for delegates with parameters)
        if (canHaveWhenChain)
        {
            RenderDelegateWhenEntryPoints(w, del);
        }
        if (canHaveVoidWhenChain)
        {
            RenderVoidDelegateWhenEntryPoints(w, del);
        }

        // When matcher/builder/chain nested classes (for delegates with parameters)
        if (canHaveWhenChain)
        {
            RenderDelegateWhenMatcherClasses(w, del);
            RenderDelegateWhenBuilderImpl(w, del);
            RenderDelegateWhenChainImpl(w, del);
        }
        if (canHaveVoidWhenChain)
        {
            RenderVoidDelegateWhenMatcherClasses(w, del);
            RenderVoidDelegateWhenChainImpl(w, del);
        }

        w.Line("\t\t}");
        w.Line();

        // Generate stub class
        w.Line($"\t\t/// <summary>Stub for {del.DelegateType} delegate.</summary>");
        w.Line($"\t\tpublic sealed class {del.StubClassName}{del.TypeParameterList} : global::KnockOff.IKnockOffStub{del.ConstraintClauses}");
        w.Line("\t\t{");

        // Strict property
        w.Line("\t\t\t/// <summary>When true, unconfigured method calls throw StubException instead of returning default. Not yet implemented for delegate stubs.</summary>");
        w.Line("\t\t\tpublic bool Strict { get; set; }");
        w.Line();

        // Interceptor property (generic if delegate is open generic)
        w.Line($"\t\t\t/// <summary>Interceptor for tracking and configuring delegate behavior.</summary>");
        w.Line($"\t\t\tpublic {del.InterceptorClassName}{del.TypeParameterList} Interceptor {{ get; }} = new();");
        w.Line();

        // Private Invoke method with When chain support
        w.Line($"\t\t\tprivate {del.ReturnType} Invoke({del.InvokeParameterDeclarations})");
        w.Line("\t\t\t{");
        if (del.Parameters.Count > 0)
        {
            w.Line($"\t\t\t\tInterceptor.RecordCall({del.InvokeArgumentList});");
        }
        else
        {
            w.Line("\t\t\t\tInterceptor.RecordCall();");
        }

        // When chain check (for non-void delegates with parameters)
        if (canHaveWhenChain)
        {
            w.Line();
            w.Line("\t\t\t\t// When chain - check HEAD matcher first (highest priority)");
            w.Line("\t\t\t\tif (Interceptor._whenChain != null && Interceptor._whenChainHead < Interceptor._whenChain.Count)");
            w.Line("\t\t\t\t{");
            w.Line("\t\t\t\t\tvar matcher = Interceptor._whenChain[Interceptor._whenChainHead];");
            w.Line($"\t\t\t\t\tif (matcher.Matches({del.InvokeArgumentList}))");
            w.Line("\t\t\t\t\t{");
            w.Line("\t\t\t\t\t\tmatcher.CallCount++;");
            w.Line("\t\t\t\t\t\t// Advance HEAD unless at last matcher (which repeats)");
            w.Line("\t\t\t\t\t\tif (Interceptor._whenChainHead < Interceptor._whenChain.Count - 1)");
            w.Line("\t\t\t\t\t\t\tInterceptor._whenChainHead++;");
            w.Line($"\t\t\t\t\t\treturn matcher.Execute({del.InvokeArgumentList});");
            w.Line("\t\t\t\t\t}");
            w.Line("\t\t\t\t\telse if (matcher.IsTerminal)");
            w.Line("\t\t\t\t\t{");
            w.Line("\t\t\t\t\t\t// ThenNone: didn't match (always false), exhaust by advancing");
            w.Line("\t\t\t\t\t\tInterceptor._whenChainHead++;");
            w.Line("\t\t\t\t\t}");
            w.Line("\t\t\t\t}");
        }

        // When chain check (for void delegates with parameters)
        if (canHaveVoidWhenChain)
        {
            w.Line();
            w.Line("\t\t\t\t// When chain - check HEAD matcher first (highest priority)");
            w.Line("\t\t\t\tif (Interceptor._whenChain != null && Interceptor._whenChainHead < Interceptor._whenChain.Count)");
            w.Line("\t\t\t\t{");
            w.Line("\t\t\t\t\tvar matcher = Interceptor._whenChain[Interceptor._whenChainHead];");
            w.Line($"\t\t\t\t\tif (matcher.Matches({del.InvokeArgumentList}))");
            w.Line("\t\t\t\t\t{");
            w.Line("\t\t\t\t\t\tmatcher.CallCount++;");
            w.Line("\t\t\t\t\t\t// Advance HEAD unless at last matcher (which repeats)");
            w.Line("\t\t\t\t\t\tif (Interceptor._whenChainHead < Interceptor._whenChain.Count - 1)");
            w.Line("\t\t\t\t\t\t\tInterceptor._whenChainHead++;");
            w.Line($"\t\t\t\t\t\tmatcher.Execute({del.InvokeArgumentList});");
            w.Line("\t\t\t\t\t\treturn;");
            w.Line("\t\t\t\t\t}");
            w.Line("\t\t\t\t\telse if (matcher.IsTerminal)");
            w.Line("\t\t\t\t\t{");
            w.Line("\t\t\t\t\t\t// ThenNone: didn't match (always false), exhaust by advancing");
            w.Line("\t\t\t\t\t\tInterceptor._whenChainHead++;");
            w.Line("\t\t\t\t\t}");
            w.Line("\t\t\t\t}");
        }

        if (del.IsVoid)
        {
            var onCallArgs = del.InvokeArgumentList;
            w.Line($"\t\t\t\tif (Interceptor._onCall is {{ }} onCall) onCall({onCallArgs});");
        }
        else
        {
            var onCallArgs = del.InvokeArgumentList;
            w.Line($"\t\t\t\tif (Interceptor._onCall is {{ }} onCall) return onCall({onCallArgs});");
            w.Line($"\t\t\t\treturn {del.DefaultExpression};");
        }
        w.Line("\t\t\t}");
        w.Line();

        // Implicit conversion operator
        w.Line($"\t\t\t/// <summary>Implicit conversion to {del.DelegateType}.</summary>");
        w.Line($"\t\t\tpublic static implicit operator {del.DelegateType}({del.StubClassName}{del.TypeParameterList} stub) => stub.Invoke;");

        w.Line("\t\t}");
        w.Line();
    }

    private static void RenderDelegateWhenEntryPoints(CodeWriter w, InlineDelegateStubModel del)
    {
        var predicateType = BuildDelegatePredicateType(del.Parameters);
        var paramTypeList = BuildDelegateParamTypeList(del.Parameters);
        var interceptorClassName = del.InterceptorClassName + del.TypeParameterList;

        // When() value overload - returns concrete type for fluent chaining
        w.Line($"\t\t\t/// <summary>Configures parameter-specific matching with exact values. Returns builder for Returns().</summary>");
        w.Line($"\t\t\tpublic WhenBuilder When({paramTypeList})");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\t_whenChain ??= new global::System.Collections.Generic.List<WhenMatcher>();");
        var lambdaParams = BuildDelegateLambdaParams(del.Parameters);
        var predicateBody = BuildDelegatePredicateBody(del.Parameters);
        w.Line($"\t\t\t\treturn new WhenBuilder(this, ({lambdaParams}) => {predicateBody});");
        w.Line("\t\t\t}");
        w.Line();

        // When() predicate overload - returns concrete type for fluent chaining
        w.Line($"\t\t\t/// <summary>Configures parameter-specific matching with predicate. Returns builder for Returns().</summary>");
        w.Line($"\t\t\tpublic WhenBuilder When({predicateType} predicate)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\t_whenChain ??= new global::System.Collections.Generic.List<WhenMatcher>();");
        w.Line("\t\t\t\treturn new WhenBuilder(this, predicate);");
        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderDelegateWhenMatcherClasses(CodeWriter w, InlineDelegateStubModel del)
    {
        var matchParams = BuildDelegateMatchParams(del.Parameters);
        var callbackArgs = BuildDelegateCallbackArgs(del.Parameters);
        var predicateType = BuildDelegatePredicateType(del.Parameters);

        // WhenMatcher abstract base (internal for access from stub class)
        w.Line($"\t\t\t/// <summary>Abstract base for When chain matchers.</summary>");
        w.Line($"\t\t\tinternal abstract class WhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tpublic abstract bool Matches({matchParams});");
        w.Line($"\t\t\t\tpublic abstract {del.ReturnType} Execute({matchParams});");
        w.Line("\t\t\t\tpublic abstract bool IsTerminal { get; }");
        w.Line("\t\t\t\tpublic int CallCount { get; set; }");
        w.Line("\t\t\t}");
        w.Line();

        // WhenMatcherValue
        w.Line($"\t\t\t/// <summary>Matcher with predicate and value.</summary>");
        w.Line($"\t\t\tinternal sealed class WhenMatcherValue : WhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {predicateType} _predicate;");
        w.Line($"\t\t\t\tprivate readonly {del.ReturnType} _value;");
        w.Line($"\t\t\t\tpublic WhenMatcherValue({predicateType} predicate, {del.ReturnType} value) {{ _predicate = predicate; _value = value; }}");
        w.Line($"\t\t\t\tpublic override bool Matches({matchParams}) => _predicate({callbackArgs});");
        w.Line($"\t\t\t\tpublic override {del.ReturnType} Execute({matchParams}) => _value;");
        w.Line("\t\t\t\tpublic override bool IsTerminal => false;");
        w.Line("\t\t\t}");
        w.Line();

        // WhenMatcherCall
        w.Line($"\t\t\t/// <summary>Matcher that always matches and invokes callback. Terminal.</summary>");
        w.Line($"\t\t\tinternal sealed class WhenMatcherCall : WhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {del.OnCallType} _callback;");
        w.Line($"\t\t\t\tpublic WhenMatcherCall({del.OnCallType} callback) => _callback = callback;");
        w.Line($"\t\t\t\tpublic override bool Matches({matchParams}) => true;");
        w.Line($"\t\t\t\tpublic override {del.ReturnType} Execute({matchParams}) => _callback({callbackArgs});");
        w.Line("\t\t\t\tpublic override bool IsTerminal => true;");
        w.Line("\t\t\t}");
        w.Line();

        // WhenMatcherNone
        w.Line($"\t\t\t/// <summary>Matcher that never matches. Terminal.</summary>");
        w.Line($"\t\t\tinternal sealed class WhenMatcherNone : WhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tpublic override bool Matches({matchParams}) => false;");
        w.Line($"\t\t\t\tpublic override {del.ReturnType} Execute({matchParams}) => default!;");
        w.Line("\t\t\t\tpublic override bool IsTerminal => true;");
        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderDelegateWhenBuilderImpl(CodeWriter w, InlineDelegateStubModel del)
    {
        var predicateType = BuildDelegatePredicateType(del.Parameters);
        var interceptorClassName = del.InterceptorClassName + del.TypeParameterList;

        // Check if this is an async delegate (Task<T> or ValueTask<T>)
        var (innerType, isTaskT, isValueTaskT) = GetAsyncTypeInfo(del.ReturnType);
        var isAsync = isTaskT || isValueTaskT;

        w.Line($"\t\t\t/// <summary>Builder for When matchers.</summary>");
        w.Line($"\t\t\tpublic sealed class WhenBuilder : global::KnockOff.IWhenBuilder<{del.OnCallType}, {del.ReturnType}>");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {interceptorClassName} _interceptor;");
        w.Line($"\t\t\t\tprivate readonly {predicateType} _predicate;");
        w.Line($"\t\t\t\tpublic WhenBuilder({interceptorClassName} interceptor, {predicateType} predicate) {{ _interceptor = interceptor; _predicate = predicate; }}");

        // For async delegates, generate Returns(TInner) that auto-wraps
        if (isAsync)
        {
            w.Line($"\t\t\t\t/// <summary>Configures the return value. Auto-wrapped in {(isTaskT ? "Task.FromResult" : "new ValueTask")}.</summary>");
            w.Line($"\t\t\t\tpublic WhenChain Returns({innerType} value)");
            w.Line("\t\t\t\t{");
            w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<WhenMatcher>();");
            if (isTaskT)
                w.Line("\t\t\t\t\t_interceptor._whenChain.Add(new WhenMatcherValue(_predicate, global::System.Threading.Tasks.Task.FromResult(value)));");
            else
                w.Line($"\t\t\t\t\t_interceptor._whenChain.Add(new WhenMatcherValue(_predicate, new global::System.Threading.Tasks.ValueTask<{innerType}>(value)));");
            w.Line("\t\t\t\t\treturn new WhenChain(_interceptor);");
            w.Line("\t\t\t\t}");
            w.Line();
            // Explicit interface implementation wraps too
            if (isTaskT)
                w.Line($"\t\t\t\tglobal::KnockOff.IWhenChain<{del.OnCallType}, {del.ReturnType}> global::KnockOff.IWhenBuilder<{del.OnCallType}, {del.ReturnType}>.Returns({del.ReturnType} value) => Returns(value.Result);");
            else
                w.Line($"\t\t\t\tglobal::KnockOff.IWhenChain<{del.OnCallType}, {del.ReturnType}> global::KnockOff.IWhenBuilder<{del.OnCallType}, {del.ReturnType}>.Returns({del.ReturnType} value) => Returns(value.Result);");
        }
        else
        {
            w.Line($"\t\t\t\tpublic WhenChain Returns({del.ReturnType} value)");
            w.Line("\t\t\t\t{");
            w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<WhenMatcher>();");
            w.Line("\t\t\t\t\t_interceptor._whenChain.Add(new WhenMatcherValue(_predicate, value));");
            w.Line("\t\t\t\t\treturn new WhenChain(_interceptor);");
            w.Line("\t\t\t\t}");
            w.Line();
            // Explicit interface implementation for IWhenBuilder.Returns
            w.Line($"\t\t\t\tglobal::KnockOff.IWhenChain<{del.OnCallType}, {del.ReturnType}> global::KnockOff.IWhenBuilder<{del.OnCallType}, {del.ReturnType}>.Returns({del.ReturnType} value) => Returns(value);");
        }
        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderDelegateWhenChainImpl(CodeWriter w, InlineDelegateStubModel del)
    {
        var predicateType = BuildDelegatePredicateType(del.Parameters);
        var paramTypeList = BuildDelegateParamTypeList(del.Parameters);
        var interceptorClassName = del.InterceptorClassName + del.TypeParameterList;

        w.Line($"\t\t\t/// <summary>When chain implementation.</summary>");
        w.Line($"\t\t\tpublic sealed class WhenChain : global::KnockOff.IWhenChain<{del.OnCallType}, {del.ReturnType}>");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {interceptorClassName} _interceptor;");
        w.Line($"\t\t\t\tpublic WhenChain({interceptorClassName} interceptor) => _interceptor = interceptor;");
        w.Line();

        // ThenWhen value overload
        w.Line($"\t\t\t\tpublic WhenBuilder ThenWhen({paramTypeList})");
        w.Line("\t\t\t\t{");
        var lambdaParams = BuildDelegateLambdaParams(del.Parameters);
        var predicateBody = BuildDelegatePredicateBody(del.Parameters);
        w.Line($"\t\t\t\t\treturn new WhenBuilder(_interceptor, ({lambdaParams}) => {predicateBody});");
        w.Line("\t\t\t\t}");
        w.Line();

        // ThenWhen predicate overload
        w.Line($"\t\t\t\tpublic WhenBuilder ThenWhen({predicateType} predicate)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\treturn new WhenBuilder(_interceptor, predicate);");
        w.Line("\t\t\t\t}");
        w.Line();

        // ThenCall
        w.Line($"\t\t\t\tpublic global::KnockOff.IWhenTracking ThenCall({del.OnCallType} callback)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<WhenMatcher>();");
        w.Line("\t\t\t\t\t_interceptor._whenChain.Add(new WhenMatcherCall(callback));");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();

        // ThenNone
        w.Line("\t\t\t\tpublic global::KnockOff.IWhenTracking ThenNone()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<WhenMatcher>();");
        w.Line("\t\t\t\t\t_interceptor._whenChain.Add(new WhenMatcherNone());");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();

        // Verify
        w.Line("\t\t\t\tpublic void Verify()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\tif (_interceptor._whenChain == null || _interceptor._whenChain.Count == 0) return;");
        w.Line("\t\t\t\t\tvar head = _interceptor._whenChainHead;");
        w.Line("\t\t\t\t\tvar count = _interceptor._whenChain.Count;");
        w.Line("\t\t\t\t\tif (head < count && !_interceptor._whenChain[head].IsTerminal && _interceptor._whenChain[head].CallCount == 0)");
        w.Line("\t\t\t\t\t\tthrow new global::KnockOff.VerificationException(global::KnockOff.VerificationFailure.SequenceIncomplete(\"When chain\", count, head));");
        w.Line("\t\t\t\t}");
        w.Line();

        // Reset
        w.Line("\t\t\t\tpublic void Reset()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChainHead = 0;");
        w.Line("\t\t\t\t\tif (_interceptor._whenChain != null)");
        w.Line("\t\t\t\t\t\tforeach (var m in _interceptor._whenChain)");
        w.Line("\t\t\t\t\t\t\tm.CallCount = 0;");
        w.Line("\t\t\t\t}");
        w.Line();

        // Verifiable
        w.Line($"\t\t\t\tpublic WhenChain Verifiable()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenVerifiable = true;");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();

        // Explicit interface implementations
        w.Line($"\t\t\t\tglobal::KnockOff.IWhenChain<{del.OnCallType}, {del.ReturnType}> global::KnockOff.IWhenChain<{del.OnCallType}, {del.ReturnType}>.Verifiable() => Verifiable();");
        w.Line("\t\t\t\tglobal::KnockOff.IWhenTracking global::KnockOff.IWhenTracking.Verifiable() => Verifiable();");

        w.Line("\t\t\t}");
        w.Line();
    }

    private static string BuildDelegatePredicateType(EquatableArray<ParameterModel> parameters)
    {
        if (parameters.Count == 0)
            return "global::System.Func<bool>";
        var paramTypes = string.Join(", ", parameters.Select(p => p.Type));
        return $"global::System.Func<{paramTypes}, bool>";
    }

    private static string BuildDelegateParamTypeList(EquatableArray<ParameterModel> parameters)
    {
        if (parameters.Count == 0) return "";
        return string.Join(", ", parameters.Select(p => $"{p.Type} {p.Name}"));
    }

    private static string BuildDelegateMatchParams(EquatableArray<ParameterModel> parameters)
    {
        if (parameters.Count == 0) return "";
        return string.Join(", ", parameters.Select(p => $"{p.Type} {p.Name}"));
    }

    private static string BuildDelegateCallbackArgs(EquatableArray<ParameterModel> parameters)
    {
        if (parameters.Count == 0) return "";
        return string.Join(", ", parameters.Select(p => p.Name));
    }

    private static string BuildDelegateLambdaParams(EquatableArray<ParameterModel> parameters)
    {
        if (parameters.Count == 0) return "";
        return string.Join(", ", Enumerable.Range(0, parameters.Count).Select(i => $"_arg{i}"));
    }

    private static string BuildDelegatePredicateBody(EquatableArray<ParameterModel> parameters)
    {
        if (parameters.Count == 0) return "true";
        var parts = new List<string>();
        for (int i = 0; i < parameters.Count; i++)
        {
            parts.Add($"global::System.Object.Equals(_arg{i}, {parameters.GetArray()![i].Name})");
        }
        return string.Join(" && ", parts);
    }

    /// <summary>
    /// Analyzes a return type for async patterns and extracts the inner type.
    /// </summary>
    private static (string InnerType, bool IsTaskT, bool IsValueTaskT) GetAsyncTypeInfo(string returnType)
    {
        const string TaskPrefix = "global::System.Threading.Tasks.Task<";
        const string ValueTaskPrefix = "global::System.Threading.Tasks.ValueTask<";

        if (returnType.StartsWith(TaskPrefix) && returnType.EndsWith(">"))
        {
            var innerType = returnType.Substring(TaskPrefix.Length, returnType.Length - TaskPrefix.Length - 1);
            return (innerType, true, false);
        }

        if (returnType.StartsWith(ValueTaskPrefix) && returnType.EndsWith(">"))
        {
            var innerType = returnType.Substring(ValueTaskPrefix.Length, returnType.Length - ValueTaskPrefix.Length - 1);
            return (innerType, false, true);
        }

        return (returnType, false, false);
    }

    // Void delegate When chain methods

    private static void RenderVoidDelegateWhenEntryPoints(CodeWriter w, InlineDelegateStubModel del)
    {
        var predicateType = BuildDelegatePredicateType(del.Parameters);
        var paramTypeList = BuildDelegateParamTypeList(del.Parameters);
        var interceptorClassName = del.InterceptorClassName + del.TypeParameterList;

        // When() value overload - returns concrete type to enable fluent ThenWhen chaining
        w.Line($"\t\t\t/// <summary>Configures parameter-specific matching with exact values for void delegate. Returns chain directly.</summary>");
        w.Line("\t\t\tpublic VoidWhenChain When(" + paramTypeList + ")");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\t_whenChain ??= new global::System.Collections.Generic.List<VoidWhenMatcher>();");
        var lambdaParams = BuildDelegateLambdaParams(del.Parameters);
        var predicateBody = BuildDelegatePredicateBody(del.Parameters);
        w.Line($"\t\t\t\tvar matcher = new VoidWhenMatcherPredicate(({lambdaParams}) => {predicateBody});");
        w.Line("\t\t\t\t_whenChain.Add(matcher);");
        w.Line("\t\t\t\treturn new VoidWhenChain(this, matcher);");
        w.Line("\t\t\t}");
        w.Line();

        // When() predicate overload - returns concrete type to enable fluent ThenWhen chaining
        w.Line($"\t\t\t/// <summary>Configures parameter-specific matching with predicate for void delegate. Returns chain directly.</summary>");
        w.Line("\t\t\tpublic VoidWhenChain When(" + predicateType + " predicate)");
        w.Line("\t\t\t{");
        w.Line("\t\t\t\t_whenChain ??= new global::System.Collections.Generic.List<VoidWhenMatcher>();");
        w.Line("\t\t\t\tvar matcher = new VoidWhenMatcherPredicate(predicate);");
        w.Line("\t\t\t\t_whenChain.Add(matcher);");
        w.Line("\t\t\t\treturn new VoidWhenChain(this, matcher);");
        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderVoidDelegateWhenMatcherClasses(CodeWriter w, InlineDelegateStubModel del)
    {
        var matchParams = BuildDelegateMatchParams(del.Parameters);
        var callbackArgs = BuildDelegateCallbackArgs(del.Parameters);
        var predicateType = BuildDelegatePredicateType(del.Parameters);

        // VoidWhenMatcher abstract base (internal for access from stub class)
        w.Line($"\t\t\t/// <summary>Abstract base for void When chain matchers.</summary>");
        w.Line($"\t\t\tinternal abstract class VoidWhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tpublic abstract bool Matches({matchParams});");
        w.Line($"\t\t\t\tpublic abstract void Execute({matchParams});");
        w.Line("\t\t\t\tpublic abstract bool IsTerminal { get; }");
        w.Line("\t\t\t\tpublic int CallCount { get; set; }");
        w.Line($"\t\t\t\tpublic {del.OnCallType}? Callback {{ get; set; }}");
        w.Line("\t\t\t}");
        w.Line();

        // VoidWhenMatcherPredicate
        w.Line($"\t\t\t/// <summary>Matcher with predicate and optional callback.</summary>");
        w.Line($"\t\t\tinternal sealed class VoidWhenMatcherPredicate : VoidWhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {predicateType} _predicate;");
        w.Line($"\t\t\t\tpublic VoidWhenMatcherPredicate({predicateType} predicate) => _predicate = predicate;");
        w.Line($"\t\t\t\tpublic override bool Matches({matchParams}) => _predicate({callbackArgs});");
        w.Line($"\t\t\t\tpublic override void Execute({matchParams}) {{ Callback?.Invoke({callbackArgs}); }}");
        w.Line("\t\t\t\tpublic override bool IsTerminal => false;");
        w.Line("\t\t\t}");
        w.Line();

        // VoidWhenMatcherCall
        w.Line($"\t\t\t/// <summary>Matcher that always matches and invokes callback. Terminal.</summary>");
        w.Line($"\t\t\tinternal sealed class VoidWhenMatcherCall : VoidWhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {del.OnCallType} _callback;");
        w.Line($"\t\t\t\tpublic VoidWhenMatcherCall({del.OnCallType} callback) => _callback = callback;");
        w.Line($"\t\t\t\tpublic override bool Matches({matchParams}) => true;");
        w.Line($"\t\t\t\tpublic override void Execute({matchParams}) => _callback({callbackArgs});");
        w.Line("\t\t\t\tpublic override bool IsTerminal => true;");
        w.Line("\t\t\t}");
        w.Line();

        // VoidWhenMatcherNone
        w.Line($"\t\t\t/// <summary>Matcher that never matches. Terminal.</summary>");
        w.Line($"\t\t\tinternal sealed class VoidWhenMatcherNone : VoidWhenMatcher");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tpublic override bool Matches({matchParams}) => false;");
        w.Line($"\t\t\t\tpublic override void Execute({matchParams}) {{ }}");
        w.Line("\t\t\t\tpublic override bool IsTerminal => true;");
        w.Line("\t\t\t}");
        w.Line();
    }

    private static void RenderVoidDelegateWhenChainImpl(CodeWriter w, InlineDelegateStubModel del)
    {
        var predicateType = BuildDelegatePredicateType(del.Parameters);
        var paramTypeList = BuildDelegateParamTypeList(del.Parameters);
        var interceptorClassName = del.InterceptorClassName + del.TypeParameterList;

        w.Line($"\t\t\t/// <summary>Void When chain implementation.</summary>");
        w.Line($"\t\t\tpublic sealed class VoidWhenChain : global::KnockOff.IVoidWhenChain<{del.OnCallType}>");
        w.Line("\t\t\t{");
        w.Line($"\t\t\t\tprivate readonly {interceptorClassName} _interceptor;");
        w.Line("\t\t\t\tprivate readonly VoidWhenMatcher _currentMatcher;");
        w.Line($"\t\t\t\tinternal VoidWhenChain({interceptorClassName} interceptor, VoidWhenMatcher currentMatcher) {{ _interceptor = interceptor; _currentMatcher = currentMatcher; }}");
        w.Line();

        // Call - sets optional callback on current matcher
        // Returns concrete type to enable fluent ThenWhen chaining
        w.Line("\t\t\t\tpublic VoidWhenChain Call(" + del.OnCallType + " callback)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_currentMatcher.Callback = callback;");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();
        // Explicit interface implementation for IVoidWhenChain.Call
        w.Line($"\t\t\t\tglobal::KnockOff.IVoidWhenChain<{del.OnCallType}> global::KnockOff.IVoidWhenChain<{del.OnCallType}>.Call({del.OnCallType} callback) => Call(callback);");
        w.Line();

        // ThenWhen value overload - returns concrete type for chaining
        w.Line("\t\t\t\tpublic VoidWhenChain ThenWhen(" + paramTypeList + ")");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<VoidWhenMatcher>();");
        var lambdaParams = BuildDelegateLambdaParams(del.Parameters);
        var predicateBody = BuildDelegatePredicateBody(del.Parameters);
        w.Line($"\t\t\t\t\tvar matcher = new VoidWhenMatcherPredicate(({lambdaParams}) => {predicateBody});");
        w.Line("\t\t\t\t\t_interceptor._whenChain.Add(matcher);");
        w.Line("\t\t\t\t\treturn new VoidWhenChain(_interceptor, matcher);");
        w.Line("\t\t\t\t}");
        w.Line();

        // ThenWhen predicate overload - returns concrete type for chaining
        w.Line("\t\t\t\tpublic VoidWhenChain ThenWhen(" + predicateType + " predicate)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<VoidWhenMatcher>();");
        w.Line("\t\t\t\t\tvar matcher = new VoidWhenMatcherPredicate(predicate);");
        w.Line("\t\t\t\t\t_interceptor._whenChain.Add(matcher);");
        w.Line("\t\t\t\t\treturn new VoidWhenChain(_interceptor, matcher);");
        w.Line("\t\t\t\t}");
        w.Line();

        // ThenCall
        w.Line($"\t\t\t\tpublic global::KnockOff.IWhenTracking ThenCall({del.OnCallType} callback)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<VoidWhenMatcher>();");
        w.Line("\t\t\t\t\t_interceptor._whenChain.Add(new VoidWhenMatcherCall(callback));");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();

        // ThenNone
        w.Line("\t\t\t\tpublic global::KnockOff.IWhenTracking ThenNone()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChain ??= new global::System.Collections.Generic.List<VoidWhenMatcher>();");
        w.Line("\t\t\t\t\t_interceptor._whenChain.Add(new VoidWhenMatcherNone());");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();

        // Verify() - from ITracking
        w.Line("\t\t\t\tpublic void Verify()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\tif (_interceptor._whenChain == null || _interceptor._whenChain.Count == 0) return;");
        w.Line("\t\t\t\t\tvar head = _interceptor._whenChainHead;");
        w.Line("\t\t\t\t\tvar count = _interceptor._whenChain.Count;");
        w.Line("\t\t\t\t\tif (head < count && !_interceptor._whenChain[head].IsTerminal && _interceptor._whenChain[head].CallCount == 0)");
        w.Line("\t\t\t\t\t\tthrow new global::KnockOff.VerificationException(global::KnockOff.VerificationFailure.SequenceIncomplete(\"When chain\", count, head));");
        w.Line("\t\t\t\t}");
        w.Line();

        // Verify(Times) - parameter-specific verification
        w.Line("\t\t\t\tpublic void Verify(global::KnockOff.Times times)");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\tif (!times.Validate(_currentMatcher.CallCount))");
        w.Line("\t\t\t\t\t\tthrow new global::KnockOff.VerificationException(new global::KnockOff.VerificationFailure(\"When matcher\", times, _currentMatcher.CallCount));");
        w.Line("\t\t\t\t}");
        w.Line();

        // Reset
        w.Line("\t\t\t\tpublic void Reset()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenChainHead = 0;");
        w.Line("\t\t\t\t\tif (_interceptor._whenChain != null)");
        w.Line("\t\t\t\t\t\tforeach (var m in _interceptor._whenChain)");
        w.Line("\t\t\t\t\t\t\tm.CallCount = 0;");
        w.Line("\t\t\t\t}");
        w.Line();

        // Verifiable - returns concrete type for chaining
        w.Line("\t\t\t\tpublic VoidWhenChain Verifiable()");
        w.Line("\t\t\t\t{");
        w.Line("\t\t\t\t\t_interceptor._whenVerifiable = true;");
        w.Line("\t\t\t\t\treturn this;");
        w.Line("\t\t\t\t}");
        w.Line();

        // Explicit interface implementations
        w.Line($"\t\t\t\tglobal::KnockOff.IVoidWhenChain<{del.OnCallType}> global::KnockOff.IVoidWhenChain<{del.OnCallType}>.Verifiable() => Verifiable();");
        w.Line("\t\t\t\tglobal::KnockOff.IWhenTracking global::KnockOff.IWhenTracking.Verifiable() => Verifiable();");

        w.Line("\t\t\t}");
        w.Line();
    }

    #endregion

    #region Class Stub Rendering

    private static void RenderClassStub(CodeWriter w, InlineClassStubModel cls)
    {
        // Delegate to ClassRenderer for full rendering
        ClassRenderer.Render(w, cls, baseIndent: 2);
    }

    #endregion

    #region Partial Property Rendering

    private static void RenderPartialProperty(CodeWriter w, InlinePartialPropertyModel prop)
    {
        var accessMod = string.IsNullOrEmpty(prop.AccessModifier) ? "" : $"{prop.AccessModifier} ";

        w.Line();
        w.Line($"\tprivate readonly Stubs.{prop.StubTypeName} {prop.BackingFieldName} = new();");
        w.Line($"\t/// <summary>Auto-instantiated stub for {prop.StubTypeName}.</summary>");
        w.Line($"\t{accessMod}partial Stubs.{prop.StubTypeName} {prop.PropertyName} {{ get => {prop.BackingFieldName}; }}");
    }

    #endregion

    #region Source Methods Rendering

    private static void RenderSourceMethods(CodeWriter w, InlineInterfaceStubModel iface)
    {
        // Skip if no source providers
        if (iface.SourceProviders.Count == 0)
            return;

        foreach (var provider in iface.SourceProviders)
        {
            w.Line($"\t\t\t/// <summary>Sets the source object for {provider.InterfaceType} delegation.</summary>");
            w.Line($"\t\t\tpublic void {provider.MethodName}({provider.InterfaceType}? source)");
            w.Line("\t\t\t{");

            foreach (var mapping in provider.MemberMappings)
            {
                if (mapping.SetSource)
                {
                    w.Line($"\t\t\t\t{mapping.InterceptorName}._source = source;");
                }
                else
                {
                    w.Line($"\t\t\t\t{mapping.InterceptorName}._source = null;");
                }
            }

            w.Line("\t\t\t}");
            w.Line();
        }
    }

    #endregion

    #region Helper Methods

    private static string FormatTypeParameterList(EquatableArray<TypeParameterModel> typeParameters)
    {
        if (typeParameters.Count == 0)
            return "";

        var names = string.Join(", ", typeParameters.Select(tp => tp.Name));
        return $"<{names}>";
    }

    private static string FormatConstraints(EquatableArray<TypeParameterModel> typeParameters)
    {
        if (typeParameters.Count == 0)
            return "";

        var clauses = typeParameters
            .Where(tp => !string.IsNullOrEmpty(tp.Constraints))
            .Select(tp => $" where {tp.Name} : {tp.Constraints}");

        return string.Join("", clauses);
    }

    #endregion
}
