// src/Generator/Renderer/StandaloneClassRenderer.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using KnockOff;
using KnockOff.Builder;
using KnockOff.Model.Inline;
using KnockOff.Model.Shared;
using KnockOff.Model.StandaloneClass;
using KnockOff.Renderer.Shared;

namespace KnockOff.Renderer;

/// <summary>
/// Renders StandaloneClassGenerationUnit to source code.
/// Follows the same wrapper + nested Impl pattern as ClassRenderer,
/// but generates a partial class completion for the user's class (not nested in Stubs).
/// </summary>
internal static class StandaloneClassRenderer
{
    public static string Render(StandaloneClassGenerationUnit unit)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable SYSLIB0050 // Obsolete serialization API");
        w.Line();

        // Always include System.Linq - needed for .Sum() in overload TotalCallCount
        w.Line("using System.Linq;");
        w.Line();

        // Namespace
        if (!string.IsNullOrEmpty(unit.Namespace))
        {
            w.Line($"namespace {unit.Namespace};");
            w.Line();
        }

        // Open containing type wrappers for nested classes
        foreach (var containingType in unit.ContainingTypes)
        {
            var accessMod = string.IsNullOrEmpty(containingType.AccessModifier)
                ? ""
                : containingType.AccessModifier + " ";
            w.Line($"{accessMod}partial {containingType.Keyword} {containingType.Name}");
            w.Line("{");
        }

        // Determine indentation for nested class context
        var baseIndent = unit.ContainingTypes.Count;
        var indent = new string('\t', baseIndent);
        var indent1 = indent + "\t";
        var indent2 = indent + "\t\t";
        var indent3 = indent + "\t\t\t";
        var indent4 = indent + "\t\t\t\t";

        var typeParamList = FormatTypeParameters(unit.TypeParameters);
        var constraintClauses = FormatConstraints(unit.TypeParameters);

        // Track which interceptors use pre-compiled mode vs generated classes
        var preCompiledInterceptors = new Dictionary<string, string>(); // interceptorName -> pre-compiled type
        var preCompiledDelegateDecls = new Dictionary<string, string>(); // interceptorName -> delegate declaration
        var preCompiledSyncDelegateDecls = new Dictionary<string, string>(); // interceptorName -> sync delegate declaration
        var renderedInterceptorClasses = new HashSet<string>();

        // Render interceptor classes (same as inline class stubs)
        foreach (var prop in unit.Properties)
        {
            if (renderedInterceptorClasses.Add(prop.InterceptorClassName))
            {
                var unifiedModel = ToUnifiedPropertyModel(prop);
                if (PreCompiledInterceptorRenderer.CanUsePreCompiled(unifiedModel))
                {
                    preCompiledInterceptors[prop.PropertyName] = PreCompiledInterceptorRenderer.GetPropertyInterceptorType(unifiedModel);
                }
                else
                {
                    var options = new PropertyInterceptorRenderOptions(
                        BaseIndent: baseIndent,
                        IncludeStrictParameter: true,
                        StrictAccessExpression: "strict",
                        InterceptorTypeParameters: prop.TypeParameterList,
                        InterceptorConstraints: prop.ConstraintClauses);
                    w.SetIndent(baseIndent);
                    PropertyInterceptorRenderer.RenderInterceptorClass(w, unifiedModel, options);
                }
            }
        }

        // Group indexers by interceptor class name and render as a single multi-indexer interceptor
        var indexersByClass = unit.Indexers.GroupBy(i => i.InterceptorClassName);
        foreach (var group in indexersByClass)
        {
            if (renderedInterceptorClasses.Add(group.Key))
            {
                var firstIndexer = group.First();
                var unifiedModels = group.Select(i => ToUnifiedIndexerModel(i)).ToList();
                if (PreCompiledInterceptorRenderer.CanUsePreCompiled(unifiedModels))
                {
                    preCompiledInterceptors[firstIndexer.IndexerName] = PreCompiledInterceptorRenderer.GetIndexerInterceptorType(unifiedModels[0]);
                }
                else
                {
                    var options = new IndexerInterceptorRenderOptions(
                        BaseIndent: baseIndent,
                        IncludeStrictParameter: true,
                        StrictAccessExpression: "strict",
                        InterceptorTypeParameters: firstIndexer.TypeParameterList,
                        InterceptorConstraints: firstIndexer.ConstraintClauses);
                    w.SetIndent(baseIndent);
                    IndexerInterceptorRenderer.RenderInterceptorClass(w, unifiedModels, options);
                }
            }
        }

        // All method interceptors are fully generated classes inheriting from MethodInterceptorRuntime.
        // No pre-compiled method interceptor types are used (Phase 2 redesign).
        foreach (var method in unit.Methods)
        {
            if (renderedInterceptorClasses.Add(method.InterceptorClassName))
            {
                var hasStubOverride = !string.IsNullOrEmpty(method.StubOverrideName) ||
                    method.Overloads.Any(o => !string.IsNullOrEmpty(o.StubOverrideName));

                var options = new InterceptorRenderOptions(
                    BaseIndent: baseIndent,
                    IncludeStrictParameter: true,
                    StrictAccessExpression: "strict",
                    InterceptorTypeParameters: typeParamList,
                    InterceptorConstraints: constraintClauses,
                    StubOverrideFallback: hasStubOverride,
                    StubTypeName: hasStubOverride ? $"{unit.ClassName}{typeParamList}" : null);
                w.SetIndent(baseIndent);
                MethodInterceptorRenderer.RenderInterceptorClass(w, method, options);
            }
        }

        foreach (var evt in unit.Events)
        {
            RenderEventInterceptorClass(w, evt, unit.ClassName, indent);
        }

        // Render generic method handler interceptor classes (Of<T>() pattern)
        // Pass emitHelperInterfaces=true because standalone interceptors are top-level classes,
        // not nested inside a containing class that provides IGenericMethodCallTracker/IResettable
        foreach (var handler in unit.GenericMethodHandlers)
        {
            ClassRenderer.RenderClassGenericMethodHandler(w, handler, indent, emitHelperInterfaces: true);
        }

        // Render the wrapper partial class (user's class)
        // Extends the generated base class for stub override properties
        var baseClassName = $"{unit.ClassName}Base{typeParamList}";
        w.Line($"{indent}/// <summary>Generated completion for {unit.ClassName} stub. Provides interceptors and .Object property.</summary>");
        w.Line($"{indent}partial class {unit.ClassName}{typeParamList} : {baseClassName}, global::KnockOff.IKnockOffStub{constraintClauses}");
        w.Line($"{indent}{{");

        // Strict property
        w.Line($"{indent1}/// <summary>When true, unconfigured method calls throw StubException instead of returning default.</summary>");
        w.Line($"{indent1}public bool Strict {{ get; set; }}");
        w.Line();

        // Interceptor properties
        foreach (var interceptorProp in unit.InterceptorProperties)
        {
            var newKeyword = interceptorProp.NeedsNewKeyword ? "new " : "";
            // Emit delegate declaration for TTuple types (1+ params)
            if (preCompiledDelegateDecls.TryGetValue(interceptorProp.PropertyName, out var delegateDecl))
            {
                w.Line($"{indent1}{delegateDecl}");
            }
            // Emit sync delegate declaration for async TTuple types
            if (preCompiledSyncDelegateDecls.TryGetValue(interceptorProp.PropertyName, out var syncDelegateDecl))
            {
                w.Line($"{indent1}{syncDelegateDecl}");
            }
            w.Line($"{indent1}/// <summary>{interceptorProp.Description}</summary>");
            if (preCompiledInterceptors.TryGetValue(interceptorProp.PropertyName, out var preCompiledType))
            {
                w.Line($"{indent1}public {newKeyword}{preCompiledType} {interceptorProp.PropertyName} {{ get; }} = new(\"{interceptorProp.PropertyName}\");");
            }
            else
            {
                w.Line($"{indent1}public {newKeyword}{interceptorProp.InterceptorTypeName} {interceptorProp.PropertyName} {{ get; }} = new();");
            }
        }
        w.Line();

        // .Object property
        w.Line($"{indent1}/// <summary>The {ExtractSimpleTypeName(unit.TargetClassName)} instance. Pass this to code expecting the target class.</summary>");
        w.Line($"{indent1}public {unit.TargetClassForInheritance} Object {{ get; }}");
        w.Line();

        // Constructors
        foreach (var ctor in unit.Constructors)
        {
            RenderWrapperConstructor(w, ctor, unit.ClassName, typeParamList, indent1);
        }

        // ResetInterceptors method
        w.Line($"{indent1}/// <summary>Resets all interceptor state.</summary>");
        w.Line($"{indent1}public void ResetInterceptors()");
        w.Line($"{indent1}{{");
        foreach (var resetStmt in unit.ResetStatements)
        {
            w.Line($"{indent2}{resetStmt}");
        }
        w.Line($"{indent1}}}");
        w.Line();

        // Verify and VerifyAll methods
        RenderVerifyMethods(w, unit, indent1, indent2);

        // Internal forwarding methods for stub overrides
        // Interceptor classes are top-level (not nested), so they cannot access
        // protected virtual methods on the base class. These internal forwarders
        // bridge the gap: interceptor calls stub.__StubOverride_X() which forwards
        // to the protected Execute_() method.
        RenderStubOverrideForwarders(w, unit, indent1);

        // Nested Impl class
        RenderImplClass(w, unit, indent1, indent2, indent3, indent4, preCompiledInterceptors);

        w.Line($"{indent}}}");

        // Close containing type wrappers for nested classes
        for (int i = 0; i < unit.ContainingTypes.Count; i++)
        {
            w.Line("}");
        }

        return w.ToString();
    }

    /// <summary>
    /// Renders the base class file for standalone class stubs.
    /// Contains virtual protected properties for each target class property, suffixed with '_'.
    /// Users can override these properties to provide default implementations.
    /// </summary>
    public static string RenderBaseClass(StandaloneClassGenerationUnit unit)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable SYSLIB0050 // Obsolete serialization API");
        w.Line();

        // Namespace
        if (!string.IsNullOrEmpty(unit.Namespace))
        {
            w.Line($"namespace {unit.Namespace};");
            w.Line();
        }

        // Open containing type wrappers for nested classes
        foreach (var containingType in unit.ContainingTypes)
        {
            var accessMod = string.IsNullOrEmpty(containingType.AccessModifier)
                ? ""
                : containingType.AccessModifier + " ";
            w.Line($"{accessMod}partial {containingType.Keyword} {containingType.Name}");
            w.Line("{");
        }

        // Base class declaration with type parameters and constraints
        var typeParams = FormatTypeParameters(unit.TypeParameters);
        var constraints = FormatConstraints(unit.TypeParameters);

        using (w.Block($"public class {unit.ClassName}Base{typeParams}{constraints}"))
        {
            // Generate virtual protected properties for each target class property
            foreach (var property in unit.BaseClassProperties)
            {
                RenderBaseClassProperty(w, property);
            }

            // Generate virtual protected methods for each target class method
            foreach (var method in unit.BaseClassMethods)
            {
                RenderBaseClassMethod(w, method);
            }
        }

        // Close containing type wrappers for nested classes
        for (int i = 0; i < unit.ContainingTypes.Count; i++)
        {
            w.Line("}");
        }

        return w.ToString();
    }

    /// <summary>
    /// Renders a single virtual protected method in the base class.
    /// Method name is suffixed with '_' to distinguish from target class method.
    /// Void methods have empty body; non-void methods return default!.
    /// </summary>
    private static void RenderBaseClassMethod(CodeWriter w, BaseClassMethodModel method)
    {
        var methodName = $"{method.MethodName}_";
        var returnType = method.ReturnType;

        w.Line($"/// <summary>Override to provide default implementation for {method.TargetMemberDescription}.</summary>");

        if (method.IsVoid)
        {
            // Void method - empty body
            if (string.IsNullOrEmpty(method.ParameterDeclarations))
                w.Line($"protected virtual void {methodName}() {{ }}");
            else
                w.Line($"protected virtual void {methodName}({method.ParameterDeclarations}) {{ }}");
        }
        else
        {
            // Non-void method - expression-bodied returning default!
            if (string.IsNullOrEmpty(method.ParameterDeclarations))
                w.Line($"protected virtual {returnType} {methodName}() => default!;");
            else
                w.Line($"protected virtual {returnType} {methodName}({method.ParameterDeclarations}) => default!;");
        }
        w.Line();
    }

    /// <summary>
    /// Renders a single virtual protected property in the base class.
    /// Property name is suffixed with '_' to distinguish from target class property.
    /// Returns default! to allow compilation without override.
    /// </summary>
    private static void RenderBaseClassProperty(CodeWriter w, BaseClassPropertyModel property)
    {
        var propertyName = $"{property.PropertyName}_";
        var returnType = property.ReturnType;

        w.Line($"/// <summary>Override to provide default implementation for {property.TargetMemberDescription}.</summary>");

        if (property.HasGetter && property.HasSetter)
        {
            // Get/set property - full property syntax
            w.Line($"protected virtual {returnType} {propertyName} {{ get => default!; set {{ }} }}");
        }
        else if (property.HasGetter)
        {
            // Get-only property - expression-bodied
            w.Line($"protected virtual {returnType} {propertyName} => default!;");
        }
        else if (property.HasSetter)
        {
            // Set-only property - block syntax
            w.Line($"protected virtual {returnType} {propertyName} {{ set {{ }} }}");
        }
        w.Line();
    }

    #region Event Interceptor Rendering

    private static void RenderEventInterceptorClass(CodeWriter w, InlineClassEventModel evt, string stubClassName, string indent)
    {
        var indent1 = indent + "\t";

        w.Line($"{indent}/// <summary>Interceptor for {stubClassName}.{evt.EventName}.</summary>");
        w.Line($"{indent}public sealed class {evt.InterceptorClassName}{evt.TypeParameterList}{evt.ConstraintClauses}");
        w.Line($"{indent}{{");

        // Backing field
        w.Line($"{indent1}private {evt.DelegateType}? _handler;");
        w.Line();

        // Add/Remove tracking
        w.Line($"{indent1}private int _addCount;");
        w.Line();
        w.Line($"{indent1}private int _removeCount;");
        w.Line();

        w.Line($"{indent1}/// <summary>Whether any handlers are subscribed.</summary>");
        w.Line($"{indent1}public bool HasSubscribers => _handler != null;");
        w.Line();

        w.Line($"{indent1}/// <summary>Records an event subscription.</summary>");
        w.Line($"{indent1}public void RecordAdd({evt.DelegateType}? value) {{ _addCount++; _handler = ({evt.DelegateType}?)global::System.Delegate.Combine(_handler, value); }}");
        w.Line();
        w.Line($"{indent1}/// <summary>Records an event unsubscription.</summary>");
        w.Line($"{indent1}public void RecordRemove({evt.DelegateType}? value) {{ _removeCount++; _handler = ({evt.DelegateType}?)global::System.Delegate.Remove(_handler, value); }}");
        w.Line();

        // Raise method
        RenderEventRaiseMethod(w, evt, indent1);

        w.Line($"{indent1}/// <summary>Resets tracking state (counts, handler) but preserves verifiable marking.</summary>");
        w.Line($"{indent1}public void Reset() {{ _addCount = 0; _removeCount = 0; _handler = null; }}");
        w.Line();

        // Verification API
        w.Line($"{indent1}private bool _isVerifiable;");
        w.Line($"{indent1}private global::KnockOff.Called? _verifiableTimes;");
        w.Line();

        w.Line($"{indent1}/// <summary>Verifies the event was subscribed to at least once.</summary>");
        w.Line($"{indent1}public void VerifyAdd() => VerifyAdd(global::KnockOff.Called.AtLeastOnce);");
        w.Line();

        w.Line($"{indent1}/// <summary>Verifies the event subscription count matches the Called constraint.</summary>");
        w.Line($"{indent1}public void VerifyAdd(global::KnockOff.Called times)");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\tif (!times.Validate(_addCount))");
        w.Line($"{indent1}\t\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' add verification failed: expected {{times}}, but was called {{_addCount}} time(s).\");");
        w.Line($"{indent1}}}");
        w.Line();

        w.Line($"{indent1}/// <summary>Verifies the event was unsubscribed at least once.</summary>");
        w.Line($"{indent1}public void VerifyRemove() => VerifyRemove(global::KnockOff.Called.AtLeastOnce);");
        w.Line();

        w.Line($"{indent1}/// <summary>Verifies the event unsubscription count matches the Called constraint.</summary>");
        w.Line($"{indent1}public void VerifyRemove(global::KnockOff.Called times)");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\tif (!times.Validate(_removeCount))");
        w.Line($"{indent1}\t\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' remove verification failed: expected {{times}}, but was called {{_removeCount}} time(s).\");");
        w.Line($"{indent1}}}");
        w.Line();

        w.Line($"{indent1}/// <summary>Verifies the event was accessed (add or remove) at least once.</summary>");
        w.Line($"{indent1}public void Verify() => Verify(global::KnockOff.Called.AtLeastOnce);");
        w.Line();

        w.Line($"{indent1}/// <summary>Verifies the total event access count matches the Called constraint.</summary>");
        w.Line($"{indent1}public void Verify(global::KnockOff.Called times)");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\tvar totalCount = _addCount + _removeCount;");
        w.Line($"{indent1}\tif (!times.Validate(totalCount))");
        w.Line($"{indent1}\t\tthrow new global::KnockOff.VerificationException($\"Event '{evt.EventName}' verification failed: expected {{times}}, but was called {{totalCount}} time(s).\");");
        w.Line($"{indent1}}}");
        w.Line();

        w.Line($"{indent1}/// <summary>Marks this event for verification by Stub.Verify(). Returns this for fluent chaining.</summary>");
        w.Line($"{indent1}public {evt.InterceptorClassName}{evt.TypeParameterList} Verifiable()");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\t_isVerifiable = true;");
        w.Line($"{indent1}\t_verifiableTimes = global::KnockOff.Called.AtLeastOnce;");
        w.Line($"{indent1}\treturn this;");
        w.Line($"{indent1}}}");
        w.Line();

        w.Line($"{indent1}/// <summary>Marks this event for verification by Stub.Verify() with Called constraint. Returns this for fluent chaining.</summary>");
        w.Line($"{indent1}public {evt.InterceptorClassName}{evt.TypeParameterList} Verifiable(global::KnockOff.Called times)");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\t_isVerifiable = true;");
        w.Line($"{indent1}\t_verifiableTimes = times;");
        w.Line($"{indent1}\treturn this;");
        w.Line($"{indent1}}}");
        w.Line();

        // Internal verification methods
        w.Line($"{indent1}internal bool IsVerifiable => _isVerifiable;");
        w.Line($"{indent1}internal bool IsConfigured => _handler != null;");
        w.Line();

        w.Line($"{indent1}/// <summary>Checks verification for Stub.Verify() - only verifiable items.</summary>");
        w.Line($"{indent1}internal global::KnockOff.VerificationFailure? CheckVerification()");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\tif (!_isVerifiable) return null;");
        w.Line($"{indent1}\tvar times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
        w.Line($"{indent1}\tvar totalCount = _addCount + _removeCount;");
        w.Line($"{indent1}\treturn times.Validate(totalCount) ? null : new global::KnockOff.VerificationFailure(\"{evt.EventName}\", times, totalCount);");
        w.Line($"{indent1}}}");
        w.Line();

        w.Line($"{indent1}/// <summary>Checks verification for Stub.VerifyAll() - all configured items.</summary>");
        w.Line($"{indent1}internal global::KnockOff.VerificationFailure? CheckVerificationAll()");
        w.Line($"{indent1}{{");
        w.Line($"{indent1}\tif (!IsConfigured && !_isVerifiable) return null;");
        w.Line($"{indent1}\tvar times = _verifiableTimes ?? global::KnockOff.Called.AtLeastOnce;");
        w.Line($"{indent1}\tvar totalCount = _addCount + _removeCount;");
        w.Line($"{indent1}\treturn times.Validate(totalCount) ? null : new global::KnockOff.VerificationFailure(\"{evt.EventName}\", times, totalCount);");
        w.Line($"{indent1}}}");

        w.Line($"{indent}}}");
        w.Line();
    }

    private static void RenderEventRaiseMethod(CodeWriter w, InlineClassEventModel evt, string indent)
    {
        if (evt.RaiseReturnsValue)
        {
            // Func-style delegate
            w.Line($"{indent}/// <summary>Raises the event with the specified arguments and returns the result.</summary>");
            if (string.IsNullOrEmpty(evt.RaiseParameters))
            {
                w.Line($"{indent}public {evt.RaiseReturnType} Raise() => _handler != null ? _handler.Invoke() : default!;");
            }
            else
            {
                w.Line($"{indent}public {evt.RaiseReturnType} Raise({evt.RaiseParameters}) => _handler != null ? _handler.Invoke({evt.RaiseArguments}) : default!;");
            }
        }
        else if (evt.UsesDynamicInvoke)
        {
            // Custom delegate - use DynamicInvoke
            if (string.IsNullOrEmpty(evt.RaiseParameters))
            {
                w.Line($"{indent}/// <summary>Raises the event.</summary>");
                w.Line($"{indent}public void Raise() => (_handler as global::System.Action)?.Invoke();");
            }
            else
            {
                w.Line($"{indent}/// <summary>Invokes the handler if subscribed.</summary>");
                w.Line($"{indent}public void Raise({evt.RaiseParameters}) => _handler?.DynamicInvoke({evt.RaiseArguments});");
            }
        }
        else
        {
            // Standard Action/EventHandler
            if (string.IsNullOrEmpty(evt.RaiseParameters))
            {
                w.Line($"{indent}/// <summary>Raises the event.</summary>");
                w.Line($"{indent}public void Raise() => _handler?.Invoke();");
            }
            else
            {
                w.Line($"{indent}/// <summary>Raises the event with the specified arguments.</summary>");
                w.Line($"{indent}public void Raise({evt.RaiseParameters}) => _handler?.Invoke({evt.RaiseArguments});");
            }
        }
        w.Line();
    }

    #endregion

    #region Wrapper Constructor Rendering

    private static void RenderWrapperConstructor(CodeWriter w, InlineConstructorModel ctor, string stubClassName, string typeParamList, string indent)
    {
        w.Line($"{indent}public {stubClassName}({ctor.ParameterDeclarations})");
        w.Line($"{indent}{{");
        if (string.IsNullOrEmpty(ctor.BaseCallArguments))
        {
            w.Line($"{indent}\tObject = new Impl(this);");
        }
        else
        {
            w.Line($"{indent}\tObject = new Impl(this, {ctor.BaseCallArguments});");
        }
        w.Line($"{indent}}}");
        w.Line();
    }

    private static void RenderVerifyMethods(CodeWriter w, StandaloneClassGenerationUnit unit, string indent, string indent1)
    {
        var interceptorPropertyNames = unit.InterceptorProperties
            .Select(p => p.PropertyName)
            .Distinct()
            .ToList();

        // Verify method
        w.Line($"{indent}/// <summary>Verifies all members marked with .Verifiable() were invoked as expected. Throws VerificationException with all failures if any fail.</summary>");
        w.Line($"{indent}public void Verify()");
        w.Line($"{indent}{{");
        w.Line($"{indent1}var failures = new global::System.Collections.Generic.List<global::KnockOff.VerificationFailure>();");
        w.Line();

        foreach (var name in interceptorPropertyNames)
        {
            w.Line($"{indent1}if ({name}.CheckVerification() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
        }

        w.Line();
        w.Line($"{indent1}if (failures.Count > 0)");
        w.Line($"{indent1}\tthrow new global::KnockOff.VerificationException(failures);");
        w.Line($"{indent}}}");
        w.Line();

        // VerifyAll method
        w.Line($"{indent}/// <summary>Verifies ALL configured members were invoked at least once. Throws VerificationException with all failures if any fail.</summary>");
        w.Line($"{indent}public void VerifyAll()");
        w.Line($"{indent}{{");
        w.Line($"{indent1}var failures = new global::System.Collections.Generic.List<global::KnockOff.VerificationFailure>();");
        w.Line();

        foreach (var name in interceptorPropertyNames)
        {
            w.Line($"{indent1}if ({name}.CheckVerificationAll() is {{ }} {name.ToLowerInvariant()}Failure) failures.Add({name.ToLowerInvariant()}Failure);");
        }

        w.Line();
        w.Line($"{indent1}if (failures.Count > 0)");
        w.Line($"{indent1}\tthrow new global::KnockOff.VerificationException(failures);");
        w.Line($"{indent}}}");
        w.Line();
    }

    #endregion

    #region Stub Override Forwarders

    /// <summary>
    /// Generates internal forwarding methods for stub overrides.
    /// Standalone class interceptors are top-level classes (not nested inside the stub),
    /// so they cannot access protected virtual methods on the stub's base class.
    /// These internal forwarders bridge the gap: the interceptor calls stub.__StubOverride_X()
    /// which has internal access, and the forwarder delegates to the protected Execute_() method.
    /// </summary>
    private static void RenderStubOverrideForwarders(CodeWriter w, StandaloneClassGenerationUnit unit, string indent)
    {
        var methodsWithStubOverride = unit.ImplMethods.Where(m => m.HasStubOverride).ToList();
        if (methodsWithStubOverride.Count == 0)
            return;

        foreach (var method in methodsWithStubOverride)
        {
            var forwarderName = $"__StubOverride_{method.MethodName}";
            var targetName = $"{method.MethodName}_";

            if (method.IsVoid)
            {
                if (string.IsNullOrEmpty(method.ParameterDeclarations))
                    w.Line($"{indent}internal void {forwarderName}() => {targetName}();");
                else
                    w.Line($"{indent}internal void {forwarderName}({method.ParameterDeclarations}) => {targetName}({method.ArgumentList});");
            }
            else
            {
                if (string.IsNullOrEmpty(method.ParameterDeclarations))
                    w.Line($"{indent}internal {method.ReturnType} {forwarderName}() => {targetName}();");
                else
                    w.Line($"{indent}internal {method.ReturnType} {forwarderName}({method.ParameterDeclarations}) => {targetName}({method.ArgumentList});");
            }
        }
        w.Line();
    }

    #endregion

    #region Impl Class Rendering

    private static void RenderImplClass(
        CodeWriter w,
        StandaloneClassGenerationUnit unit,
        string indent,
        string indent1,
        string indent2,
        string indent3,
        Dictionary<string, string> preCompiledInterceptors)
    {
        var typeParamList = FormatTypeParameters(unit.TypeParameters);
        var stubClassName = unit.ClassName + typeParamList;

        // Suppress CS8618 for classes with required members
        if (unit.HasRequiredMembers)
        {
            w.Line("#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor");
        }

        w.Line($"{indent}/// <summary>Internal implementation that inherits from {ExtractSimpleTypeName(unit.TargetClassName)}.</summary>");
        var implKeyword = unit.IsRecord ? "record" : "class";
        w.Line($"{indent}private sealed {implKeyword} Impl : {unit.TargetClassForInheritance}");
        w.Line($"{indent}{{");

        // Reference to the wrapper
        w.Line($"{indent1}private readonly {stubClassName} _stub;");
        w.Line();

        // Default ref backing fields for abstract ref return members (_stub == null path during base constructor)
        foreach (var prop in unit.ImplProperties)
        {
            if (prop.IsRefReturn && prop.IsAbstract)
            {
                w.Line($"{indent1}private {prop.ReturnType} _defaultRefBacking_{prop.PropertyName};");
            }
        }
        foreach (var indexer in unit.ImplIndexers)
        {
            if (indexer.IsRefReturn && indexer.IsAbstract)
            {
                w.Line($"{indent1}private {indexer.ReturnType} _defaultRefBacking_{indexer.IndexerName}{indexer.InvokeSuffix};");
            }
        }
        foreach (var method in unit.ImplMethods)
        {
            if (method.IsRefReturn && method.IsAbstract)
            {
                w.Line($"{indent1}private {method.ReturnType} _defaultRefBacking_{method.MethodName};");
            }
        }
        w.Line();

        // Constructors
        foreach (var ctor in unit.Constructors)
        {
            RenderImplConstructor(w, ctor, stubClassName, unit.HasRequiredMembers, unit.RequiredMemberNames, indent1);
        }

        // Property overrides
        foreach (var prop in unit.ImplProperties)
        {
            RenderImplPropertyOverride(w, prop, indent1, indent2);
        }

        // Indexer overrides
        foreach (var indexer in unit.ImplIndexers)
        {
            RenderImplIndexerOverride(w, indexer, indent1, indent2);
        }

        // Method overrides
        foreach (var method in unit.ImplMethods)
        {
            RenderImplMethodOverride(w, method, indent1, indent2, preCompiledInterceptors);
        }

        // Event overrides
        foreach (var evt in unit.ImplEvents)
        {
            RenderImplEventOverride(w, evt, indent1, indent2);
        }

        w.Line($"{indent}}}");

        if (unit.HasRequiredMembers)
        {
            w.Line("#pragma warning restore CS8618");
        }
    }

    private static void RenderImplConstructor(CodeWriter w, InlineConstructorModel ctor, string stubClassName, bool hasRequiredMembers, EquatableArray<string> requiredMemberNames, string indent)
    {
        var indent1 = indent + "\t";

        var paramList = string.IsNullOrEmpty(ctor.ParameterDeclarations)
            ? $"{stubClassName} stub"
            : $"{stubClassName} stub, {ctor.ParameterDeclarations}";

        if (hasRequiredMembers)
        {
            w.Line($"{indent}[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]");
        }
        w.Line($"{indent}public Impl({paramList}) : base({ctor.BaseCallArguments})");
        w.Line($"{indent}{{");

        foreach (var memberName in requiredMemberNames)
        {
            w.Line($"{indent1}{memberName} = default!;");
        }

        w.Line($"{indent1}_stub = stub;");
        w.Line($"{indent}}}");
        w.Line();
    }

    private static void RenderImplPropertyOverride(CodeWriter w, InlineClassImplPropertyModel prop, string indent, string indent1)
    {
        var indent2 = indent1 + "\t";
        var requiredKeyword = prop.IsRequired ? "required " : "";

        if (prop.SetterHasAllowNull)
            w.Line("#pragma warning disable CS8765 // Nullability of parameter doesn't match overridden member");
        w.Line($"{indent}/// <inheritdoc />");
        w.Line($"{indent}{requiredKeyword}{prop.AccessModifier} override {prop.RefReturnPrefix}{prop.ReturnType} {prop.PropertyName}");
        w.Line($"{indent}{{");

        if (prop.IsRefReturn)
        {
            // Ref return properties are always get-only (C# constraint)
            w.Line($"{indent1}get");
            w.Line($"{indent1}{{");
            if (prop.IsAbstract)
            {
                w.Line($"{indent2}if (_stub == null) {{ _defaultRefBacking_{prop.PropertyName} = default!; return ref _defaultRefBacking_{prop.PropertyName}; }}");
                w.Line($"{indent2}_stub.{prop.PropertyName}.InvokeRefGet(_stub.Strict);");
                w.Line($"{indent2}return ref _stub.{prop.PropertyName}._refReturnBacking;");
            }
            else
            {
                // Virtual: IsConfigured-first pattern
                w.Line($"{indent2}if (_stub == null) return ref base.{prop.PropertyName};");
                w.Line($"{indent2}if (_stub.{prop.PropertyName}.IsConfigured)");
                w.Line($"{indent2}{{");
                w.Line($"{indent2}\t_stub.{prop.PropertyName}.InvokeRefGet(_stub.Strict);");
                w.Line($"{indent2}\treturn ref _stub.{prop.PropertyName}._refReturnBacking;");
                w.Line($"{indent2}}}");
                w.Line($"{indent2}_stub.{prop.PropertyName}.InvokeRefGet(_stub.Strict);");
                w.Line($"{indent2}return ref base.{prop.PropertyName};");
            }
            w.Line($"{indent1}}}");
        }
        else
        {
            if (prop.HasGetter)
            {
                w.Line($"{indent1}get");
                w.Line($"{indent1}{{");

                if (prop.HasStubOverride)
                {
                    // Stub override pattern:
                    // 1. Null check for calls during base constructor (fall back to base for virtual)
                    // 2. Get supersedes stub override (InvokeGetCallback tracks internally)
                    // 3. Record access only for stub override path (to avoid double counting)
                    // 4. Stub override (virtual property with _ suffix in stub's base class)
                    var fallback = prop.IsAbstract ? "default!" : $"base.{prop.PropertyName}";
                    w.Line($"{indent2}if (_stub == null) return {fallback};");
                    w.Line($"{indent2}if (_stub.{prop.PropertyName}.HasGet) return _stub.{prop.PropertyName}.InvokeGetCallback();");
                    w.Line($"{indent2}_stub.{prop.PropertyName}.RecordGet();");
                    w.Line($"{indent2}return _stub.{prop.PropertyName}_;");
                }
                else
                {
                    // No stub override - delegate to interceptor which handles full priority chain
                    // (sequence > Get > strict/default) and falls back to base for virtual properties
                    if (prop.IsAbstract)
                    {
                        w.Line($"{indent2}if (_stub == null) return default!;");
                        w.Line($"{indent2}return _stub.{prop.PropertyName}.InvokeGet(_stub.Strict);");
                    }
                    else
                    {
                        // For virtual properties, check if configured. If not, delegate to base.
                        w.Line($"{indent2}if (_stub == null) return base.{prop.PropertyName};");
                        w.Line($"{indent2}if (_stub.{prop.PropertyName}.IsConfigured) return _stub.{prop.PropertyName}.InvokeGet(_stub.Strict);");
                        w.Line($"{indent2}_stub.{prop.PropertyName}.InvokeGet(_stub.Strict);");
                        w.Line($"{indent2}return base.{prop.PropertyName};");
                    }
                }
                w.Line($"{indent1}}}");
            }

            if (prop.HasSetter)
            {
                var setterKeyword = prop.IsInitOnly ? "init" : "set";
                w.Line($"{indent1}{setterKeyword}");
                w.Line($"{indent1}{{");

                if (prop.HasStubOverride)
                {
                    // Stub override pattern:
                    // 1. Null check for calls during base constructor (fall back to base for virtual)
                    // 2. Set supersedes stub override (InvokeSetCallback tracks internally)
                    // 3. Record access only for stub override path (to avoid double counting)
                    // 4. Stub override (virtual property with _ suffix in stub's base class)
                    if (prop.IsAbstract)
                    {
                        w.Line($"{indent2}if (_stub == null) return;");
                    }
                    else
                    {
                        w.Line($"{indent2}if (_stub == null) {{ base.{prop.PropertyName} = value; return; }}");
                    }
                    w.Line($"{indent2}if (_stub.{prop.PropertyName}.HasSet) {{ _stub.{prop.PropertyName}.InvokeSetCallback(value); return; }}");
                    w.Line($"{indent2}_stub.{prop.PropertyName}.RecordSet(value);");
                    w.Line($"{indent2}_stub.{prop.PropertyName}_ = value;");
                }
                else
                {
                    // No stub override - delegate to interceptor which handles full priority chain
                    // (sequence > Set > strict/default) and falls back to base for virtual properties
                    if (prop.IsAbstract)
                    {
                        w.Line($"{indent2}if (_stub == null) return;");
                        w.Line($"{indent2}_stub.{prop.PropertyName}.InvokeSet(_stub.Strict, value);");
                    }
                    else
                    {
                        // For virtual properties, check if configured. If not, delegate to base.
                        w.Line($"{indent2}if (_stub == null) {{ base.{prop.PropertyName} = value; return; }}");
                        w.Line($"{indent2}_stub.{prop.PropertyName}.InvokeSet(_stub.Strict, value);");
                        w.Line($"{indent2}if (!_stub.{prop.PropertyName}.IsConfigured) base.{prop.PropertyName} = value;");
                    }
                }
                w.Line($"{indent1}}}");
            }
        }

        w.Line($"{indent}}}");
        if (prop.SetterHasAllowNull)
            w.Line("#pragma warning restore CS8765");
        w.Line();
    }

    private static void RenderImplIndexerOverride(CodeWriter w, InlineClassImplIndexerModel indexer, string indent, string indent1)
    {
        var indent2 = indent1 + "\t";
        var invokeSuffix = indexer.InvokeSuffix;

        if (indexer.SetterHasAllowNull)
            w.Line("#pragma warning disable CS8765 // Nullability of parameter doesn't match overridden member");
        w.Line($"{indent}/// <inheritdoc />");
        w.Line($"{indent}{indexer.AccessModifier} override {indexer.RefReturnPrefix}{indexer.ReturnType} this[{indexer.ParameterDeclarations}]");
        w.Line($"{indent}{{");

        if (indexer.IsRefReturn)
        {
            // Ref return indexers are always get-only (C# constraint)
            w.Line($"{indent1}get");
            w.Line($"{indent1}{{");
            if (indexer.IsAbstract)
            {
                w.Line($"{indent2}if (_stub == null) {{ _defaultRefBacking_{indexer.IndexerName}{invokeSuffix} = default!; return ref _defaultRefBacking_{indexer.IndexerName}{invokeSuffix}; }}");
                w.Line($"{indent2}_stub.{indexer.IndexerName}.InvokeRefGet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList});");
                w.Line($"{indent2}return ref _stub.{indexer.IndexerName}._refReturnBacking{invokeSuffix};");
            }
            else
            {
                // Virtual: IsConfigured-first pattern
                w.Line($"{indent2}if (_stub == null) return ref base[{indexer.ArgumentList}];");
                w.Line($"{indent2}if (_stub.{indexer.IndexerName}.IsConfigured)");
                w.Line($"{indent2}{{");
                w.Line($"{indent2}\t_stub.{indexer.IndexerName}.InvokeRefGet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList});");
                w.Line($"{indent2}\treturn ref _stub.{indexer.IndexerName}._refReturnBacking{invokeSuffix};");
                w.Line($"{indent2}}}");
                w.Line($"{indent2}_stub.{indexer.IndexerName}.InvokeRefGet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList});");
                w.Line($"{indent2}return ref base[{indexer.ArgumentList}];");
            }
            w.Line($"{indent1}}}");
        }
        else
        {
            if (indexer.HasGetter)
            {
                w.Line($"{indent1}get");
                w.Line($"{indent1}{{");
                if (indexer.IsAbstract)
                {
                    var defaultExpr = indexer.IsNullable ? "default" : GetDefaultForType(indexer.ReturnType, indexer.DefaultStrategy, indexer.ConcreteTypeForNew);
                    w.Line($"{indent2}if (_stub == null) return {defaultExpr};");
                    w.Line($"{indent2}return _stub.{indexer.IndexerName}.InvokeGet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList});");
                }
                else
                {
                    w.Line($"{indent2}if (_stub == null) return base[{indexer.ArgumentList}];");
                    w.Line($"{indent2}if (_stub.{indexer.IndexerName}.IsConfigured) return _stub.{indexer.IndexerName}.InvokeGet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList});");
                    w.Line($"{indent2}_stub.{indexer.IndexerName}.InvokeGet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList});");
                    w.Line($"{indent2}return base[{indexer.ArgumentList}];");
                }
                w.Line($"{indent1}}}");
            }

            if (indexer.HasSetter)
            {
                var setterKeyword = indexer.IsInitOnly ? "init" : "set";
                w.Line($"{indent1}{setterKeyword}");
                w.Line($"{indent1}{{");
                if (indexer.IsAbstract)
                {
                    w.Line($"{indent2}if (_stub == null) return;");
                    w.Line($"{indent2}_stub.{indexer.IndexerName}.InvokeSet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList}, value);");
                }
                else
                {
                    w.Line($"{indent2}if (_stub == null) {{ base[{indexer.ArgumentList}] = value; return; }}");
                    w.Line($"{indent2}_stub.{indexer.IndexerName}.InvokeSet{invokeSuffix}(_stub.Strict, {indexer.ArgumentList}, value);");
                    w.Line($"{indent2}if (!_stub.{indexer.IndexerName}.IsConfigured) base[{indexer.ArgumentList}] = value;");
                }
                w.Line($"{indent1}}}");
            }
        }

        w.Line($"{indent}}}");
        if (indexer.SetterHasAllowNull)
            w.Line("#pragma warning restore CS8765");
        w.Line();
    }

    private static void RenderImplMethodOverride(
        CodeWriter w,
        InlineClassImplMethodModel method,
        string indent,
        string indent1,
        Dictionary<string, string> preCompiledInterceptors)
    {
        if (method.IsGenericMethod)
        {
            ClassRenderer.RenderImplGenericMethodOverride(w, method, indent, indent1);
            return;
        }

        var isPreCompiled = preCompiledInterceptors.ContainsKey(method.HandlerName);

        if (method.DoesNotReturn)
        {
            w.Line("#pragma warning disable CS8763 // A method marked [DoesNotReturn] should not return");
            w.Line($"{indent}[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
        }
        w.Line($"{indent}/// <inheritdoc />");
        w.Line($"{indent}{method.AccessModifier} override {method.RefReturnPrefix}{method.ReturnType} {method.MethodName}({method.ParameterDeclarations})");
        w.Line($"{indent}{{");

        if (method.IsRefReturn)
        {
            // Ref return method override - uses InvokeRef + _refReturnBacking pattern
            // Note: ref return methods always fall back to generated interceptor classes (never pre-compiled)
            var invokeRefMethodName = string.IsNullOrEmpty(method.InvokeSuffix)
                ? "InvokeRef"
                : $"InvokeRef{method.InvokeSuffix}";
            var backingField = string.IsNullOrEmpty(method.InvokeSuffix)
                ? "_refReturnBacking"
                : $"_refReturnBacking{method.InvokeSuffix}";
            var invokeArgs = "_stub.Strict" + (string.IsNullOrEmpty(method.InputArgumentList) ? "" : $", {method.InputArgumentList}");

            if (method.IsAbstract)
            {
                w.Line($"{indent1}if (_stub == null) {{ _defaultRefBacking_{method.MethodName} = default!; return ref _defaultRefBacking_{method.MethodName}; }}");
                w.Line($"{indent1}_stub.{method.HandlerName}.{invokeRefMethodName}({invokeArgs});");
                w.Line($"{indent1}return ref _stub.{method.HandlerName}.{backingField};");
            }
            else
            {
                // Virtual: IsConfigured-first pattern
                w.Line($"{indent1}if (_stub == null) return ref base.{method.MethodName}({method.ArgumentList});");
                w.Line($"{indent1}if (_stub.{method.HandlerName}.IsConfigured)");
                w.Line($"{indent1}{{");
                w.Line($"{indent1}\t_stub.{method.HandlerName}.{invokeRefMethodName}({invokeArgs});");
                w.Line($"{indent1}\treturn ref _stub.{method.HandlerName}.{backingField};");
                w.Line($"{indent1}}}");
                w.Line($"{indent1}_stub.{method.HandlerName}.{invokeRefMethodName}({invokeArgs});");
                w.Line($"{indent1}return ref base.{method.MethodName}({method.ArgumentList});");
            }
        }
        else
        {
            var invokeMethodName = string.IsNullOrEmpty(method.InvokeSuffix)
                ? "Invoke"
                : $"Invoke{method.InvokeSuffix}";

            if (method.HasStubOverride)
            {
                // Stub override pattern:
                // The interceptor handles stub override fallback internally via stub.MethodName_()
                // Pass _stub to Invoke() so the interceptor can call the stub override when unconfigured
                // No base.Method() call -- stub override completely replaces base call (Design Decision 1)
                // Note: stub overrides are excluded from pre-compiled interceptors

                // Null check for calls during base constructor
                if (method.IsVoid)
                {
                    w.Line($"{indent1}if (_stub == null) return;");
                    var invokeArgs = "_stub.Strict, _stub" + (string.IsNullOrEmpty(method.InputArgumentList) ? "" : $", {method.InputArgumentList}");
                    w.Line($"{indent1}_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs});");
                }
                else
                {
                    w.Line($"{indent1}if (_stub == null) return default!;");
                    var invokeArgs = "_stub.Strict, _stub" + (string.IsNullOrEmpty(method.InputArgumentList) ? "" : $", {method.InputArgumentList}");
                    w.Line($"{indent1}return _stub.{method.HandlerName}.{invokeMethodName}({invokeArgs});");
                }
            }
            else
            {
                // Standard interceptor pattern (no stub override)

                // Null check for calls during base constructor
                w.Line($"{indent1}if (_stub == null)");
                w.Line($"{indent1}{{");
                if (method.IsAbstract)
                {
                    if (method.IsVoid)
                        w.Line($"{indent1}\treturn;");
                    else if (method.IsTask)
                        w.Line($"{indent1}\treturn global::System.Threading.Tasks.Task.CompletedTask;");
                    else if (method.IsValueTask)
                        w.Line($"{indent1}\treturn default;");
                    else
                        w.Line($"{indent1}\treturn default!;");
                }
                else
                {
                    if (method.IsVoid)
                    {
                        w.Line($"{indent1}\tbase.{method.MethodName}({method.ArgumentList});");
                        w.Line($"{indent1}\treturn;");
                    }
                    else
                    {
                        w.Line($"{indent1}\treturn base.{method.MethodName}({method.ArgumentList});");
                    }
                }
                w.Line($"{indent1}}}");
                w.Line();

                // Build invoke arguments: strict, then method parameters
                // For pre-compiled interceptors, strip ref/in prefixes and wrap for TTuple
                var rawInputArgs = method.InputArgumentList;
                var cleanInputArgs = isPreCompiled ? StripRefPrefixes(rawInputArgs) : rawInputArgs;
                string invokeArgs;
                if (isPreCompiled)
                {
                    // TTuple types: wrap 2+ params in tuple literal for Invoke(bool strict, TArgs args)
                    var wrappedArgs = PreCompiledInterceptorRenderer.WrapInvokeArgs(cleanInputArgs);
                    invokeArgs = "_stub.Strict" + wrappedArgs;
                }
                else
                {
                    invokeArgs = "_stub.Strict" + (string.IsNullOrEmpty(cleanInputArgs) ? "" : $", {cleanInputArgs}");
                }

                // Determine if ValueTask wrapping is needed (only for pre-compiled)
                var needsValueTaskWrap = false;
                var needsVoidValueTaskWrap = false;
                if (isPreCompiled)
                {
                    var (_, _, isAsyncValueTaskT) = PreCompiledInterceptorRenderer.GetAsyncTypeInfoPublic(method.ReturnType);
                    var (_, isVoidValueTask) = PreCompiledInterceptorRenderer.GetVoidAsyncInfoPublic(method.ReturnType);
                    needsValueTaskWrap = isAsyncValueTaskT;
                    needsVoidValueTaskWrap = isVoidValueTask;
                }
                // Non-precompiled interceptors handle ValueTask wrapping in their Invoke methods

                if (method.IsAbstract)
                {
                    if (method.IsVoid)
                    {
                        w.Line($"{indent1}_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs});");
                    }
                    else if (needsVoidValueTaskWrap)
                    {
                        w.Line($"{indent1}return new global::System.Threading.Tasks.ValueTask(_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs}));");
                    }
                    else if (needsValueTaskWrap)
                    {
                        w.Line($"{indent1}return new {method.ReturnType}(_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs}));");
                    }
                    else
                    {
                        w.Line($"{indent1}return _stub.{method.HandlerName}.{invokeMethodName}({invokeArgs});");
                    }
                }
                else
                {
                    w.Line($"{indent1}var unconfiguredBefore = _stub.{method.HandlerName}.UnconfiguredCallCount;");
                    if (method.IsVoid)
                    {
                        w.Line($"{indent1}_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs});");
                        w.Line($"{indent1}if (_stub.{method.HandlerName}.UnconfiguredCallCount > unconfiguredBefore)");
                        w.Line($"{indent1}{{");
                        w.Line($"{indent1}\tbase.{method.MethodName}({method.ArgumentList});");
                        w.Line($"{indent1}}}");
                    }
                    else if (needsVoidValueTaskWrap)
                    {
                        w.Line($"{indent1}var result = new global::System.Threading.Tasks.ValueTask(_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs}));");
                        w.Line($"{indent1}if (_stub.{method.HandlerName}.UnconfiguredCallCount > unconfiguredBefore)");
                        w.Line($"{indent1}{{");
                        w.Line($"{indent1}\treturn base.{method.MethodName}({method.ArgumentList});");
                        w.Line($"{indent1}}}");
                        w.Line($"{indent1}return result;");
                    }
                    else if (needsValueTaskWrap)
                    {
                        w.Line($"{indent1}var result = new {method.ReturnType}(_stub.{method.HandlerName}.{invokeMethodName}({invokeArgs}));");
                        w.Line($"{indent1}if (_stub.{method.HandlerName}.UnconfiguredCallCount > unconfiguredBefore)");
                        w.Line($"{indent1}{{");
                        w.Line($"{indent1}\treturn base.{method.MethodName}({method.ArgumentList});");
                        w.Line($"{indent1}}}");
                        w.Line($"{indent1}return result;");
                    }
                    else
                    {
                        w.Line($"{indent1}var result = _stub.{method.HandlerName}.{invokeMethodName}({invokeArgs});");
                        w.Line($"{indent1}if (_stub.{method.HandlerName}.UnconfiguredCallCount > unconfiguredBefore)");
                        w.Line($"{indent1}{{");
                        w.Line($"{indent1}\treturn base.{method.MethodName}({method.ArgumentList});");
                        w.Line($"{indent1}}}");
                        w.Line($"{indent1}return result;");
                    }
                }
            }
        }

        w.Line($"{indent}}}");
        if (method.DoesNotReturn)
            w.Line("#pragma warning restore CS8763");
        w.Line();
    }

    private static void RenderImplEventOverride(CodeWriter w, InlineClassImplEventModel evt, string indent, string indent1)
    {
        w.Line($"{indent}/// <inheritdoc />");
        w.Line($"{indent}{evt.AccessModifier} override event {evt.DelegateType}? {evt.EventName}");
        w.Line($"{indent}{{");
        w.Line($"{indent1}add => _stub?.{evt.EventName}.RecordAdd(value);");
        w.Line($"{indent1}remove => _stub?.{evt.EventName}.RecordRemove(value);");
        w.Line($"{indent}}}");
        w.Line();
    }

    #endregion

    #region Model Adapters

    private static UnifiedPropertyInterceptorModel ToUnifiedPropertyModel(InlineClassPropertyModel prop)
    {
        return new UnifiedPropertyInterceptorModel(
            InterceptorClassName: prop.InterceptorClassName,
            PropertyName: prop.PropertyName,
            DeclaringInterface: "",
            ValueType: prop.ReturnType,
            NullableValueType: prop.NullableReturnType,
            DefaultExpression: "default!",
            HasGetter: prop.HasGetter,
            HasSetter: prop.HasSetter,
            IsInitOnly: false,
            ReturnsByRef: prop.ReturnsByRef,
            ReturnsByRefReadonly: prop.ReturnsByRefReadonly);
    }

    private static UnifiedIndexerInterceptorModel ToUnifiedIndexerModel(InlineClassIndexerModel indexer)
    {
        var paramTypes = indexer.ParameterDeclarations.Split(',').Select(p => { var parts = p.Trim().Split(' '); return parts[parts.Length - 2]; }).ToArray();
        var paramList = string.Join(", ", paramTypes);

        // For source delegation, compute flattened argument list from key expression
        var argumentList = indexer.KeyExpression.StartsWith("(") && indexer.KeyExpression.EndsWith(")")
            ? indexer.KeyExpression.Substring(1, indexer.KeyExpression.Length - 2)
            : indexer.KeyExpression;

        return new UnifiedIndexerInterceptorModel(
            InterceptorClassName: indexer.InterceptorClassName,
            IndexerName: indexer.IndexerName,
            DeclaringInterface: "",
            KeyType: indexer.KeyType,
            NullableKeyType: MakeNullable(indexer.KeyType),
            KeyParamName: "key",
            KeyTypeFriendlyName: indexer.KeyTypeFriendlyName,
            ValueType: indexer.ReturnType,
            NullableValueType: MakeNullable(indexer.ReturnType),
            DefaultExpression: "default!",
            HasGetter: indexer.HasGetter,
            HasSetter: indexer.HasSetter,
            ParameterSignature: indexer.ParameterDeclarations,
            ParameterTypes: paramList,
            KeyExpression: indexer.KeyExpression,
            ArgumentList: argumentList,
            ReturnsByRef: indexer.ReturnsByRef,
            ReturnsByRefReadonly: indexer.ReturnsByRefReadonly);
    }

    #endregion

    #region Helper Methods

    private static string FormatTypeParameters(EquatableArray<TypeParameterModel> typeParameters)
    {
        if (typeParameters.Count == 0)
            return "";
        return $"<{string.Join(", ", typeParameters.Select(tp => tp.Name))}>";
    }

    private static string FormatConstraints(EquatableArray<TypeParameterModel> typeParameters)
    {
        var clauses = new List<string>();
        foreach (var tp in typeParameters)
        {
            if (!string.IsNullOrEmpty(tp.Constraints))
            {
                clauses.Add($" where {tp.Name} : {tp.Constraints}");
            }
        }
        return string.Join("", clauses);
    }

    private static string MakeNullable(string type)
    {
        if (type.EndsWith("?"))
            return type;
        return type + "?";
    }

    /// <summary>
    /// Strips ref/in/out prefixes from an argument list string.
    /// Pre-compiled interceptors use plain parameters, not ref/in/out.
    /// </summary>
    private static string StripRefPrefixes(string argumentList)
    {
        if (string.IsNullOrEmpty(argumentList))
            return argumentList;

        var args = argumentList.Split(',');
        var cleanArgs = new List<string>();
        foreach (var arg in args)
        {
            var trimmed = arg.Trim();
            if (trimmed.StartsWith("in "))
                trimmed = trimmed.Substring(3);
            else if (trimmed.StartsWith("ref "))
                trimmed = trimmed.Substring(4);
            else if (trimmed.StartsWith("out "))
                trimmed = trimmed.Substring(4);
            cleanArgs.Add(trimmed);
        }
        return string.Join(", ", cleanArgs);
    }

    private static string ExtractSimpleTypeName(string fullName)
    {
        var name = fullName;
        if (name.StartsWith("global::"))
            name = name.Substring(8);

        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
            return name.Substring(lastDot + 1);

        return name;
    }

    private static string GetDefaultForType(string typeName, DefaultValueStrategy strategy, string? concreteType)
    {
        if (typeName == "global::System.Threading.Tasks.ValueTask" || typeName == "ValueTask")
            return "default";

        if (typeName == "global::System.Threading.Tasks.Task" || typeName == "Task")
            return "global::System.Threading.Tasks.Task.CompletedTask";

        if (typeName.Contains("ValueTask<") || typeName.Contains("global::System.Threading.Tasks.ValueTask<"))
        {
            var innerType = ExtractGenericArg(typeName);
            if (!string.IsNullOrEmpty(innerType))
            {
                if (strategy == DefaultValueStrategy.NewInstance)
                {
                    var innerTypeToNew = concreteType ?? innerType;
                    return $"new global::System.Threading.Tasks.ValueTask<{innerType}>(new {innerTypeToNew}())";
                }
                return "default";
            }
            return "default";
        }

        if (typeName.Contains("Task<") || typeName.Contains("global::System.Threading.Tasks.Task<"))
        {
            var innerType = ExtractGenericArg(typeName);
            if (!string.IsNullOrEmpty(innerType))
            {
                var innerTypeToNew = concreteType ?? innerType;
                var innerValue = strategy switch
                {
                    DefaultValueStrategy.NewInstance => $"new {innerTypeToNew}()",
                    DefaultValueStrategy.Default => "default!",
                    _ => "default!"
                };
                return $"global::System.Threading.Tasks.Task.FromResult<{innerType}>({innerValue})";
            }
            return "global::System.Threading.Tasks.Task.CompletedTask";
        }

        var typeToNew = concreteType ?? typeName;
        return strategy switch
        {
            DefaultValueStrategy.NewInstance => $"new {typeToNew}()",
            DefaultValueStrategy.Default => "default!",
            _ => "default!"
        };
    }

    private static string ExtractGenericArg(string typeName)
    {
        var start = typeName.IndexOf('<');
        var end = typeName.LastIndexOf('>');
        if (start >= 0 && end > start)
        {
            return typeName.Substring(start + 1, end - start - 1);
        }
        return "";
    }

    #endregion
}
